import { expect, test, type Page } from '@playwright/test';
import { createExpedition, generateChunk } from '@shards/game-core';
import { gameContent } from '@shards/game-data';
import type { GridPoint } from '@shards/shared';
import { chunkRegions, regionAt } from '../../packages/game-core/src/world/regions';
import { tileToScreen } from '../../apps/client/src/world/projection';
import { cameraView, clearFixtureEnemies, clickTile, expectActorPosition, firstCampSpawn, loadExpeditionFixture, loadPartyAt, placeFixtureParty, ready } from './world-helpers';

async function expectMovementMarker(page: Page, point: GridPoint, blocked: boolean, hover = true) {
  const view = await cameraView(page);
  const center = tileToScreen(point, view);
  if (hover) await page.mouse.move(center.x, center.y);
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
  // Inspect the actual painted canvas: diagonal rim samples distinguish a circle
  // from the former square, while the inner samples distinguish the blocked X.
  const ink = blocked ? [209, 139, 118] : [232, 216, 161];
  const samples = await page.locator('.world-surface canvas').evaluate((element, args) => {
    const canvas = element as HTMLCanvasElement;
    const bounds = canvas.getBoundingClientRect();
    const scale = canvas.width / bounds.width;
    const context = canvas.getContext('2d')!;
    const hasInk = (dx: number, dy: number) => {
      const x = Math.round((args.center.x + dx * args.zoom) * scale);
      const y = Math.round((args.center.y + dy * args.zoom) * scale);
      const data = context.getImageData(x - 1, y - 1, 3, 3).data;
      for (let index = 0; index < data.length; index += 4) {
        if (args.ink.every((channel, offset) => Math.abs(data[index + offset] - channel) < 17)) return true;
      }
      return false;
    };
    return {
      rim: Array.from({ length: 8 }, (_, index) => {
        const angle = index * Math.PI / 4;
        return hasInk(Math.cos(angle) * 12, Math.sin(angle) * 12);
      }),
      cross: [[-4, -4], [4, 4], [-4, 4], [4, -4]].map(([x, y]) => hasInk(x, y)),
    };
  }, { center, zoom: view.zoom, ink });
  expect(samples.rim).toEqual(Array(8).fill(true));
  expect(samples.cross).toEqual(Array(4).fill(blocked));
}

test('the ground cursor paints a round rim and adds a matching cross over fire without a notice', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await ready(page);
  await expectMovementMarker(page, { x: 19, y: 19 }, false);
  await page.screenshot({ path: 'test-results/movement-cursor-reachable.png' });
  await expectMovementMarker(page, { x: 17, y: 17 }, true);
  await page.screenshot({ path: 'test-results/movement-cursor-blocked.png' });
  await clickTile(page, { x: 17, y: 17 });
  await expect(page.locator('.game-notice')).toHaveCount(0);
  await expectActorPosition(page, firstCampSpawn);
});

test('the route destination keeps its whole ring above an opaque roof without opening the house', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await ready(page);
  await loadPartyAt(page, { x: 8, y: 13 });
  const target = { x: 8, y: 8 };
  await clickTile(page, target);
  // Pause while still outside so the roof remains opaque and the route remains visible.
  await page.getByRole('button', { name: 'Меню', exact: true }).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByTestId('world-canvas')).toHaveAttribute('data-revealed-house-roofs', '0');
  await expectMovementMarker(page, target, false, false);
  await page.screenshot({ path: 'test-results/movement-destination-overlay.png' });
});

test('walkable ground in a disconnected area has the blocked cursor and rejects clicks silently', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await ready(page);
  const state = createExpedition('FIRST-CAMPFIRE', ['guardian'], gameContent);
  const targetId = '2,-2';
  // Build a valid discovered route in the real world graph, then restore it using
  // the public load UI. Geometry is regenerated by the production save loader.
  const routes = new Map([[state.world.graph.startId, [state.world.graph.startId]]]);
  const nodes = new Map(state.world.graph.nodes.map(node => [node.id, node]));
  for (const [id, route] of routes) {
    for (const neighbor of Object.values(nodes.get(id)!.exits)) {
      if (neighbor && !routes.has(neighbor)) routes.set(neighbor, [...route, neighbor]);
    }
    if (routes.has(targetId)) break;
  }
  const route = routes.get(targetId)!;
  expect(route).toBeDefined();
  const chunk = generateChunk(state.world.graph, targetId);
  const origin = { x: 13, y: 2 };
  const unreachable = { x: 15, y: 3 };
  const regions = chunkRegions(chunk);
  expect(chunk.tiles[unreachable.y * chunk.size + unreachable.x].walkable).toBe(true);
  expect(regionAt(chunk, regions, origin)).not.toBe(regionAt(chunk, regions, unreachable));
  Object.assign(state.world, {
    chunk, currentChunkId: targetId, visited: route, tick: route.length, transitions: route.length - 1,
    actors: placeFixtureParty(chunk, state.world.actors, origin),
  });
  clearFixtureEnemies(state);
  await loadExpeditionFixture(page, state);
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expectActorPosition(page, origin);
  await expectMovementMarker(page, unreachable, true);
  await page.screenshot({ path: 'test-results/movement-cursor-other-entrance.png' });
  await clickTile(page, unreachable);
  await expect(page.locator('.game-notice')).toHaveCount(0);
  await expectActorPosition(page, origin);
});
