import { createBossCatalog } from './boss-catalog-builders';

export const winterBossCatalog = createBossCatalog('winter', [
  {
    id: 'white_sovereign', name: 'Белый Государь', title: 'Корона последней зимы', role: 'tank', sprite: 'elite_warden', color: '#c1d9df',
    description: 'Метель покрывает отряд ледяными надломами. Государь выжидает за панцирем ледника и ослабляет противников приговором стужи.',
    stats: { maxHp: 800, power: 35, armor: 27, initiative: 5, crit: 5, evasion: 3, resilience: 10 }, support: ['boss_glacial_shell', 'boss_winter_edict'],
    signature: { name: 'Указ вечной метели', family: 'frost', cooldown: 5, target: 'allEnemies', projectile: 'frost',
      description: 'Каждому врагу — 2d8 + половина Силы. Попадание оставляет Ледяной надлом на 3 хода: броня −3 и 2d4 урона в конце хода.',
      actions: [{ type: 'damage', dice: '2d8', scaling: 'power', factor: .5, onHitStatusId: 'glacial_fracture', onHitDuration: 3 }], icon: { frame: 'rays', motif: 'crystal', accent: 'shield' } },
  },
  {
    id: 'polar_devourer', name: 'Пожиратель Полярной Ночи', title: 'Пасть за краем света', role: 'damage', sprite: 'wolf', color: '#a6b8d0',
    description: 'Три укуса промораживают одну цель. Ночная мантия и кровь поддерживают хищника, пока отряд борется с накапливающимся уроном.',
    stats: { maxHp: 650, power: 35, armor: 18, initiative: 11, crit: 7, evasion: 7 }, support: ['boss_night_mantle', 'boss_blood_feast'],
    signature: { name: 'Голод без рассвета', family: 'frost', cooldown: 4, target: 'enemy', projectile: 'frost',
      description: 'Три независимых удара на 1d10 + треть Силы. Каждый успех добавляет Обморожение на 2 хода: уклонение −1 и 1d4 урона без брони в начале хода.',
      actions: [{ type: 'damage', dice: '1d10', scaling: 'power', factor: 1 / 3, hits: 3, onHitStatusId: 'frostbite', onHitDuration: 2 }], icon: { frame: 'arrows', motif: 'fang', accent: 'moon' } },
  },
  {
    id: 'glass_empress', name: 'Императрица Ледяного Стекла', title: 'Преломлённый свет севера', role: 'damage', sprite: 'goblin_shaman', color: '#acc7ee',
    description: 'Лучами за один ход оставляет несколько ожогов эфира. Стеклянный панцирь позволяет дождаться новой серии, а клятва звёзд усиливает каждый луч.',
    stats: { maxHp: 610, power: 32, armor: 17, initiative: 10, crit: 6, evasion: 7 }, support: ['boss_glacial_shell', 'boss_stellar_oath'],
    signature: { name: 'Четыре грани севера', family: 'arcane', cooldown: 5, target: 'randomEnemy', projectile: 'arcane',
      description: 'Четыре луча по одной случайной цели, каждый на 1d8 + четверть Силы. Каждый успех добавляет Ожог эфира на 2 хода: 1d6 урона без брони в начале хода.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', factor: .25, hits: 4, onHitStatusId: 'mana_scorch', onHitDuration: 2 }], icon: { frame: 'arrows', motif: 'crystal', accent: 'rune' } },
  },
  {
    id: 'grave_frost', name: 'Могильный Мороз', title: 'Страж нетронутого снега', role: 'tank', sprite: 'slime', color: '#a8bbb7',
    description: 'Ослабляет урон всего отряда и разбрасывает холодные кости. Соединяет костяные щиты с восстановлением оттепели.',
    stats: { maxHp: 760, power: 33, armor: 24, initiative: 3, crit: 4, evasion: 2 }, support: ['boss_ossuary_wall', 'boss_last_thaw'],
    signature: { name: 'Снег поверх имён', family: 'spirit', cooldown: 5, target: 'allEnemies', projectile: 'bone',
      description: 'На 2 хода весь отряд получает Белое безмолвие: Сила и урон −3. Затем каждому врагу — 1d12 + половина Силы; попадание накладывает Бледное возмездие на 2 хода.',
      actions: [{ type: 'status', statusId: 'white_silence', duration: 2 }, { type: 'damage', dice: '1d12', scaling: 'power', factor: .5, onHitStatusId: 'pale_rebuke', onHitDuration: 2 }], icon: { frame: 'weave', motif: 'bone', accent: 'crystal' } },
  },
  {
    id: 'starved_aurora', name: 'Голодное Сияние', title: 'Пожар на мёртвом небе', role: 'damage', sprite: 'goblin_archer', color: '#b3a2ed',
    description: 'За полярным светом остаётся след кометы, поражающий отряд без брони. Сияние повышает точность и крит перед следующей волной.',
    stats: { maxHp: 590, power: 32, armor: 14, initiative: 13, crit: 6, evasion: 8 }, support: ['boss_stellar_oath', 'boss_predators_gaze'],
    signature: { name: 'Северное пожирание', family: 'astral', cooldown: 5, target: 'allEnemies', projectile: 'arcane',
      description: 'По каждому врагу — 1d12 + половина Силы. Попадание оставляет След кометы на 2 хода: 2d4 урона без брони в конце хода. Сияние получает Лунную благодать на 1 ход.',
      actions: [{ type: 'damage', dice: '1d12', scaling: 'power', factor: .5, onHitStatusId: 'comet_wake', onHitDuration: 2 }, { type: 'status', statusId: 'lunar_grace', duration: 1, target: 'self' }], icon: { frame: 'rays', motif: 'star', accent: 'moon' } },
  },
  {
    id: 'frozen_executioner', name: 'Палач Замёрзших Клятв', title: 'Лезвие над белой плахой', role: 'damage', sprite: 'goblin_scout', color: '#b9c3d3',
    description: 'Прицеливается в самого раненого и может гарантированно критовать двумя ударами. С его ледяной защитой нужно разбираться до следующей казни.',
    stats: { maxHp: 640, power: 36, armor: 21, initiative: 8, crit: 6, evasion: 4 }, support: ['boss_glacial_shell', 'boss_rending_sweep'],
    signature: { name: 'Казнь подо льдом', family: 'metal', cooldown: 6, target: 'lowestHealthEnemy',
      description: 'Смертельная точность на 1 ход делает успешные попадания критическими. Затем дважды атакует самого раненого врага на 1d8 + треть Силы; каждый удар отдельно проверяет попадание.',
      actions: [{ type: 'status', statusId: 'sure_strike', duration: 1, target: 'self' }, { type: 'damage', dice: '1d8', scaling: 'power', factor: 1 / 3, hits: 2 }], icon: { frame: 'slash', motif: 'blade', accent: 'crystal' } },
  },
  {
    id: 'mother_white_web', name: 'Мать Белой Паутины', title: 'Саван заблудших путников', role: 'tank', sprite: 'spider', color: '#bdd7cd',
    description: 'Паутина притупляет движения отряда, а ледяные иглы выбирают случайную цель. Споры и стужа продлевают её охоту.',
    stats: { maxHp: 680, power: 32, armor: 20, initiative: 8, crit: 4, evasion: 5 }, support: ['boss_spore_carapace', 'boss_winter_edict'],
    signature: { name: 'Саван из шести игл', family: 'frost', cooldown: 5, target: 'randomEnemy', projectile: 'frost',
      description: 'Весь отряд получает Корневую хватку на 2 хода (уклонение и проворность −3). По одной случайной цели — шесть отдельных попаданий на 1d4, каждый успех добавляет Обморожение на 1 ход.',
      actions: [{ type: 'status', statusId: 'rootbound', duration: 2, target: 'allEnemies' }, { type: 'damage', dice: '1d4', hits: 6, onHitStatusId: 'frostbite', onHitDuration: 1 }], icon: { frame: 'weave', motif: 'fang', accent: 'crystal' } },
  },
  {
    id: 'iron_icebreaker', name: 'Железный Ледолом', title: 'Таран затонувших крепостей', role: 'tank', sprite: 'boar', color: '#9cb9ca',
    description: 'Разбивает защиту цели двумя сокрушительными ударами. Очень прочен, медлителен, способен восстановить себя и ослабить весь отряд.',
    stats: { maxHp: 830, power: 38, armor: 30, initiative: 1, crit: 3, evasion: 1, resilience: 11 }, support: ['boss_last_thaw', 'boss_winter_edict'],
    signature: { name: 'Сломанный материк', family: 'stone', cooldown: 5, target: 'enemy', projectile: 'stone',
      description: 'Сначала Линия разлома на 3 хода: броня −8, проворность −1. Затем два удара на 2d6 + треть Силы. Ледолом получает Решимость горы на 1 ход: уменьшение урона на 5.',
      actions: [{ type: 'status', statusId: 'fault_line', duration: 3 }, { type: 'damage', dice: '2d6', scaling: 'power', factor: 1 / 3, hits: 2 }, { type: 'status', statusId: 'mountain_resolve', duration: 1, target: 'self' }], icon: { frame: 'burst', motif: 'rock', accent: 'shield' } },
  },
  {
    id: 'last_hour_keeper', name: 'Сторож Последнего Часа', title: 'Песок под вечным льдом', role: 'healer', sprite: 'goblin_shaman', color: '#ccbfa0',
    description: 'Эрозия времени действует до начала следующей атаки, а ледяной щит и оттепель держат сторожа в строю. Его часы не переставляют инициативу в середине боя.',
    stats: { maxHp: 650, power: 31, armor: 18, initiative: 12, crit: 5, evasion: 6 }, support: ['boss_glacial_shell', 'boss_last_thaw'],
    signature: { name: 'Когда кончится снег', family: 'time', cooldown: 5, target: 'allEnemies', projectile: 'arcane',
      description: 'Каждому врагу — 2d6 + половина Силы, при попадании Эрозия мгновений на 2 хода (1d6 урона без брони в начале хода). Сторож получает Заимствованный миг на 2 хода: повтор базовой атаки на 4 при 1d4.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', factor: .5, onHitStatusId: 'chronal_erosion', onHitDuration: 2 }, { type: 'status', statusId: 'borrowed_moment', duration: 2, target: 'self' }], icon: { frame: 'orbit', motif: 'hourglass', accent: 'crystal' } },
  },
  {
    id: 'black_snow_abbess', name: 'Игуменья Чёрного Снега', title: 'Молитва без утешения', role: 'healer', sprite: 'goblin_shaman', color: '#b7a9c8',
    description: 'Лишает весь отряд точности и критов, наказывая самую раненую цель. Для долгой схватки у неё есть костяные щиты и исцеление.',
    stats: { maxHp: 675, power: 33, armor: 19, initiative: 6, crit: 5, evasion: 4 }, support: ['boss_grave_mending', 'boss_ossuary_wall'],
    signature: { name: 'Молитва замёрзших губ', family: 'spirit', cooldown: 5, target: 'lowestHealthEnemy', projectile: 'shadow',
      description: 'Всем врагам на 2 хода Погребальный плач: точность и крит −2. Самой раненой цели — удар на 3d8 + половину Силы; попадание оставляет Ночную рану на 3 хода.',
      actions: [{ type: 'status', statusId: 'funeral_lament', duration: 2, target: 'allEnemies' }, { type: 'damage', dice: '3d8', scaling: 'power', factor: .5, onHitStatusId: 'night_wound', onHitDuration: 3 }], icon: { frame: 'seal', motif: 'skull', accent: 'cross' } },
  },
  {
    id: 'comet_wolf', name: 'Волк Упавшей Кометы', title: 'Охотник меж холодных звёзд', role: 'damage', sprite: 'wolf', color: '#bcb0e5',
    description: 'Сначала усиливает точность, затем совершает два прыжка по случайной жертве. След кометы игнорирует броню, а охота и звёздная клятва усиливают повторные удары.',
    stats: { maxHp: 625, power: 35, armor: 17, initiative: 14, crit: 7, evasion: 7 }, support: ['boss_stellar_oath', 'boss_hunting_fervor'],
    signature: { name: 'Прыжок через созвездие', family: 'astral', cooldown: 4, target: 'randomEnemy', projectile: 'arcane',
      description: 'На 1 ход получает Звёздную точность: точность +4, крит +1. Затем два удара по одной случайной цели на 1d12 + треть Силы; попадания оставляют След кометы на 2 хода.',
      actions: [{ type: 'status', statusId: 'stellar_precision', duration: 1, target: 'self' }, { type: 'damage', dice: '1d12', scaling: 'power', factor: 1 / 3, hits: 2, onHitStatusId: 'comet_wake', onHitDuration: 2 }], icon: { frame: 'slash', motif: 'fang', accent: 'star' } },
  },
  {
    id: 'heart_of_last_glacier', name: 'Сердце Последнего Ледника', title: 'Тишина после всех времён года', role: 'tank', sprite: 'elite_warden', color: '#adcfd6',
    description: 'Холод пустоты подавляет броню и крит всего отряда. Сердце лечится оттепелью и обращает силу холодных звёзд против любого, кто пережил зиму.',
    stats: { maxHp: 810, power: 36, armor: 26, initiative: 4, crit: 5, evasion: 2, resilience: 10 }, support: ['boss_last_thaw', 'boss_stellar_oath'],
    signature: { name: 'Пустота под материком', family: 'astral', cooldown: 6, target: 'allEnemies', projectile: 'frost',
      description: 'Весь отряд получает Холод пустоты на 2 хода: броня −4, крит −3, проворность −2. Затем каждому врагу — удар на 3d6 + половину Силы. Сердце получает щит на 3d8 на 2 хода.',
      actions: [{ type: 'status', statusId: 'void_chill', duration: 2 }, { type: 'damage', dice: '3d6', scaling: 'power', factor: .5 }, { type: 'shield', dice: '3d8', duration: 2, target: 'self' }], icon: { frame: 'ward', motif: 'crystal', accent: 'moon' } },
  },
]);
