import { createBossCatalog } from './boss-catalog-builders';

export const springBossCatalog = createBossCatalog('spring', [
  {
    id: 'briar_king', name: 'Кряж, Дубовый король', title: 'Владыка переплетённых корней', role: 'tank', sprite: 'elite_warden', color: '#b8c56a',
    description: 'Сковывает весь отряд корнями, пережидает ответные удары за корой и восстанавливается соком рощи. Нужны устойчивый урон и запас лечения.',
    stats: { maxHp: 400, power: 20, armor: 18, initiative: 3, crit: 3, evasion: 2 },
    support: ['boss_briar_wall', 'boss_green_renewal'],
    signature: { name: 'Трон из корней', family: 'nature', cooldown: 4, target: 'allEnemies', projectile: 'nature',
      description: 'Каждому противнику — 2d6 + половина Силы. Попадание накладывает Корневую хватку на 2 хода: уклонение и проворность −3.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', factor: .5, onHitStatusId: 'rootbound', onHitDuration: 2 }], icon: { frame: 'weave', motif: 'leaf', accent: 'shield' } },
  },
  {
    id: 'thousand_fangs', name: 'Мать Тысячи Клыков', title: 'Прародительница весеннего выводка', role: 'damage', sprite: 'spider', color: '#b5ab68',
    description: 'Три последовательных укуса оставляют отдельные заряды яда. За споровым щитом готовит усиленную охоту.',
    stats: { maxHp: 290, power: 17, armor: 9, initiative: 9, crit: 4, evasion: 6 },
    support: ['boss_spore_carapace', 'boss_hunting_fervor'],
    signature: { name: 'Тройной выводок', family: 'venom', cooldown: 4, target: 'enemy', projectile: 'poison',
      description: 'Три независимых попадания, каждое на 1d6 + треть Силы. Каждый успех добавляет Яд на 2 хода: 1d4 урона в конце хода цели за заряд.',
      actions: [{ type: 'damage', dice: '1d6', hits: 3, scaling: 'power', factor: 1 / 3, onHitStatusId: 'poisoned', onHitDuration: 2 }], icon: { frame: 'arrows', motif: 'fang', accent: 'drop' } },
  },
  {
    id: 'first_thunder', name: 'Рогач Первой Грозы', title: 'Бегущий по ливням', role: 'damage', sprite: 'boar', color: '#9fc6ce',
    description: 'Один мощный разряд пробивает защиту цели, после чего разрывающий удар пользуется оставленной меткой. Усиление охоты повышает точность.',
    stats: { maxHp: 320, power: 21, armor: 12, initiative: 8, crit: 4, evasion: 4 },
    support: ['boss_hunting_fervor', 'boss_rending_sweep'],
    signature: { name: 'Рога громового неба', family: 'storm', cooldown: 4, target: 'enemy', projectile: 'lightning',
      description: 'Удар на 2d10 + половину Силы. Попадание оставляет Проводящую метку на 3 хода: броня −4, точность −1.',
      actions: [{ type: 'damage', dice: '2d10', scaling: 'power', factor: .5, onHitStatusId: 'conductive_brand', onHitDuration: 3 }], icon: { frame: 'slash', motif: 'bolt', accent: 'claw' } },
  },
  {
    id: 'blind_florist', name: 'Слепая Цветочница', title: 'Садовница чёрной пыльцы', role: 'healer', sprite: 'goblin_shaman', color: '#d7a3bf',
    description: 'Пыльца снижает точность отряда. Цветочница укрепляется спорами и лечится, заставляя готовить точное оружие и продолжительные эффекты.',
    stats: { maxHp: 285, power: 18, armor: 8, initiative: 7, crit: 2, evasion: 5 },
    support: ['boss_spore_carapace', 'boss_green_renewal'],
    signature: { name: 'Пыльца без глаз', family: 'nature', cooldown: 5, target: 'allEnemies', projectile: 'nature',
      description: 'На 2 хода накладывает на весь отряд Тьму в глазах (точность −4), затем атакует каждого на 1d8 + треть Силы. Пыльца остаётся и при промахе.',
      actions: [{ type: 'status', statusId: 'blackout', duration: 2 }, { type: 'damage', dice: '1d8', scaling: 'power', factor: 1 / 3 }], icon: { frame: 'burst', motif: 'leaf', accent: 'eye' } },
  },
  {
    id: 'torn_leaves', name: 'Герцог Рваных Листьев', title: 'Дуэлянт тернового двора', role: 'damage', sprite: 'goblin_scout', color: '#bd886b',
    description: 'Обрушивает несколько порезов на случайную жертву. Перед следующим выпадом усиливает крит и точность; его кровотечение игнорирует броню.',
    stats: { maxHp: 280, power: 18, armor: 10, initiative: 10, crit: 6, evasion: 6 },
    support: ['boss_predators_gaze', 'boss_rending_sweep'],
    signature: { name: 'Четыре сорванных лепестка', family: 'war', cooldown: 5, target: 'randomEnemy',
      description: 'Выбирает случайного противника броском кубика и четырежды атакует его на 1d4. Каждое попадание добавляет Кровотечение на 2 хода.',
      actions: [{ type: 'damage', dice: '1d4', hits: 4, onHitStatusId: 'bleeding', onHitDuration: 2 }], icon: { frame: 'arrows', motif: 'blade', accent: 'leaf' } },
  },
  {
    id: 'meltwater_lady', name: 'Хозяйка Талых Вод', title: 'Королева затопленных троп', role: 'healer', sprite: 'slime', color: '#79bdbe',
    description: 'Накрывает отряд холодной волной и немедленно восстанавливает себя. Чередует ледяной щит и расцвет рощи.',
    stats: { maxHp: 320, power: 18, armor: 10, initiative: 5, crit: 3, evasion: 3 },
    support: ['boss_glacial_shell', 'boss_green_renewal'],
    signature: { name: 'Половодье', family: 'frost', cooldown: 5, target: 'allEnemies', projectile: 'frost',
      description: 'По каждому врагу — 1d10 + треть Силы, при попадании Обморожение на 2 хода. После волны лечит себя на 2d6 без бонуса Силы.',
      actions: [{ type: 'damage', dice: '1d10', scaling: 'power', factor: 1 / 3, onHitStatusId: 'frostbite', onHitDuration: 2 }, { type: 'heal', dice: '2d6', target: 'self' }], icon: { frame: 'weave', motif: 'crystal', accent: 'leaf' } },
  },
  {
    id: 'moss_colossus', name: 'Мшистый Исполин', title: 'Гора, которая проснулась', role: 'tank', sprite: 'elite_warden', color: '#78956b',
    description: 'Тяжёлый удар разрушает броню, а каменная оболочка даёт ему время пережить ответ. Медленный противник с большим запасом прочности.',
    stats: { maxHp: 420, power: 23, armor: 20, initiative: 1, crit: 2, evasion: 1, resilience: 7 },
    support: ['boss_briar_wall', 'boss_rending_sweep'],
    signature: { name: 'Трещина под ногами', family: 'stone', cooldown: 5, target: 'enemy', projectile: 'stone',
      description: 'Удар на 3d6 + половину Силы. Попадание создаёт Линию разлома на 3 хода: броня −8, проворность −1. Исполин получает Гранитную кожу на 1 ход: броня +9.',
      actions: [{ type: 'damage', dice: '3d6', scaling: 'power', factor: .5, onHitStatusId: 'fault_line', onHitDuration: 3 }, { type: 'status', statusId: 'granite_skin', duration: 1, target: 'self' }], icon: { frame: 'burst', motif: 'rock', accent: 'leaf' } },
  },
  {
    id: 'plague_beekeeper', name: 'Пчельник Морового Мёда', title: 'Хранитель гибельного улья', role: 'damage', sprite: 'goblin_shaman', color: '#d6bc5c',
    description: 'Рой разъедает броню всего отряда. Сам Пчельник прячется в спорах и пьёт кровь раненых.',
    stats: { maxHp: 300, power: 17, armor: 11, initiative: 6, crit: 3, evasion: 4 },
    support: ['boss_spore_carapace', 'boss_blood_feast'],
    signature: { name: 'Улей под рёбрами', family: 'venom', cooldown: 4, target: 'allEnemies', projectile: 'poison',
      description: 'Каждому врагу наносит 1d6 + половину Силы. Попадание накладывает Ядовитую коррозию на 3 хода: броня −3 и 1d4 урона в конце хода.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', factor: .5, onHitStatusId: 'toxic_corrosion', onHitDuration: 3 }], icon: { frame: 'orbit', motif: 'fang', accent: 'leaf' } },
  },
  {
    id: 'silver_huntress', name: 'Сребролунная Охотница', title: 'Первая стрела новолуния', role: 'damage', sprite: 'goblin_archer', color: '#a1b3d5',
    description: 'Преследует самого раненого. Две лунные стрелы оставляют рану и прикрывают охотницу уклонением.',
    stats: { maxHp: 270, power: 19, armor: 8, initiative: 11, crit: 5, evasion: 7, accuracy: 5 },
    support: ['boss_hunting_fervor', 'boss_predators_gaze'],
    signature: { name: 'Две луны в ране', family: 'astral', cooldown: 4, target: 'lowestHealthEnemy', projectile: 'arrow',
      description: 'Два независимых удара по самому раненому врагу, каждый на 1d8 + треть Силы. Попадание добавляет Ночную рану на 2 хода. Охотница получает Лунную благодать на 1 ход.',
      actions: [{ type: 'damage', dice: '1d8', hits: 2, scaling: 'power', factor: 1 / 3, onHitStatusId: 'night_wound', onHitDuration: 2 }, { type: 'status', statusId: 'lunar_grace', duration: 1, target: 'self' }], icon: { frame: 'arrows', motif: 'moon', accent: 'blade' } },
  },
  {
    id: 'reed_tyrant', name: 'Тростниковый Тиран', title: 'Повелитель болотных знамен', role: 'tank', sprite: 'goblin_scout', color: '#aeb583',
    description: 'Изматывает сразу всех противников и усиливает собственный натиск. Его броня уступает королевской коре, зато он точнее и агрессивнее.',
    stats: { maxHp: 355, power: 20, armor: 16, initiative: 6, crit: 4, evasion: 3 },
    support: ['boss_rending_sweep', 'boss_hunting_fervor'],
    signature: { name: 'Приказ гнуть колени', family: 'war', cooldown: 5, target: 'allEnemies',
      description: 'Каждому противнику — 1d8 + половина Силы. Попадание вызывает Боевое истощение на 2 хода: урон −3, уклонение −2. Тиран получает Боевой транс на 2 хода.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', factor: .5, onHitStatusId: 'battle_fatigue', onHitDuration: 2 }, { type: 'status', statusId: 'battle_trance', duration: 2, target: 'self' }], icon: { frame: 'seal', motif: 'claw', accent: 'shield' } },
  },
  {
    id: 'buried_bell', name: 'Погребённый Звонарь', title: 'Голос под корнями', role: 'healer', sprite: 'goblin_shaman', color: '#93b8ad',
    description: 'Погребальный звон ослабляет прицел и крит всего отряда. Костяная защита и память мёртвых поддерживают затяжной бой.',
    stats: { maxHp: 310, power: 18, armor: 12, initiative: 4, crit: 3, evasion: 3 },
    support: ['boss_ossuary_wall', 'boss_grave_mending'],
    signature: { name: 'Третий погребальный звон', family: 'spirit', cooldown: 5, target: 'allEnemies', projectile: 'bone',
      description: 'Погребальный плач на 2 хода всем врагам снижает точность и крит на 2. Затем звон атакует каждого на 1d10 + треть Силы.',
      actions: [{ type: 'status', statusId: 'funeral_lament', duration: 2 }, { type: 'damage', dice: '1d10', scaling: 'power', factor: 1 / 3 }], icon: { frame: 'rays', motif: 'skull', accent: 'leaf' } },
  },
  {
    id: 'red_antler', name: 'Краснорог, Зверь Пробуждения', title: 'Голод под молодой травой', role: 'damage', sprite: 'wolf', color: '#c58578',
    description: 'Один глубокий укус ослабляет Силу цели и лечит хищника. После зова охоты усиливает каждый последующий удар.',
    stats: { maxHp: 335, power: 22, armor: 11, initiative: 8, crit: 5, evasion: 4 },
    support: ['boss_hunting_fervor', 'boss_blood_feast'],
    signature: { name: 'Пробуждённый голод', family: 'blood', cooldown: 4, target: 'enemy', projectile: 'blood',
      description: 'Удар на 2d8 + половину Силы; попадание наносит Рваную рану на 3 хода (Сила −2, 1d6 урона без брони в конце хода). Затем зверь лечит себя на 1d8.',
      actions: [{ type: 'damage', dice: '2d8', scaling: 'power', factor: .5, onHitStatusId: 'open_wound', onHitDuration: 3 }, { type: 'heal', dice: '1d8', target: 'self' }], icon: { frame: 'slash', motif: 'fang', accent: 'drop' } },
  },
  {
    id: 'glass_seed', name: 'Стеклянное Семя', title: 'Сердце невозможной рощи', role: 'tank', sprite: 'slime', color: '#b0cee0',
    description: 'Эфирные осколки прожигают броню периодическим уроном. Стеклянное Семя сочетает споровый и ледяной щиты.',
    stats: { maxHp: 340, power: 18, armor: 14, initiative: 5, crit: 4, evasion: 4 },
    support: ['boss_glacial_shell', 'boss_spore_carapace'],
    signature: { name: 'Прорастание сквозь стекло', family: 'arcane', cooldown: 4, target: 'randomEnemy', projectile: 'arcane',
      description: 'Три независимых осколка по одной случайной цели, каждый на 1d6. Попадания добавляют Ожог эфира на 2 хода: 1d6 урона без брони в начале хода за заряд. На 1 ход получает Зеркальный покров.',
      actions: [{ type: 'damage', dice: '1d6', hits: 3, onHitStatusId: 'mana_scorch', onHitDuration: 2 }, { type: 'status', statusId: 'mirror_ward', duration: 1, target: 'self' }], icon: { frame: 'orbit', motif: 'crystal', accent: 'leaf' } },
  },
]);
