import { createBossCatalog } from './boss-catalog-builders';

export const autumnBossCatalog = createBossCatalog('autumn', [
  {
    id: 'harvest_reaper', name: 'Жнец Последнего Урожая', title: 'Серп багряных полей', role: 'damage', sprite: 'goblin_scout', color: '#d69456',
    description: 'Один взмах открывает раны у всего отряда. Жнец умеет лечиться кровью и готовить следующий удар усилением критов.',
    stats: { maxHp: 530, power: 29, armor: 17, initiative: 8, crit: 6, evasion: 5 }, support: ['boss_blood_feast', 'boss_predators_gaze'],
    signature: { name: 'Последний сноп', family: 'blood', cooldown: 5, target: 'allEnemies',
      description: 'Каждому врагу — удар на 2d8 + половину Силы. Попадание оставляет Рваную рану на 2 хода: Сила −2 и 1d6 урона без брони в конце хода.',
      actions: [{ type: 'damage', dice: '2d8', scaling: 'power', factor: .5, onHitStatusId: 'open_wound', onHitDuration: 2 }], icon: { frame: 'slash', motif: 'blade', accent: 'leaf' } },
  },
  {
    id: 'hollow_duchess', name: 'Герцогиня Пустых Лиц', title: 'Хозяйка дома без окон', role: 'damage', sprite: 'goblin_shaman', color: '#bd94c2',
    description: 'Затмение отнимает у отряда Силу и точность. Ночной покров и костяная крепость вынуждают пережить несколько циклов её атак.',
    stats: { maxHp: 485, power: 27, armor: 13, initiative: 9, crit: 5, evasion: 7 }, support: ['boss_night_mantle', 'boss_ossuary_wall'],
    signature: { name: 'Бал без лиц', family: 'shadow', cooldown: 5, target: 'allEnemies', projectile: 'shadow',
      description: 'На 2 хода накладывает на каждого врага Затмение: точность −3, Сила −4. Затем атакует каждого на 1d12 + половину Силы.',
      actions: [{ type: 'status', statusId: 'eclipse', duration: 2 }, { type: 'damage', dice: '1d12', scaling: 'power', factor: .5 }], icon: { frame: 'weave', motif: 'moon', accent: 'eye' } },
  },
  {
    id: 'ossuary_archon', name: 'Архонт Оссуария', title: 'Свод из тысячи рёбер', role: 'tank', sprite: 'elite_warden', color: '#c6b898',
    description: 'Костяные копья оставляют урон, который проходит сквозь броню. Большая прочность и щиты требуют сильного сосредоточенного натиска.',
    stats: { maxHp: 650, power: 29, armor: 24, initiative: 3, crit: 4, evasion: 2, resilience: 9 }, support: ['boss_ossuary_wall', 'boss_grave_mending'],
    signature: { name: 'Колоннада рёбер', family: 'spirit', cooldown: 4, target: 'enemy', projectile: 'bone',
      description: 'Три независимых копья по одной цели, каждое на 1d8 + треть Силы. Попадания добавляют Бледное возмездие на 2 хода: 1d6 урона без брони в конце хода за заряд.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', factor: 1 / 3, hits: 3, onHitStatusId: 'pale_rebuke', onHitDuration: 2 }], icon: { frame: 'arrows', motif: 'bone', accent: 'skull' } },
  },
  {
    id: 'rot_gardener', name: 'Садовник Великой Гнили', title: 'Корень пожирающей осени', role: 'healer', sprite: 'thornling', color: '#aeb46e',
    description: 'Распространяет гибельный яд по всему отряду. Чтобы остановить его цикл щитов и лечения, нужны подготовленные предметы и сильные навыки.',
    stats: { maxHp: 575, power: 27, armor: 18, initiative: 4, crit: 3, evasion: 3 }, support: ['boss_spore_carapace', 'boss_green_renewal'],
    signature: { name: 'Сад, который ест', family: 'venom', cooldown: 5, target: 'allEnemies', projectile: 'poison',
      description: 'Каждому врагу — 1d10 + половина Силы. Попадание накладывает Гибельное дыхание на 2 хода: 1d8 урона без брони в начале хода.',
      actions: [{ type: 'damage', dice: '1d10', scaling: 'power', factor: .5, onHitStatusId: 'virulent_breath', onHitDuration: 2 }], icon: { frame: 'burst', motif: 'leaf', accent: 'skull' } },
  },
  {
    id: 'carrion_king', name: 'Король Вороньего Пира', title: 'Клюв над полем павших', role: 'damage', sprite: 'goblin_archer', color: '#ab8ead',
    description: 'Преследует слабейшего двумя смертельными клевками. Его попадания раскрывают раны, а теневая мантия затрудняет ответ.',
    stats: { maxHp: 470, power: 30, armor: 13, initiative: 12, crit: 7, evasion: 7 }, support: ['boss_night_mantle', 'boss_blood_feast'],
    signature: { name: 'Пир над последним вздохом', family: 'shadow', cooldown: 4, target: 'lowestHealthEnemy', projectile: 'shadow',
      description: 'Два удара по самой раненой цели, каждый на 1d10 + половину Силы. Попадания вызывают Кровотечение на 2 хода. Король получает Смертоносность на 1 ход.',
      actions: [{ type: 'damage', dice: '1d10', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'bleeding', onHitDuration: 2 }, { type: 'status', statusId: 'lethality', duration: 1, target: 'self' }], icon: { frame: 'arrows', motif: 'feather', accent: 'fang' } },
  },
  {
    id: 'rust_marshal', name: 'Маршал Ржавых Знамён', title: 'Последний воин павшей дружины', role: 'tank', sprite: 'goblin_scout', color: '#bc8668',
    description: 'Ржавчина ослабляет броню и урон противников. Маршал наращивает точность и разрывает защиту выбранной жертвы.',
    stats: { maxHp: 610, power: 31, armor: 23, initiative: 5, crit: 5, evasion: 3 }, support: ['boss_predators_gaze', 'boss_rending_sweep'],
    signature: { name: 'Парад рыжего железа', family: 'metal', cooldown: 5, target: 'allEnemies', projectile: 'stone',
      description: 'Каждому врагу — 2d6 + половина Силы. Попадание накладывает Ржавчину на 3 хода: броня −5 и урон −2. Маршал получает Закалённую волю на 2 хода.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', factor: .5, onHitStatusId: 'rust', onHitDuration: 3 }, { type: 'status', statusId: 'tempered_will', duration: 2, target: 'self' }], icon: { frame: 'ward', motif: 'blade', accent: 'shield' } },
  },
  {
    id: 'blood_granary', name: 'Амбар Кровавых Десятин', title: 'Голод, обретший плоть', role: 'tank', sprite: 'slime', color: '#a95867',
    description: 'Выдерживает долгий бой и пожирает здоровье одного противника за раз. Во время охоты каждый удар становится сильнее.',
    stats: { maxHp: 630, power: 30, armor: 17, initiative: 2, crit: 4, evasion: 1 }, support: ['boss_blood_feast', 'boss_hunting_fervor'],
    signature: { name: 'Десятина живой плоти', family: 'blood', cooldown: 4, target: 'enemy', projectile: 'blood',
      description: 'Атакует цель на 3d8 + половину Силы, затем восстанавливает себе 2d10. На 2 хода получает Змеиный голод: попадания лечат на 1d6, броня −2.',
      actions: [{ type: 'damage', dice: '3d8', scaling: 'power', factor: .5 }, { type: 'heal', dice: '2d10', target: 'self' }, { type: 'status', statusId: 'venom_hunger', duration: 2, target: 'self' }], icon: { frame: 'seal', motif: 'drop', accent: 'fang' } },
  },
  {
    id: 'last_lantern', name: 'Последний Фонарщик', title: 'Проводник ослепших душ', role: 'healer', sprite: 'goblin_shaman', color: '#b6c0a0',
    description: 'Свет его фонаря прожигает случайную цель и вызывает костяной вихрь. Способен усилить свои лучи клятвой холодных звёзд.',
    stats: { maxHp: 500, power: 27, armor: 14, initiative: 7, crit: 4, evasion: 5 }, support: ['boss_grave_mending', 'boss_stellar_oath'],
    signature: { name: 'Фонарь за чертой', family: 'spirit', cooldown: 5, target: 'randomEnemy', projectile: 'holy',
      description: 'Два луча по одной случайной цели, каждый на 1d12 + треть Силы. Попадание оставляет Ожог эфира на 2 хода. Фонарщик получает Костяной смерч на 2 хода.',
      actions: [{ type: 'damage', dice: '1d12', scaling: 'power', factor: 1 / 3, hits: 2, onHitStatusId: 'mana_scorch', onHitDuration: 2 }, { type: 'status', statusId: 'bone_cyclone', duration: 2, target: 'self' }], icon: { frame: 'rays', motif: 'wisp', accent: 'cross' } },
  },
  {
    id: 'witch_of_falling_hours', name: 'Ведьма Падающих Часов', title: 'Хранительница увядающих мгновений', role: 'damage', sprite: 'goblin_shaman', color: '#c5ad82',
    description: 'Каждый осколок времени оставляет отдельную эрозию. Ведьма уклоняется и использует звёздную силу, не меняя уже рассчитанную очередь ходов.',
    stats: { maxHp: 480, power: 26, armor: 12, initiative: 13, crit: 5, evasion: 7 }, support: ['boss_night_mantle', 'boss_stellar_oath'],
    signature: { name: 'Три украденные осени', family: 'time', cooldown: 5, target: 'enemy', projectile: 'arcane',
      description: 'Три независимых удара по цели на 1d8. Каждый успех добавляет Эрозию мгновений на 3 хода: 1d6 урона без брони в начале хода. На 1 ход получает Ускользающую секунду: уклонение +5, крит −2.',
      actions: [{ type: 'damage', dice: '1d8', hits: 3, onHitStatusId: 'chronal_erosion', onHitDuration: 3 }, { type: 'status', statusId: 'fading_second', duration: 1, target: 'self' }], icon: { frame: 'orbit', motif: 'hourglass', accent: 'leaf' } },
  },
  {
    id: 'grave_boar', name: 'Могильный Секач', title: 'Клыки под опавшей листвой', role: 'tank', sprite: 'boar', color: '#a3977e',
    description: 'Разгоняет землю и вскрывает броню, прикрываясь костями. Его тяжёлые прямые удары особенно опасны для уже повреждённых конечностей.',
    stats: { maxHp: 640, power: 33, armor: 24, initiative: 3, crit: 4, evasion: 1 }, support: ['boss_ossuary_wall', 'boss_rending_sweep'],
    signature: { name: 'Борозда до могилы', family: 'stone', cooldown: 5, target: 'enemy', projectile: 'stone',
      description: 'Накладывает Линию разлома на 2 хода (броня −8), затем наносит два независимых удара на 1d12 + треть Силы. Попадания добавляют Терновую рану на 2 хода.',
      actions: [{ type: 'status', statusId: 'fault_line', duration: 2 }, { type: 'damage', dice: '1d12', scaling: 'power', factor: 1 / 3, hits: 2, onHitStatusId: 'briar_wound', onHitDuration: 2 }], icon: { frame: 'slash', motif: 'fang', accent: 'bone' } },
  },
  {
    id: 'amber_widow', name: 'Янтарная Вдова', title: 'Плетельщица застывших слёз', role: 'damage', sprite: 'spider', color: '#d9a360',
    description: 'Янтарные нити сковывают отряд, а яд выбирает самую раненую жертву. Щиты и усиленная охота делают её опасной на любом этапе боя.',
    stats: { maxHp: 510, power: 28, armor: 15, initiative: 10, crit: 5, evasion: 6 }, support: ['boss_spore_carapace', 'boss_hunting_fervor'],
    signature: { name: 'Янтарная паутина', family: 'venom', cooldown: 5, target: 'lowestHealthEnemy', projectile: 'poison',
      description: 'Всем врагам на 2 хода Корневая хватка: уклонение и проворность −3. Самой раненой цели — два удара на 1d8 + половину Силы, попадания накладывают Яд на 3 хода.',
      actions: [{ type: 'status', statusId: 'rootbound', duration: 2, target: 'allEnemies' }, { type: 'damage', dice: '1d8', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'poisoned', onHitDuration: 3 }], icon: { frame: 'weave', motif: 'fang', accent: 'hourglass' } },
  },
  {
    id: 'ashen_pilgrim', name: 'Паломник Угасших Костров', title: 'Носитель последнего угля', role: 'healer', sprite: 'goblin_shaman', color: '#c09787',
    description: 'Дым ослабляет удары отряда, а тлеющие угли накапливаются на одной цели. Паломник укрепляется огнём и восстанавливается чужой памятью.',
    stats: { maxHp: 540, power: 27, armor: 17, initiative: 5, crit: 4, evasion: 3 }, support: ['boss_furnace_form', 'boss_grave_mending'],
    signature: { name: 'Уголь покинутого очага', family: 'fire', cooldown: 4, target: 'enemy', projectile: 'fire',
      description: 'На 2 хода накладывает Пепельное удушье на весь отряд (точность −3, Сила −2). Затем трижды атакует выбранную цель на 1d6 + треть Силы; каждый успех добавляет Горение.',
      actions: [{ type: 'status', statusId: 'ash_choke', duration: 2, target: 'allEnemies' }, { type: 'damage', dice: '1d6', scaling: 'power', factor: 1 / 3, hits: 3, onHitStatusId: 'burning', onHitDuration: null }], icon: { frame: 'seal', motif: 'flame', accent: 'wisp' } },
  },
]);
