import { createBossCatalog } from './boss-catalog-builders';

export const summerBossCatalog = createBossCatalog('summer', [
  {
    id: 'brass_sun', name: 'Медное Солнце', title: 'Живое горнило полдня', role: 'tank', sprite: 'elite_warden', color: '#e6ac57',
    description: 'Прожигает весь отряд волнами огня. Под усилением горнила его многократные попадания особенно опасны; дождь шлака разрушает броню.',
    stats: { maxHp: 520, power: 25, armor: 19, initiative: 4, crit: 4, evasion: 2 }, support: ['boss_furnace_form', 'boss_slag_rain'],
    signature: { name: 'Полуденный апокалипсис', family: 'fire', cooldown: 5, target: 'allEnemies', projectile: 'fire',
      description: 'Два независимых удара по каждому врагу, каждый на 1d6 + четверть Силы. Каждое попадание добавляет заряд Горения без срока.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', factor: .25, hits: 2, onHitStatusId: 'burning', onHitDuration: null }], icon: { frame: 'rays', motif: 'flame', accent: 'star' } },
  },
  {
    id: 'dune_queen', name: 'Царица Сухих Дюн', title: 'Песок, выпивший реку', role: 'damage', sprite: 'spider', color: '#d9c183',
    description: 'Слепит песком и заставляет самых раненых нести каменные занозы. Уклонение и броня ослабляют ответный натиск.',
    stats: { maxHp: 405, power: 24, armor: 14, initiative: 9, crit: 5, evasion: 6 }, support: ['boss_night_mantle', 'boss_rending_sweep'],
    signature: { name: 'Глотка бархана', family: 'stone', cooldown: 4, target: 'lowestHealthEnemy', projectile: 'stone',
      description: 'Накладывает Тьму в глазах на 2 хода (точность −4), затем атакует самую раненую цель на 3d6 + половину Силы. Попадание оставляет Каменные занозы на 2 хода.',
      actions: [{ type: 'status', statusId: 'blackout', duration: 2 }, { type: 'damage', dice: '3d6', scaling: 'power', factor: .5, onHitStatusId: 'splintered_stone', onHitDuration: 2 }], icon: { frame: 'burst', motif: 'rock', accent: 'eye' } },
  },
  {
    id: 'scarlet_admiral', name: 'Алый Адмирал', title: 'Корсар кровавого зноя', role: 'damage', sprite: 'goblin_scout', color: '#d46e69',
    description: 'Двойной абордажный выпад обескровливает цель. Адмирал усиливает прицел и восстанавливается за счёт крови.',
    stats: { maxHp: 420, power: 25, armor: 15, initiative: 8, crit: 6, evasion: 5 }, support: ['boss_predators_gaze', 'boss_blood_feast'],
    signature: { name: 'Абордаж красного прилива', family: 'blood', cooldown: 4, target: 'enemy',
      description: 'Два удара по выбранной цели, каждый на 1d8 + половину Силы. Попадания добавляют Кровотечение на 3 хода. Адмирал получает Жажду хищника на 1 ход.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'bleeding', onHitDuration: 3 }, { type: 'status', statusId: 'predators_thirst', duration: 1, target: 'self' }], icon: { frame: 'slash', motif: 'blade', accent: 'drop' } },
  },
  {
    id: 'storm_matriarch', name: 'Матриарх Летней Бури', title: 'Наследница громовых башен', role: 'damage', sprite: 'goblin_shaman', color: '#ada5e1',
    description: 'Разряды оставляют статический заряд на всём отряде. Клятва звёзд подготавливает следующий залп, а ледяной панцирь защищает заклинательницу.',
    stats: { maxHp: 400, power: 25, armor: 11, initiative: 11, crit: 5, evasion: 6 }, support: ['boss_stellar_oath', 'boss_glacial_shell'],
    signature: { name: 'Грозовая корона', family: 'storm', cooldown: 4, target: 'allEnemies', projectile: 'lightning',
      description: 'Каждому врагу — 2d6 + половина Силы. Попадание добавляет Статический заряд на 3 хода: 1d4 урона в конце хода, крит −1.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', factor: .5, onHitStatusId: 'static_charge', onHitDuration: 3 }], icon: { frame: 'arrows', motif: 'bolt', accent: 'star' } },
  },
  {
    id: 'cinder_butcher', name: 'Мясник Пепельного Рынка', title: 'Собиратель обугленных костей', role: 'tank', sprite: 'boar', color: '#c07f59',
    description: 'Сначала раскаляет броню жертвы, потом наносит тяжёлый удар. Умеет кормить свой огонь кровью.',
    stats: { maxHp: 485, power: 29, armor: 19, initiative: 3, crit: 4, evasion: 2 }, support: ['boss_furnace_form', 'boss_blood_feast'],
    signature: { name: 'Разделка на раскалённом железе', family: 'fire', cooldown: 4, target: 'enemy', projectile: 'fire',
      description: 'Обугливает броню выбранной цели на 2 хода (−6), затем атакует на 2d10 + Силу. Попадание добавляет Тление на 2 хода.',
      actions: [{ type: 'status', statusId: 'charred_armor', duration: 2 }, { type: 'damage', dice: '2d10', scaling: 'power', onHitStatusId: 'smoldering', onHitDuration: 2 }], icon: { frame: 'slash', motif: 'blade', accent: 'flame' } },
  },
  {
    id: 'salt_prophet', name: 'Пророк Белой Соли', title: 'Святой мёртвого озера', role: 'healer', sprite: 'goblin_shaman', color: '#e4d4b6',
    description: 'Соляной приговор ослабляет попадания всего отряда. Пророк укрывается костяной крепостью и исцеляется памятью погибших паломников.',
    stats: { maxHp: 415, power: 24, armor: 16, initiative: 5, crit: 3, evasion: 3 }, support: ['boss_ossuary_wall', 'boss_grave_mending'],
    signature: { name: 'Проповедь иссушения', family: 'holy', cooldown: 5, target: 'allEnemies', projectile: 'holy',
      description: 'На 2 хода всем врагам Светлый приговор: точность −3, крит −2. Затем каждому — удар на 1d12 + треть Силы. Пророк получает Божественную защиту на 1 ход.',
      actions: [{ type: 'status', statusId: 'radiant_censure', duration: 2 }, { type: 'damage', dice: '1d12', scaling: 'power', factor: 1 / 3 }, { type: 'status', statusId: 'divine_protection', duration: 1, target: 'self' }], icon: { frame: 'seal', motif: 'cross', accent: 'rock' } },
  },
  {
    id: 'golden_hydra', name: 'Златозубая Гидра', title: 'Четыре голода жарких болот', role: 'damage', sprite: 'slime', color: '#cab14e',
    description: 'Четыре укуса отравляют одну цель. На коротком промежутке между охотой и защитой уязвима для сосредоточенных атак.',
    stats: { maxHp: 460, power: 24, armor: 15, initiative: 6, crit: 3, evasion: 3 }, support: ['boss_hunting_fervor', 'boss_spore_carapace'],
    signature: { name: 'Четыре золотые пасти', family: 'venom', cooldown: 5, target: 'enemy', projectile: 'poison',
      description: 'Четыре независимых укуса, каждый на 1d6 + четверть Силы. Попадания накладывают Ядовитую лихорадку на 2 хода: Сила −4, бонус инициативы −2 не переставляет текущую очередь.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', factor: .25, hits: 4, onHitStatusId: 'venom_fever', onHitDuration: 2 }], icon: { frame: 'arrows', motif: 'fang', accent: 'star' } },
  },
  {
    id: 'noon_executioner', name: 'Полуденный Палач', title: 'Тень без хозяина', role: 'damage', sprite: 'goblin_scout', color: '#bd7a8c',
    description: 'Смертельно точный удар добивает самого раненого противника. Его защитные приёмы основаны на уклонении и повторных атаках.',
    stats: { maxHp: 385, power: 27, armor: 12, initiative: 10, crit: 6, evasion: 7 }, support: ['boss_night_mantle', 'boss_rending_sweep'],
    signature: { name: 'Тень на плахе', family: 'shadow', cooldown: 6, target: 'lowestHealthEnemy', projectile: 'shadow',
      description: 'Получает Смертельную точность на 1 ход, затем атакует самого раненого врага на 2d8 + половину Силы. Попадание гарантированно критическое, но от него можно уклониться.',
      actions: [{ type: 'status', statusId: 'sure_strike', duration: 1, target: 'self' }, { type: 'damage', dice: '2d8', scaling: 'power', factor: .5 }], icon: { frame: 'slash', motif: 'blade', accent: 'eye' } },
  },
  {
    id: 'ember_phoenix', name: 'Феникс Неугасимой Золы', title: 'Пепел, который помнит жизнь', role: 'healer', sprite: 'goblin_archer', color: '#ee9d75',
    description: 'Огненный ливень сменяется коротким восстановлением. Феникс не воскресает после гибели: запас лечения нужно преодолеть во время боя.',
    stats: { maxHp: 390, power: 23, armor: 10, initiative: 10, crit: 5, evasion: 6 }, support: ['boss_furnace_form', 'boss_green_renewal'],
    signature: { name: 'Крылья негаснущего пепла', family: 'fire', cooldown: 5, target: 'allEnemies', projectile: 'fire',
      description: 'Удар по каждому врагу на 1d10 + половину Силы, попадание добавляет Горение. Феникс получает Искры жизни на 2 хода: 1d8 + Силу лечения в начале хода.',
      actions: [{ type: 'damage', dice: '1d10', scaling: 'power', factor: .5, onHitStatusId: 'burning', onHitDuration: null }, { type: 'status', statusId: 'embers_of_life', duration: 2, target: 'self' }], icon: { frame: 'weave', motif: 'feather', accent: 'flame' } },
  },
  {
    id: 'copper_huntsman', name: 'Медный Ловчий', title: 'Гонитель последней тени', role: 'damage', sprite: 'goblin_archer', color: '#c09868',
    description: 'Зазубренные стрелы затрудняют бегство и оставляют кровь. Ловчий усиливает прицел, затем разрывает одну ослабленную цель.',
    stats: { maxHp: 405, power: 26, armor: 14, initiative: 9, crit: 5, evasion: 5, accuracy: 7 }, support: ['boss_predators_gaze', 'boss_rending_sweep'],
    signature: { name: 'Петля на солнечном луче', family: 'metal', cooldown: 4, target: 'enemy', projectile: 'arrow',
      description: 'Два независимых удара на 1d10 + треть Силы. Каждый успех накладывает Зазубренные оковы на 3 хода: проворность −3, 1d4 урона без брони в конце хода.',
      actions: [{ type: 'damage', dice: '1d10', scaling: 'power', factor: 1 / 3, hits: 2, onHitStatusId: 'barbed_shackles', onHitDuration: 3 }], icon: { frame: 'arrows', motif: 'blade', accent: 'shield' } },
  },
  {
    id: 'mirage_sultan', name: 'Султан Пустых Миражей', title: 'Последний дворец над песком', role: 'tank', sprite: 'goblin_shaman', color: '#bd9be1',
    description: 'Бьёт случайную цель несколькими лучами, подавляющими Силу и точность. Прячется за щитами и ночным покровом.',
    stats: { maxHp: 440, power: 23, armor: 13, initiative: 7, crit: 4, evasion: 6 }, support: ['boss_glacial_shell', 'boss_night_mantle'],
    signature: { name: 'Три ложных солнца', family: 'arcane', cooldown: 4, target: 'randomEnemy', projectile: 'arcane',
      description: 'Три луча по одной случайной цели, каждый на 1d8 + четверть Силы. Попадание накладывает Разлад чар на 2 хода: Сила −5, точность −2.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', factor: .25, hits: 3, onHitStatusId: 'arcane_disruption', onHitDuration: 2 }], icon: { frame: 'orbit', motif: 'rune', accent: 'star' } },
  },
  {
    id: 'locust_emperor', name: 'Император Саранчи', title: 'Чёрное облако над нивой', role: 'damage', sprite: 'rat', color: '#abbe64',
    description: 'Рой ослабляет Силу и прицел всего отряда, затем питается кровью. Опаснее всего затяжная схватка под его пеленой.',
    stats: { maxHp: 410, power: 24, armor: 11, initiative: 10, crit: 4, evasion: 7 }, support: ['boss_hunting_fervor', 'boss_blood_feast'],
    signature: { name: 'Пожирание полей', family: 'venom', cooldown: 5, target: 'allEnemies', projectile: 'poison',
      description: 'По всем врагам — 1d10 + половина Силы. Попадание накладывает Пепельное удушье на 2 хода: точность −3, Сила −2. Император лечит себя на 2d8.',
      actions: [{ type: 'damage', dice: '1d10', scaling: 'power', factor: .5, onHitStatusId: 'ash_choke', onHitDuration: 2 }, { type: 'heal', dice: '2d8', target: 'self' }], icon: { frame: 'burst', motif: 'fang', accent: 'leaf' } },
  },
  {
    id: 'obsidian_ram', name: 'Обсидиановый Таран', title: 'Кулак спящего вулкана', role: 'tank', sprite: 'boar', color: '#a67b79',
    description: 'Раскалывает броню и прикрывается щитом после тарана. Медленное тяжёлое чудовище, которое наказывает за слабое лечение конечностей.',
    stats: { maxHp: 535, power: 29, armor: 23, initiative: 2, crit: 3, evasion: 1, resilience: 8 }, support: ['boss_slag_rain', 'boss_furnace_form'],
    signature: { name: 'Чёрный разлом', family: 'stone', cooldown: 5, target: 'enemy', projectile: 'stone',
      description: 'Удар на 3d8 + половину Силы. Попадание создаёт Линию разлома на 2 хода: броня −8. После тарана получает щит на 2d8 на 2 хода.',
      actions: [{ type: 'damage', dice: '3d8', scaling: 'power', factor: .5, onHitStatusId: 'fault_line', onHitDuration: 2 }, { type: 'shield', dice: '2d8', duration: 2, target: 'self' }], icon: { frame: 'burst', motif: 'rock', accent: 'flame' } },
  },
]);
