import type { UnitDefinition } from '@shards/shared';
import { MOVEMENT_SPEED_PROFILES } from './movement';
import { STARTER_ANATOMY } from './anatomy';

/** Nine starting heroes; every ability uses the shared deterministic combat rules. */
export const characters: UnitDefinition[] = [
  {
    schemaVersion: 1, id: 'guardian', name: 'Страж', title: 'Щит отряда',
    description: 'Принимает удары на себя и защищает весь отряд, включая себя. Его присутствие снижает входящий урон на 25%.',
    role: 'tank', color: '#e7b96b', sprite: 'guardian',
    movementSpeed: MOVEMENT_SPEED_PROFILES.guardian,
    anatomy: STARTER_ANATOMY.guardian,
    stats: { maxHp: 160, power: 8, armor: 18, initiative: 9, crit: 0.06, evasion: 0.03, healing: 0 },
    basicAttack: { type: 'damage', dice: '1d6', scaling: 'power', factor: 1.1 },
    skillIds: ['tank_taunt', 'guardian_bastion'], effectIds: [],
    modifiers: { partyDamageReduction: 0.25 }, tags: ['ARMOR', 'TAUNT', 'ALLY_PROTECTION', 'SHIELD'],
    passive: { name: 'Стойкая защита', description: 'Снижает входящий урон всего отряда, включая самого Стража, на 25%, пока герой жив. Бастион усиливает защиту до 75%.' },
  },
  {
    schemaVersion: 1, id: 'priest', name: 'Жрица', title: 'Хранительница света',
    description: 'Лечит самых раненых союзников, а молитвой восстанавливает весь отряд. Каждое исцеление ненадолго усиливает урон получателя.',
    role: 'healer', color: '#9ce0d1', sprite: 'priest',
    movementSpeed: MOVEMENT_SPEED_PROFILES.priest,
    anatomy: STARTER_ANATOMY.priest,
    stats: { maxHp: 105, power: 5, armor: 7, initiative: 11, crit: 0.08, evasion: 0.07, healing: 11 },
    basicAttack: { type: 'damage', dice: '1d6', scaling: 'power', factor: 1 },
    skillIds: ['healer_mend', 'priest_prayer'], effectIds: ['priest_benediction'],
    modifiers: {}, tags: ['HEAL', 'BUFF', 'HOLY'],
    passive: { name: 'Благословение света', description: 'Исцеление Жрицы усиливает урон получателя, в том числе самой Жрицы, на 20% на 2 его хода.' },
  },
  {
    schemaVersion: 1, id: 'mage', name: 'Маг', title: 'Искра пепла',
    description: 'Поражает врага мощным заклинанием и накладывает горение. Критические попадания тоже поджигают цель.',
    role: 'damage', color: '#b8a3f3', sprite: 'mage',
    movementSpeed: MOVEMENT_SPEED_PROFILES.mage,
    anatomy: STARTER_ANATOMY.mage,
    stats: { maxHp: 92, power: 14, armor: 5, initiative: 13, crit: 0.16, evasion: 0.09, healing: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 0.65 },
    skillIds: ['damage_burst', 'mage_ignite'], effectIds: ['mage_ember_spark'],
    modifiers: {}, tags: ['FIRE', 'BURN', 'DOT', 'MAGIC', 'CRITICAL'],
    passive: { name: 'Тлеющая искра', description: 'Критический удар Мага накладывает горение на 2 хода. Повторное срабатывание возможно через 1 ход Мага.' },
  },
  {
    schemaVersion: 1, id: 'vampire', name: 'Вампир', title: 'Ненасытный защитник',
    description: 'Отвлекает врагов и восстанавливает силы каждым ударом. Жажда крови ненадолго усиливает прямой урон.',
    role: 'tank', color: '#c78091', sprite: 'vampire', movementSpeed: MOVEMENT_SPEED_PROFILES.vampire,
    anatomy: STARTER_ANATOMY.vampire,
    stats: { maxHp: 150, power: 11, armor: 12, initiative: 12, crit: 0.1, evasion: 0.06, healing: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 0.9 },
    skillIds: ['tank_taunt', 'vampire_bloodlust'], effectIds: [],
    modifiers: { vampirism: 0.3 }, tags: ['VAMPIRISM', 'PHYSICAL', 'BLEED', 'HEAL', 'LOW_HEALTH'],
    passive: { name: 'Вампиризм', description: 'Восстанавливает 30% фактически нанесённого прямого урона здоровью врага. Поглощённый щитом урон не лечит. Утраченные части тела не отрастают.' },
  },
  {
    schemaVersion: 1, id: 'paladin', name: 'Паладин', title: 'Свет клятвы',
    description: 'Защищает отряд и лечит себя. Часть каждого полученного исцеления передаёт всем живым героям, включая себя.',
    role: 'tank', color: '#e7dc9d', sprite: 'paladin', movementSpeed: MOVEMENT_SPEED_PROFILES.paladin,
    anatomy: STARTER_ANATOMY.paladin,
    stats: { maxHp: 160, power: 9, armor: 16, initiative: 8, crit: 0.08, evasion: 0.04, healing: 10 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 1 },
    skillIds: ['tank_taunt', 'paladin_radiance'], effectIds: [],
    modifiers: { healingShare: 0.25 }, tags: ['HEAL', 'OVERHEAL', 'HOLY', 'BLOCK'],
    passive: { name: 'Общий свет', description: '25% фактически полученного лечения один раз восстанавливает здоровье каждого живого героя, включая Паладина. Это дополнительное лечение не запускает новую передачу.' },
  },
  {
    schemaVersion: 1, id: 'druid', name: 'Друид', title: 'Голос рощи',
    description: 'Лечит раненых и дарует всему отряду постепенную регенерацию. Удачный бросок сохраняет заряд исцеления.',
    role: 'healer', color: '#abd083', sprite: 'druid', movementSpeed: MOVEMENT_SPEED_PROFILES.druid,
    anatomy: STARTER_ANATOMY.druid,
    stats: { maxHp: 110, power: 7, armor: 8, initiative: 12, crit: 0.08, evasion: 0.08, healing: 10 },
    basicAttack: { type: 'damage', dice: '1d6', scaling: 'power', factor: 1 },
    skillIds: ['healer_mend', 'druid_regrowth'], effectIds: [],
    modifiers: { preserveHotChance: 0.25 }, tags: ['HOT', 'NATURE', 'REGENERATION', 'POISON'],
    passive: { name: 'Неувядающий рост', description: 'После каждого тика наложенной Друидом регенерации бросает d20: на 1–5 заряд не расходуется. Работает, пока Друид жив.' },
  },
  {
    schemaVersion: 1, id: 'necromancer', name: 'Некромант', title: 'Хранитель последней грани',
    description: 'Восстанавливает живых союзников и укрывает отряд временным щитом. Иногда щит поглощает удар без расхода силы.',
    role: 'healer', color: '#afa4cf', sprite: 'necromancer', movementSpeed: MOVEMENT_SPEED_PROFILES.necromancer,
    anatomy: STARTER_ANATOMY.necromancer,
    stats: { maxHp: 100, power: 9, armor: 6, initiative: 10, crit: 0.1, evasion: 0.05, healing: 10 },
    basicAttack: { type: 'damage', dice: '1d6', scaling: 'power', factor: 1 },
    skillIds: ['healer_mend', 'necromancer_ward'], effectIds: [],
    modifiers: { preserveShieldChance: 0.25 }, tags: ['SHIELD', 'ABSORB', 'DARK', 'DEATH', 'SUMMON'],
    passive: { name: 'Непрерывный покров', description: 'При поглощении урона щитом Некроманта бросает d20: на 1–5 ёмкость щита не расходуется. Время действия всё равно уменьшается. Работает, пока Некромант жив.' },
  },
  {
    schemaVersion: 1, id: 'rogue', name: 'Разбойник', title: 'Тень клинка',
    description: 'Быстрый боец с двумя кинжалами. Избегает части ударов и на короткое время делает каждое попадание критическим.',
    role: 'damage', color: '#c3b49b', sprite: 'rogue', movementSpeed: MOVEMENT_SPEED_PROFILES.rogue,
    anatomy: STARTER_ANATOMY.rogue,
    stats: { maxHp: 100, power: 12, armor: 7, initiative: 16, crit: 0.15, evasion: 0.05, healing: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 0.9 },
    skillIds: ['damage_burst', 'rogue_precision'], effectIds: [],
    modifiers: { evasionBonus: 0.15 }, tags: ['CRITICAL', 'DODGE', 'BLEED', 'EXECUTE'],
    passive: { name: 'Ускользание', description: 'Добавляет 15 процентных пунктов уклонения. Попадание врага проверяется броском d20.' },
  },
  {
    schemaVersion: 1, id: 'ranger', name: 'Следопыт', title: 'Верная тетива',
    description: 'После атаки может выпустить дополнительную стрелу. Шквал стрел резко увеличивает вероятность повторного выстрела.',
    role: 'damage', color: '#b0c687', sprite: 'ranger', movementSpeed: MOVEMENT_SPEED_PROFILES.ranger,
    anatomy: STARTER_ANATOMY.ranger,
    stats: { maxHp: 105, power: 12, armor: 8, initiative: 14, crit: 0.12, evasion: 0.1, healing: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 0.85 },
    skillIds: ['damage_burst', 'ranger_volley'], effectIds: [],
    modifiers: { repeatChance: 0.25 }, tags: ['REPEAT', 'PROJECTILE', 'MULTIHIT'],
    passive: { name: 'Вторая стрела', description: 'После действия с уроном имеет 25% шанс дополнительной базовой атаки. Повтор не вызывает цепочку. Рейтинг выше 100% усиливает прямой урон на величину превышения.' },
  },
];
