import type { UnitDefinition } from '@shards/shared';
import { MOVEMENT_SPEED_PROFILES } from './movement';
import { STARTER_ANATOMY } from './anatomy';

/** Nine starting heroes; every ability uses the shared deterministic combat rules. */
export const characters: UnitDefinition[] = [
  {
    schemaVersion: 1, id: 'guardian', name: 'Страж', title: 'Щит отряда',
    description: 'Вызывает врагов на себя и становится несокрушимым бастионом. Перед каждым ударом по отряду бросает 1d4 и уменьшает входящий урон на результат.',
    role: 'tank', color: '#e7b96b', sprite: 'guardian',
    movementSpeed: MOVEMENT_SPEED_PROFILES.guardian,
    anatomy: STARTER_ANATOMY.guardian,
    stats: { maxHp: 160, power: 8, armor: 0, initiative: 2, crit: 1, evasion: 1, agility: 1 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d6', scaling: 'power', factor: 1.1 },
    skillIds: ['tank_taunt', 'guardian_bastion'], effectIds: [],
    modifiers: { partyGuardDice: '1d4' }, tags: ['ARMOR', 'TAUNT', 'ALLY_PROTECTION', 'SHIELD'],
    passive: { name: 'Стойкая защита', description: 'Перед каждым ударом по живому участнику своего отряда, включая себя, Страж бросает 1d4. Входящий урон уменьшается на результат, вплоть до нуля.' },
  },
  {
    schemaVersion: 1, id: 'priest', name: 'Жрица', title: 'Хранительница света',
    description: 'Лечит самых раненых союзников, а молитвой восстанавливает весь отряд. Каждое исцеление ненадолго усиливает урон получателя.',
    role: 'healer', color: '#9ce0d1', sprite: 'priest',
    movementSpeed: MOVEMENT_SPEED_PROFILES.priest,
    anatomy: STARTER_ANATOMY.priest,
    stats: { maxHp: 105, power: 11, armor: 0, initiative: 3, crit: 1, evasion: 1, agility: 2 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d6', scaling: 'power', factor: 1 },
    skillIds: ['healer_mend', 'priest_prayer'], effectIds: ['priest_benediction'],
    modifiers: {}, tags: ['HEAL', 'BUFF', 'HOLY'],
    passive: { name: 'Благословение света', description: 'Каждое исцеление Жрицы накладывает отдельное Благословение: +1d4 к урону каждого удара на 2 хода получателя. У каждого заряда своя длительность и свой бросок.' },
  },
  {
    schemaVersion: 1, id: 'mage', name: 'Маг', title: 'Искра пепла',
    description: 'Поражает врага мощным заклинанием и накладывает горение. Критические попадания тоже поджигают цель.',
    role: 'damage', color: '#b8a3f3', sprite: 'mage',
    movementSpeed: MOVEMENT_SPEED_PROFILES.mage,
    anatomy: STARTER_ANATOMY.mage,
    stats: { maxHp: 92, power: 14, armor: 0, initiative: 4, crit: 3, evasion: 2, agility: 3 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 0.65 },
    skillIds: ['damage_burst', 'mage_ignite'], effectIds: ['mage_ember_spark'],
    modifiers: {}, tags: ['FIRE', 'BURN', 'DOT', 'MAGIC', 'CRITICAL'],
    passive: { name: 'Тлеющая искра', description: 'Каждое критическое попадание добавляет 1 заряд Горения. В конце хода цель получает урон по числу зарядов, после чего теряет 1 заряд.' },
  },
  {
    schemaVersion: 1, id: 'vampire', name: 'Вампир', title: 'Ненасытный защитник',
    description: 'Отвлекает врагов и восстанавливает силы каждым ударом. Жажда крови ненадолго усиливает прямой урон.',
    role: 'tank', color: '#c78091', sprite: 'vampire', movementSpeed: MOVEMENT_SPEED_PROFILES.vampire,
    anatomy: STARTER_ANATOMY.vampire,
    stats: { maxHp: 150, power: 11, armor: 0, initiative: 3, crit: 2, evasion: 1, agility: 3 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 0.9 },
    skillIds: ['tank_taunt', 'vampire_bloodlust'], effectIds: [],
    modifiers: { vampirismDice: '1d6' }, tags: ['VAMPIRISM', 'PHYSICAL', 'BLEED', 'HEAL', 'LOW_HEALTH'],
    passive: { name: 'Вампиризм', description: 'После прямого урона здоровью врага восстанавливает 1d6 HP, не больше нанесённого урона. Поглощённый щитом урон не лечит. Утраченные части тела не отрастают.' },
  },
  {
    schemaVersion: 1, id: 'paladin', name: 'Паладин', title: 'Свет клятвы',
    description: 'Защищает отряд и лечит себя. Получив исцеление, бросает 1d4 и восстанавливает столько здоровья каждому союзнику.',
    role: 'tank', color: '#e7dc9d', sprite: 'paladin', movementSpeed: MOVEMENT_SPEED_PROFILES.paladin,
    anatomy: STARTER_ANATOMY.paladin,
    stats: { maxHp: 160, power: 16, armor: 0, initiative: 1, crit: 1, evasion: 1, agility: 1 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 1 },
    skillIds: ['tank_taunt', 'paladin_radiance'], effectIds: [],
    modifiers: { healingShareDice: '1d4' }, tags: ['HEAL', 'OVERHEAL', 'HOLY', 'BLOCK'],
    passive: { name: 'Общий свет', description: 'Получив лечение, бросает 1d4 и восстанавливает столько HP каждому живому участнику своего отряда, включая себя. Это лечение не запускает новую передачу.' },
  },
  {
    schemaVersion: 1, id: 'druid', name: 'Друид', title: 'Голос рощи',
    description: 'Лечит выбранного союзника и дарует регенерацию в начале его хода. Четвёрка на 1d4 продлевает сработавшую ауру на один ход.',
    role: 'healer', color: '#abd083', sprite: 'druid', movementSpeed: MOVEMENT_SPEED_PROFILES.druid,
    anatomy: STARTER_ANATOMY.druid,
    stats: { maxHp: 110, power: 10, armor: 0, initiative: 3, crit: 1, evasion: 2, agility: 3 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d6', scaling: 'power', factor: 1 },
    skillIds: ['healer_mend', 'druid_regrowth'], effectIds: [],
    modifiers: { preserveHot: { dice: '1d4', atLeast: 4 } }, tags: ['HOT', 'NATURE', 'REGENERATION', 'POISON'],
    passive: { name: 'Неувядающий рост', description: 'После каждого срабатывания Живой рощи бросает 1d4: на 4 продлевает эту ауру на 1 ход. В конце хода получателя её длительность уменьшается как обычно. Работает, пока Друид участвует в бою.' },
  },
  {
    schemaVersion: 1, id: 'necromancer', name: 'Некромант', title: 'Хранитель последней грани',
    description: 'Восстанавливает живых союзников и укрывает выбранного героя костяным щитом. Четвёрка на 1d4 позволяет поглотить удар без расхода ёмкости.',
    role: 'healer', color: '#afa4cf', sprite: 'necromancer', movementSpeed: MOVEMENT_SPEED_PROFILES.necromancer,
    anatomy: STARTER_ANATOMY.necromancer,
    stats: { maxHp: 100, power: 10, armor: 0, initiative: 2, crit: 2, evasion: 1, agility: 2 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d6', scaling: 'power', factor: 1 },
    skillIds: ['healer_mend', 'necromancer_ward'], effectIds: [],
    modifiers: { preserveShield: { dice: '1d4', atLeast: 4 } }, tags: ['SHIELD', 'ABSORB', 'DARK', 'DEATH', 'SUMMON'],
    passive: { name: 'Непрерывный покров', description: 'Когда костяной щит должен поглотить урон, Некромант бросает 1d4: на 4 щит полностью поглощает оставшийся удар без расхода ёмкости. Время действия уменьшается в конце хода получателя. Работает, пока Некромант участвует в бою.' },
  },
  {
    schemaVersion: 1, id: 'rogue', name: 'Разбойник', title: 'Тень клинка',
    description: 'Быстрый боец с двумя кинжалами. Избегает части ударов и на короткое время делает каждое попадание критическим.',
    role: 'damage', color: '#c3b49b', sprite: 'rogue', movementSpeed: MOVEMENT_SPEED_PROFILES.rogue,
    anatomy: STARTER_ANATOMY.rogue,
    stats: { maxHp: 100, power: 12, armor: 0, initiative: 6, crit: 3, evasion: 1, agility: 6 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 0.9 },
    skillIds: ['damage_burst', 'rogue_precision'], effectIds: [],
    modifiers: { evasionBonus: 5 }, tags: ['CRITICAL', 'DODGE', 'BLEED', 'EXECUTE'],
    passive: { name: 'Ускользание', description: '+5 к атрибуту уклонения. Чтобы попасть, враг должен выбросить на 1d20 больше итогового уклонения Разбойника.' },
  },
  {
    schemaVersion: 1, id: 'ranger', name: 'Следопыт', title: 'Верная тетива',
    description: 'После атаки бросает 1d4: на 4 выпускает ещё одну стрелу. Шквал стрел заменяет этот бросок на 1d6: повтор срабатывает на 4–6.',
    role: 'damage', color: '#b0c687', sprite: 'ranger', movementSpeed: MOVEMENT_SPEED_PROFILES.ranger,
    anatomy: STARTER_ANATOMY.ranger,
    stats: { maxHp: 105, power: 12, armor: 0, initiative: 5, crit: 2, evasion: 2, agility: 5 , accuracy: 0, resilience: 0, luck: 0 },
    basicAttack: { type: 'damage', dice: '1d8', scaling: 'power', factor: 0.85 },
    skillIds: ['damage_burst', 'ranger_volley'], effectIds: [],
    modifiers: { repeatAttack: { dice: '1d4', atLeast: 4 } }, tags: ['REPEAT', 'PROJECTILE', 'MULTIHIT'],
    passive: { name: 'Вторая стрела', description: 'После действия с уроном бросает 1d4: на 4 выполняет дополнительную базовую атаку по выбранной живой цели. Это часть того же действия; повтор не вызывает цепочку.' },
  },
];
