import type { AuraVisualDefinition } from '@shards/shared';

export interface EquipmentThemeName { id: string; name: string; genitive: string }
export interface EquipmentThemeCollection {
  id: string;
  name: string;
  family: AuraVisualDefinition['family'];
  material: 'cloth' | 'leather' | 'mail' | 'plate' | 'bone';
  silhouette: 'guardian' | 'priest' | 'mage' | 'vampire' | 'paladin' | 'druid' | 'necromancer' | 'rogue' | 'ranger';
  hue: number;
  themes: EquipmentThemeName[];
}

const theme = (id: string, name: string, genitive: string): EquipmentThemeName => ({ id, name, genitive });

/** Authored identities and grammatical forms; rarity and mechanical profiles live in the equipment catalog. */
export const EQUIPMENT_THEME_COLLECTIONS: EquipmentThemeCollection[] = [
  {
    id: 'iron-orders', name: 'Железные ордены', family: 'metal', material: 'plate', silhouette: 'guardian', hue: 28,
    themes: [
      theme('iron-oath', 'Железный обет', 'железного обета'),
      theme('silent-garrison', 'Безмолвный караул', 'безмолвного караула'),
      theme('broken-seal', 'Треснувшая печать', 'треснувшей печати'),
      theme('ash-legion', 'Пепельный легион', 'пепельного легиона'),
      theme('last-bastion', 'Последняя бастея', 'последней бастеи'),
      theme('locked-citadel', 'Запертая цитадель', 'запертой цитадели'),
      theme('kingless-throne', 'Престол без короля', 'престола без короля'),
      theme('black-rivet', 'Чёрная заклёпка', 'чёрной заклёпки'),
      theme('bronze-mandate', 'Бронзовый наказ', 'бронзового наказа'),
      theme('cold-charter', 'Холодная хартия', 'холодной хартии'),
      theme('scarred-banner', 'Израненное знамя', 'израненного знамени'),
      theme('bonegate-watch', 'Стража Костяных врат', 'стражи Костяных врат'),
      theme('unbent-knee', 'Несклонённое колено', 'несклонённого колена'),
      theme('blind-herald', 'Слепой герольд', 'слепого герольда'),
      theme('hammers-law', 'Закон молота', 'закона молота'),
      theme('chain-brotherhood', 'Братство цепи', 'братства цепи'),
      theme('empty-armory', 'Опустевший арсенал', 'опустевшего арсенала'),
      theme('rusted-regent', 'Ржавый регент', 'ржавого регента'),
      theme('buried-standard', 'Погребённый штандарт', 'погребённого штандарта'),
      theme('copper-vespers', 'Медная вечерня', 'медной вечерни'),
      theme('gateward-debt', 'Долг привратника', 'долга привратника'),
      theme('sable-keep', 'Соболиная твердыня', 'соболиной твердыни'),
      theme('silver-hostage', 'Серебряный заложник', 'серебряного заложника'),
      theme('battle-crown', 'Венец побоища', 'венца побоища'),
      theme('unending-vigil', 'Неусыпная стража', 'неусыпной стражи'),
    ],
  },
  {
    id: 'candle-pilgrims', name: 'Паломники свечного пути', family: 'holy', material: 'cloth', silhouette: 'priest', hue: 42,
    themes: [
      theme('candle-road', 'Дорога свечей', 'дороги свечей'),
      theme('dusty-litany', 'Пыльная литания', 'пыльной литании'),
      theme('barefoot-promise', 'Босоногий обет', 'босоногого обета'),
      theme('salt-prayer', 'Солёная молитва', 'солёной молитвы'),
      theme('widows-lantern', 'Фонарь вдовы', 'фонаря вдовы'),
      theme('hollow-bell', 'Полый колокол', 'полого колокола'),
      theme('wax-tears', 'Восковые слёзы', 'восковых слёз'),
      theme('bread-for-the-lost', 'Хлеб заблудших', 'хлеба заблудших'),
      theme('mercy-at-the-ford', 'Милость у переправы', 'милости у переправы'),
      theme('shroud-of-hope', 'Саван надежды', 'савана надежды'),
      theme('unspoken-confession', 'Невысказанная исповедь', 'невысказанной исповеди'),
      theme('rosemary-rosary', 'Розарий розмарина', 'розария розмарина'),
      theme('shelter-of-strangers', 'Приют незнакомцев', 'приюта незнакомцев'),
      theme('penitents-mile', 'Верста покаяния', 'версты покаяния'),
      theme('bellkeepers-alms', 'Милостыня звонаря', 'милостыни звонаря'),
      theme('mended-halo', 'Заштопанный нимб', 'заштопанного нимба'),
      theme('dawn-at-the-well', 'Рассвет у колодца', 'рассвета у колодца'),
      theme('ashes-of-incense', 'Прах ладана', 'праха ладана'),
      theme('travellers-requiem', 'Реквием странников', 'реквиема странников'),
      theme('open-palm', 'Раскрытая ладонь', 'раскрытой ладони'),
      theme('starlit-chapel', 'Часовня под звёздами', 'часовни под звёздами'),
      theme('last-crust', 'Последняя краюха', 'последней краюхи'),
      theme('linen-covenant', 'Льняной завет', 'льняного завета'),
      theme('roadside-miracle', 'Придорожное чудо', 'придорожного чуда'),
      theme('homecoming-hymn', 'Гимн возвращения', 'гимна возвращения'),
    ],
  },
  {
    id: 'mire-covenants', name: 'Заветы болот', family: 'nature', material: 'leather', silhouette: 'druid', hue: 93,
    themes: [
      theme('reed-court', 'Камышовый двор', 'камышового двора'),
      theme('peat-crown', 'Торфяная корона', 'торфяной короны'),
      theme('drowned-willow', 'Утопленная ива', 'утопленной ивы'),
      theme('frog-kings-bargain', 'Сговор жабьего царя', 'сговора жабьего царя'),
      theme('sinking-path', 'Тонущая тропа', 'тонущей тропы'),
      theme('sedge-whisper', 'Шёпот осоки', 'шёпота осоки'),
      theme('carrion-lily', 'Падальная лилия', 'падальной лилии'),
      theme('mire-bells', 'Болотные колокольцы', 'болотных колокольцев'),
      theme('roots-beneath-water', 'Корни под водой', 'корней под водой'),
      theme('silt-memory', 'Память ила', 'памяти ила'),
      theme('heron-vigil', 'Цаплиный дозор', 'цаплиного дозора'),
      theme('leech-tithe', 'Подать пиявок', 'подати пиявок'),
      theme('green-bottomless', 'Зелёная бездна', 'зелёной бездны'),
      theme('mist-over-the-fen', 'Туман над топью', 'тумана над топью'),
      theme('sunken-beehive', 'Затонувший улей', 'затонувшего улья'),
      theme('marsh-brides-ribbon', 'Лента болотной невесты', 'ленты болотной невесты'),
      theme('black-cranberry', 'Чёрная клюква', 'чёрной клюквы'),
      theme('bogwood-testament', 'Завещание морёного дуба', 'завещания морёного дуба'),
      theme('pale-duckweed', 'Бледная ряска', 'бледной ряски'),
      theme('stillwater-pledge', 'Зарок стоячей воды', 'зарока стоячей воды'),
      theme('reedbed-refuge', 'Камышовое убежище', 'камышового убежища'),
      theme('tangled-ford', 'Запутанный брод', 'запутанного брода'),
      theme('moss-on-the-gallows', 'Мох на виселице', 'мха на виселице'),
      theme('swamp-honey', 'Мёд трясины', 'мёда трясины'),
      theme('fenwatchers-due', 'Дань смотрителю топей', 'дани смотрителю топей'),
    ],
  },
  {
    id: 'ossuary-archives', name: 'Костяные архивы', family: 'spirit', material: 'bone', silhouette: 'necromancer', hue: 32,
    themes: [
      theme('ivory-index', 'Костяной указатель', 'костяного указателя'),
      theme('nameless-ledger', 'Реестр безымянных', 'реестра безымянных'),
      theme('sealed-ossuary', 'Запечатанный оссуарий', 'запечатанного оссуария'),
      theme('dusty-epitaph', 'Пыльная эпитафия', 'пыльной эпитафии'),
      theme('jawbone-cipher', 'Шифр челюстей', 'шифра челюстей'),
      theme('undertakers-margins', 'Поля могильщика', 'полей могильщика'),
      theme('rattle-of-folios', 'Шелест костяных листов', 'шелеста костяных листов'),
      theme('burial-inventory', 'Погребальная опись', 'погребальной описи'),
      theme('unclaimed-skull', 'Невостребованный череп', 'невостребованного черепа'),
      theme('vertebral-stair', 'Лестница позвонков', 'лестницы позвонков'),
      theme('mute-witness', 'Немой свидетель', 'немого свидетеля'),
      theme('marrow-ink', 'Чернила костного мозга', 'чернил костного мозга'),
      theme('reliquary-of-names', 'Реликварий имён', 'реликвария имён'),
      theme('deathmask-catalog', 'Собрание посмертных масок', 'собрания посмертных масок'),
      theme('crypt-corrector', 'Корректор склепа', 'корректора склепа'),
      theme('ribbed-scroll', 'Ребристый свиток', 'ребристого свитка'),
      theme('forgotten-genealogy', 'Забытая родословная', 'забытой родословной'),
      theme('calcium-seal', 'Меловая печать', 'меловой печати'),
      theme('bonebound-chronicle', 'Летопись в костяном переплёте', 'летописи в костяном переплёте'),
      theme('quiet-exhumation', 'Тихая эксгумация', 'тихой эксгумации'),
      theme('epitaph-without-date', 'Эпитафия без даты', 'эпитафии без даты'),
      theme('mourning-custodian', 'Хранитель траурных списков', 'хранителя траурных списков'),
      theme('pale-annotation', 'Бледная помета', 'бледной пометы'),
      theme('catacomb-memory', 'Память катакомб', 'памяти катакомб'),
      theme('last-page-of-the-dead', 'Последняя страница мёртвых', 'последней страницы мёртвых'),
    ],
  },
  {
    id: 'lunar-loom', name: 'Лунные узоры', family: 'astral', material: 'cloth', silhouette: 'mage', hue: 237,
    themes: [
      theme('crescent-hem', 'Подол полумесяца', 'подола полумесяца'),
      theme('silver-spindle', 'Серебряное веретено', 'серебряного веретена'),
      theme('eclipse-embroidery', 'Вышивка затмения', 'вышивки затмения'),
      theme('moonwell-silk', 'Шёлк лунного колодца', 'шёлка лунного колодца'),
      theme('night-seamstress', 'Ночная швея', 'ночной швеи'),
      theme('fallen-selene', 'Падшая Селена', 'падшей Селены'),
      theme('pale-lace', 'Бледное кружево', 'бледного кружева'),
      theme('sleepwalkers-thread', 'Нить лунатика', 'нити лунатика'),
      theme('tidewoven-veil', 'Вуаль приливов', 'вуали приливов'),
      theme('owl-feather-pattern', 'Узор совиного пера', 'узора совиного пера'),
      theme('moonlit-spider', 'Паук лунного света', 'паука лунного света'),
      theme('cloudless-shawl', 'Шаль безоблачной ночи', 'шали безоблачной ночи'),
      theme('pearl-of-dreams', 'Жемчужина сновидений', 'жемчужины сновидений'),
      theme('waning-vow', 'Обет убывающей луны', 'обета убывающей луны'),
      theme('starless-bridal', 'Бесзвёздное венчание', 'бесзвёздного венчания'),
      theme('mirror-lake-satin', 'Атлас зеркального озера', 'атласа зеркального озера'),
      theme('lunarbloom-corset', 'Корсаж луноцвета', 'корсажа луноцвета'),
      theme('sigh-of-the-crescent', 'Вздох молодого месяца', 'вздоха молодого месяца'),
      theme('velvet-orbit', 'Бархатная орбита', 'бархатной орбиты'),
      theme('unravelled-night', 'Распущенная ночь', 'распущенной ночи'),
      theme('sleeping-constellation', 'Спящее созвездие', 'спящего созвездия'),
      theme('bride-of-the-tide', 'Невеста прилива', 'невесты прилива'),
      theme('sable-moonrise', 'Соболиный восход луны', 'соболиного восхода луны'),
      theme('dreamcatchers-knot', 'Узел ловца снов', 'узла ловца снов'),
      theme('loom-beyond-midnight', 'Станок за полночью', 'станка за полночью'),
    ],
  },
  {
    id: 'black-tide-corsairs', name: 'Корсары чёрного прилива', family: 'storm', material: 'leather', silhouette: 'rogue', hue: 196,
    themes: [
      theme('black-tide', 'Чёрный прилив', 'чёрного прилива'),
      theme('hanged-captain', 'Повешенный капитан', 'повешенного капитана'),
      theme('salt-cutlass', 'Солёный тесак', 'солёного тесака'),
      theme('gullbone-fleet', 'Флот чаичьих костей', 'флота чаичьих костей'),
      theme('hollow-harbor', 'Пустая гавань', 'пустой гавани'),
      theme('drowned-compass', 'Утонувший компас', 'утонувшего компаса'),
      theme('tarred-heart', 'Просмолённое сердце', 'просмолённого сердца'),
      theme('widowmaker-reef', 'Вдовий риф', 'вдовьего рифа'),
      theme('siren-ransom', 'Выкуп сирены', 'выкупа сирены'),
      theme('noose-at-the-mast', 'Петля на мачте', 'петли на мачте'),
      theme('shipless-admiral', 'Адмирал без корабля', 'адмирала без корабля'),
      theme('storm-bottle', 'Бутыль бури', 'бутыли бури'),
      theme('keelhaul-covenant', 'Клятва под килем', 'клятвы под килем'),
      theme('sharks-supper', 'Акулий ужин', 'акульего ужина'),
      theme('powder-wake', 'Пороховой след', 'порохового следа'),
      theme('blind-lighthouse', 'Слепой маяк', 'слепого маяка'),
      theme('broken-anchor', 'Сломанный якорь', 'сломанного якоря'),
      theme('dead-calm-mutiny', 'Бунт мёртвого штиля', 'бунта мёртвого штиля'),
      theme('ropewalk-ghost', 'Призрак канатного двора', 'призрака канатного двора'),
      theme('krakens-dividend', 'Доля кракена', 'доли кракена'),
      theme('red-sail-at-dusk', 'Алый парус на закате', 'алого паруса на закате'),
      theme('pearl-smugglers', 'Жемчужные контрабандисты', 'жемчужных контрабандистов'),
      theme('sea-grave-dowry', 'Приданое морской могилы', 'приданого морской могилы'),
      theme('last-port-debt', 'Долг последнего порта', 'долга последнего порта'),
      theme('captainless-drum', 'Барабан бесхозного судна', 'барабана бесхозного судна'),
    ],
  },
  {
    id: 'celestial-cartographers', name: 'Небесные картографы', family: 'arcane', material: 'mail', silhouette: 'ranger', hue: 218,
    themes: [
      theme('unmapped-meridian', 'Неизведанный меридиан', 'неизведанного меридиана'),
      theme('comet-surveyor', 'Землемер комет', 'землемера комет'),
      theme('empty-astrolabe', 'Пустая астролябия', 'пустой астролябии'),
      theme('horizon-of-glass', 'Стеклянный горизонт', 'стеклянного горизонта'),
      theme('star-ferry', 'Звёздная переправа', 'звёздной переправы'),
      theme('north-without-sun', 'Север без солнца', 'севера без солнца'),
      theme('ink-black-zenith', 'Чернильный зенит', 'чернильного зенита'),
      theme('atlas-of-abysses', 'Атлас бездн', 'атласа бездн'),
      theme('lost-parallel', 'Потерянная параллель', 'потерянной параллели'),
      theme('wayfarers-parallax', 'Параллакс странника', 'параллакса странника'),
      theme('folded-firmament', 'Сложенный небосвод', 'сложенного небосвода'),
      theme('pilots-of-the-void', 'Лоцманы пустоты', 'лоцманов пустоты'),
      theme('celestial-depthmark', 'Небесный промер', 'небесного промера'),
      theme('route-of-the-red-star', 'Путь красной звезды', 'пути красной звезды'),
      theme('boundary-of-dreams', 'Граница сновидений', 'границы сновидений'),
      theme('blind-observatory', 'Слепая обсерватория', 'слепой обсерватории'),
      theme('cracked-sextant', 'Треснувший секстант', 'треснувшего секстанта'),
      theme('dust-between-worlds', 'Пыль между мирами', 'пыли между мирами'),
      theme('star-eaters-trail', 'След пожирателя звёзд', 'следа пожирателя звёзд'),
      theme('southern-null', 'Южное безмолвие', 'южного безмолвия'),
      theme('map-of-unborn-lands', 'Карта нерождённых земель', 'карты нерождённых земель'),
      theme('copper-ephemeris', 'Медные эфемериды', 'медных эфемерид'),
      theme('anchor-of-the-sky', 'Якорь небес', 'якоря небес'),
      theme('strangers-azimuth', 'Азимут чужака', 'азимута чужака'),
      theme('last-coordinate', 'Последняя координата', 'последней координаты'),
    ],
  },
  {
    id: 'drowned-kingdoms', name: 'Затопленные царства', family: 'stone', material: 'plate', silhouette: 'guardian', hue: 38,
    themes: [
      theme('sunken-balcony', 'Затонувший балкон', 'затонувшего балкона'),
      theme('marble-below-silt', 'Мрамор под илом', 'мрамора под илом'),
      theme('king-of-the-reservoir', 'Король водохранилища', 'короля водохранилища'),
      theme('flooded-treasury', 'Залитая сокровищница', 'залитой сокровищницы'),
      theme('barnacled-throne', 'Престол в ракушках', 'престола в ракушках'),
      theme('echo-of-the-aqueduct', 'Эхо акведука', 'эха акведука'),
      theme('broken-fountain', 'Разбитый фонтан', 'разбитого фонтана'),
      theme('submerged-coronation', 'Подводная коронация', 'подводной коронации'),
      theme('last-dry-stair', 'Последняя сухая ступень', 'последней сухой ступени'),
      theme('cistern-watch', 'Дозор цистерны', 'дозора цистерны'),
      theme('silt-covered-charter', 'Заиленная грамота', 'заиленной грамоты'),
      theme('palace-eel', 'Дворцовый угорь', 'дворцового угря'),
      theme('drowned-wedding', 'Утопленная свадьба', 'утопленной свадьбы'),
      theme('oyster-crown', 'Устричный венец', 'устричного венца'),
      theme('weeping-masonry', 'Плачущая кладка', 'плачущей кладки'),
      theme('ferry-of-granite', 'Гранитный паром', 'гранитного парома'),
      theme('floodgate-tomb', 'Гробница шлюза', 'гробницы шлюза'),
      theme('coral-heraldry', 'Коралловая геральдика', 'коралловой геральдики'),
      theme('rain-swallowed-city', 'Город, проглоченный дождём', 'города, проглоченного дождём'),
      theme('sunken-mint', 'Затонувший монетный двор', 'затонувшего монетного двора'),
      theme('stairwell-to-the-depths', 'Лестница в глубину', 'лестницы в глубину'),
      theme('watermarked-kingdom', 'Царство водяных знаков', 'царства водяных знаков'),
      theme('sodden-regalia', 'Промокшие регалии', 'промокших регалий'),
      theme('sluicekeepers-vow', 'Клятва хранителя шлюза', 'клятвы хранителя шлюза'),
      theme('ruins-beneath-the-ferry', 'Руины под переправой', 'руин под переправой'),
    ],
  },
  {
    id: 'ash-forges', name: 'Пепельные горны', family: 'fire', material: 'mail', silhouette: 'paladin', hue: 14,
    themes: [
      theme('embers-covenant', 'Завет углей', 'завета углей'),
      theme('furnace-widow', 'Вдова горнила', 'вдовы горнила'),
      theme('brass-dragon', 'Латунный дракон', 'латунного дракона'),
      theme('soot-crowned-smith', 'Коронованный сажей кузнец', 'коронованного сажей кузнеца'),
      theme('quenched-revolt', 'Закалённый мятеж', 'закалённого мятежа'),
      theme('red-anvil', 'Алая наковальня', 'алой наковальни'),
      theme('bellows-of-despair', 'Меха отчаяния', 'мехов отчаяния'),
      theme('melted-scepter', 'Оплавленный скипетр', 'оплавленного скипетра'),
      theme('cinder-procession', 'Шествие головешек', 'шествия головешек'),
      theme('fire-eaters-debt', 'Долг пожирателя пламени', 'долга пожирателя пламени'),
      theme('slag-cathedral', 'Шлаковый собор', 'шлакового собора'),
      theme('coal-lung', 'Угольное лёгкое', 'угольного лёгкого'),
      theme('crucible-confession', 'Исповедь тигля', 'исповеди тигля'),
      theme('furnace-door', 'Дверь плавильни', 'двери плавильни'),
      theme('blistered-oath', 'Обожжённая клятва', 'обожжённой клятвы'),
      theme('scarlet-tongs', 'Багряные клещи', 'багряных клещей'),
      theme('glassmakers-funeral', 'Похороны стеклодува', 'похорон стеклодува'),
      theme('ash-under-the-nail', 'Пепел под ногтем', 'пепла под ногтем'),
      theme('orphaned-spark', 'Осиротевшая искра', 'осиротевшей искры'),
      theme('copper-pyre', 'Медный костёр', 'медного костра'),
      theme('cooled-lava', 'Остывшая лава', 'остывшей лавы'),
      theme('hammer-song', 'Песнь отбойного молота', 'песни отбойного молота'),
      theme('sulfur-benediction', 'Серное благословение', 'серного благословения'),
      theme('charcoal-monarch', 'Монарх древесного угля', 'монарха древесного угля'),
      theme('last-quenching', 'Последняя закалка', 'последней закалки'),
    ],
  },
  {
    id: 'winter-graves', name: 'Зимние могильники', family: 'frost', material: 'plate', silhouette: 'guardian', hue: 201,
    themes: [
      theme('rime-coffin', 'Гроб инея', 'гроба инея'),
      theme('white-funeral', 'Белые похороны', 'белых похорон'),
      theme('frozen-epitaph', 'Замёрзшая эпитафия', 'замёрзшей эпитафии'),
      theme('glacier-crown', 'Венец ледника', 'венца ледника'),
      theme('snowbound-heir', 'Занесённый снегом наследник', 'занесённого снегом наследника'),
      theme('ice-bell-tower', 'Ледяная колокольня', 'ледяной колокольни'),
      theme('buried-aurora', 'Погребённое сияние', 'погребённого сияния'),
      theme('thawless-vigil', 'Дозор без оттепели', 'дозора без оттепели'),
      theme('wolf-frost', 'Волчий мороз', 'волчьего мороза'),
      theme('cracked-permafrost', 'Треснувшая мерзлота', 'треснувшей мерзлоты'),
      theme('breath-in-the-crypt', 'Дыхание в склепе', 'дыхания в склепе'),
      theme('pale-snowdrop', 'Бледный подснежник', 'бледного подснежника'),
      theme('hoarfrost-psalm', 'Псалом изморози', 'псалма изморози'),
      theme('winter-mortician', 'Зимний гробовщик', 'зимнего гробовщика'),
      theme('icicle-rosary', 'Чётки сосулек', 'чёток сосулек'),
      theme('cold-bridesmaid', 'Холодная подружка невесты', 'холодной подружки невесты'),
      theme('snowblind-court', 'Снежнослепой двор', 'снежнослепого двора'),
      theme('last-warm-stone', 'Последний тёплый камень', 'последнего тёплого камня'),
      theme('frostbitten-banner', 'Обмороженное знамя', 'обмороженного знамени'),
      theme('silence-under-ice', 'Тишина подо льдом', 'тишины подо льдом'),
      theme('polar-censer', 'Полярное кадило', 'полярного кадила'),
      theme('unmelted-tear', 'Нерастаявшая слеза', 'нерастаявшей слезы'),
      theme('white-cairn', 'Белый курган', 'белого кургана'),
      theme('snow-burial-wreath', 'Венок снежного погребения', 'венка снежного погребения'),
      theme('frozen-doorstep', 'Замёрзший порог', 'замёрзшего порога'),
    ],
  },
  {
    id: 'crimson-courts', name: 'Багряные дворы', family: 'blood', material: 'cloth', silhouette: 'vampire', hue: 349,
    themes: [
      theme('velvet-execution', 'Бархатная казнь', 'бархатной казни'),
      theme('genealogy-of-hunger', 'Родословная голода', 'родословной голода'),
      theme('ruby-etiquette', 'Рубиновый этикет', 'рубинового этикета'),
      theme('scarlet-audience', 'Багряная аудиенция', 'багряной аудиенции'),
      theme('favorites-heart', 'Сердце фаворита', 'сердца фаворита'),
      theme('empty-goblet', 'Пустой бокал', 'пустого бокала'),
      theme('feast-behind-shutters', 'Пир за ставнями', 'пира за ставнями'),
      theme('heiress-smile', 'Улыбка наследницы', 'улыбки наследницы'),
      theme('blood-promissory', 'Кровавый вексель', 'кровавого векселя'),
      theme('night-chamberlain', 'Ночной камергер', 'ночного камергера'),
      theme('scarlet-glove', 'Алая перчатка', 'алой перчатки'),
      theme('donors-seal', 'Печать дарителя крови', 'печати дарителя крови'),
      theme('mirror-without-guest', 'Зеркало без гостя', 'зеркала без гостя'),
      theme('ball-of-dead-candles', 'Бал потухших свечей', 'бала потухших свечей'),
      theme('sweet-mourning', 'Сладкий траур', 'сладкого траура'),
      theme('bastards-chalice', 'Чаша незаконного наследника', 'чаши незаконного наследника'),
      theme('testament-of-the-fang', 'Завещание клыка', 'завещания клыка'),
      theme('first-blood-debt', 'Долг первой крови', 'долга первой крови'),
      theme('silken-headsman', 'Шёлковый палач', 'шёлкового палача'),
      theme('pale-debutante', 'Бледный дебютант', 'бледного дебютанта'),
      theme('nettle-wine', 'Крапивное вино', 'крапивного вина'),
      theme('wedding-in-crimson', 'Свадьба под багрянцем', 'свадьбы под багрянцем'),
      theme('last-curtsy', 'Последний реверанс', 'последнего реверанса'),
      theme('open-vein-heraldry', 'Герб открытой вены', 'герба открытой вены'),
      theme('everlasting-banquet', 'Вечный банкет', 'вечного банкета'),
    ],
  },
  {
    id: 'shadow-fraternities', name: 'Теневые братства', family: 'shadow', material: 'leather', silhouette: 'rogue', hue: 264,
    themes: [
      theme('stolen-footstep', 'Украденный шаг', 'украденного шага'),
      theme('hush-money', 'Откуп тишины', 'откупа тишины'),
      theme('window-without-light', 'Окно без света', 'окна без света'),
      theme('lockpicks-prayer', 'Молитва отмычки', 'молитвы отмычки'),
      theme('blind-alley-pact', 'Договор глухого переулка', 'договора глухого переулка'),
      theme('crow-feather-sign', 'Знак вороньего пера', 'знака вороньего пера'),
      theme('inked-thumb', 'Чернильный палец', 'чернильного пальца'),
      theme('guild-of-empty-pockets', 'Гильдия пустых карманов', 'гильдии пустых карманов'),
      theme('masked-creditor', 'Кредитор в маске', 'кредитора в маске'),
      theme('roof-rats', 'Крысы черепичных крыш', 'крыс черепичных крыш'),
      theme('crooked-witness', 'Лживый свидетель', 'лживого свидетеля'),
      theme('silence-for-hire', 'Наёмное молчание', 'наёмного молчания'),
      theme('candle-snuffer', 'Гаситель свечей', 'гасителя свечей'),
      theme('stolen-surname', 'Украденная фамилия', 'украденной фамилии'),
      theme('backdoor-court', 'Двор чёрного хода', 'двора чёрного хода'),
      theme('velvet-blackmail', 'Бархатный шантаж', 'бархатного шантажа'),
      theme('narrow-stair', 'Узкая лестница', 'узкой лестницы'),
      theme('midnight-notary', 'Полуночный нотариус', 'полуночного нотариуса'),
      theme('nameless-key', 'Безымянный ключ', 'безымянного ключа'),
      theme('false-bottom', 'Двойное дно', 'двойного дна'),
      theme('coin-under-the-tongue', 'Монета под языком', 'монеты под языком'),
      theme('unseen-handshake', 'Невидимое рукопожатие', 'невидимого рукопожатия'),
      theme('orphaned-shadow', 'Осиротевшая тень', 'осиротевшей тени'),
      theme('loose-cobblestone', 'Шаткий булыжник', 'шаткого булыжника'),
      theme('gallows-pardon', 'Помилование у виселицы', 'помилования у виселицы'),
    ],
  },
  {
    id: 'venom-gardens', name: 'Сады ядов', family: 'venom', material: 'leather', silhouette: 'druid', hue: 85,
    themes: [
      theme('belladonna-court', 'Двор белладонны', 'двора белладонны'),
      theme('hemlock-wreath', 'Венок болиголова', 'венка болиголова'),
      theme('foxglove-chalice', 'Чаша наперстянки', 'чаши наперстянки'),
      theme('serpents-orchard', 'Змеиный плодовый сад', 'змеиного плодового сада'),
      theme('bitter-harvest', 'Горькая жатва', 'горькой жатвы'),
      theme('widows-greenhouse', 'Теплица вдов', 'теплицы вдов'),
      theme('sleeping-mandrake', 'Спящая мандрагора', 'спящей мандрагоры'),
      theme('blistering-dew', 'Обжигающая роса', 'обжигающей росы'),
      theme('yellowed-herbarium', 'Пожелтевший гербарий', 'пожелтевшего гербария'),
      theme('thorns-under-glass', 'Шипы под стеклом', 'шипов под стеклом'),
      theme('nightshade-wedding', 'Паслёновая свадьба', 'паслёновой свадьбы'),
      theme('moulded-nectar', 'Плесневый нектар', 'плесневого нектара'),
      theme('apothecarys-farewell', 'Прощание аптекаря', 'прощания аптекаря'),
      theme('green-widow', 'Зелёная вдова', 'зелёной вдовы'),
      theme('vinegar-bloom', 'Уксусный цвет', 'уксусного цвета'),
      theme('scorpion-rose', 'Скорпионья роза', 'скорпионьей розы'),
      theme('saffron-of-decay', 'Шафран тления', 'шафрана тления'),
      theme('adder-root', 'Змеиный корень', 'змеиного корня'),
      theme('gardeners-last-dose', 'Последняя доза садовника', 'последней дозы садовника'),
      theme('sour-apple-oath', 'Клятва кислого яблока', 'клятвы кислого яблока'),
      theme('moth-eaten-petal', 'Изъеденный молью лепесток', 'изъеденного молью лепестка'),
      theme('dead-bees-hive', 'Улей мёртвых пчёл', 'улья мёртвых пчёл'),
      theme('jars-of-whispering-seeds', 'Склянки шепчущих семян', 'склянок шепчущих семян'),
      theme('milky-sap', 'Млечный сок', 'млечного сока'),
      theme('orchid-of-the-grave', 'Могильная орхидея', 'могильной орхидеи'),
    ],
  },
  {
    id: 'hourglass-cloisters', name: 'Обители песочных часов', family: 'time', material: 'cloth', silhouette: 'mage', hue: 41,
    themes: [
      theme('unstruck-hour', 'Непробивший час', 'непробившего часа'),
      theme('sandkeepers-vow', 'Обет хранителя песка', 'обета хранителя песка'),
      theme('rusted-pendulum', 'Ржавый маятник', 'ржавого маятника'),
      theme('cloister-of-yesterday', 'Обитель вчерашнего дня', 'обители вчерашнего дня'),
      theme('borrowed-dawn', 'Заимствованный рассвет', 'заимствованного рассвета'),
      theme('calendar-of-ashes', 'Календарь пепла', 'календаря пепла'),
      theme('stillborn-season', 'Нерождённое время года', 'нерождённого времени года'),
      theme('clock-without-hands', 'Часы без стрелок', 'часов без стрелок'),
      theme('forgotten-birthday', 'Забытый день рождения', 'забытого дня рождения'),
      theme('sundial-at-midnight', 'Полуночные солнечные часы', 'полуночных солнечных часов'),
      theme('unspent-year', 'Непрожитый год', 'непрожитого года'),
      theme('delayed-funeral', 'Отложенные похороны', 'отложенных похорон'),
      theme('sands-of-the-cell', 'Пески затворнической кельи', 'песков затворнической кельи'),
      theme('witness-to-tomorrow', 'Свидетель завтрашнего дня', 'свидетеля завтрашнего дня'),
      theme('worn-out-eternity', 'Потёртая вечность', 'потёртой вечности'),
      theme('echo-before-the-bell', 'Эхо перед звоном', 'эха перед звоном'),
      theme('last-leap-year', 'Последний високосный год', 'последнего високосного года'),
      theme('motionless-procession', 'Неподвижное шествие', 'неподвижного шествия'),
      theme('ageing-mirror', 'Стареющее зеркало', 'стареющего зеркала'),
      theme('thread-of-an-instant', 'Нить мгновения', 'нити мгновения'),
      theme('annulled-prophecy', 'Отменённое пророчество', 'отменённого пророчества'),
      theme('timeless-confession', 'Исповедь вне времени', 'исповеди вне времени'),
      theme('stolen-afternoon', 'Украденный полдень', 'украденного полдня'),
      theme('monastery-of-recurrence', 'Монастырь возвращения', 'монастыря возвращения'),
      theme('dust-of-a-century', 'Пыль столетия', 'пыли столетия'),
    ],
  },
  {
    id: 'war-reliquaries', name: 'Реликвии забытых войн', family: 'war', material: 'plate', silhouette: 'guardian', hue: 3,
    themes: [
      theme('orphaned-regiment', 'Осиротевший полк', 'осиротевшего полка'),
      theme('truce-of-crows', 'Воронье перемирие', 'вороньего перемирия'),
      theme('broken-pike', 'Сломанная пика', 'сломанной пики'),
      theme('fields-without-harvest', 'Поля без жатвы', 'полей без жатвы'),
      theme('drummer-without-hands', 'Безрукий барабанщик', 'безрукого барабанщика'),
      theme('shattered-triumph', 'Разбитый триумф', 'разбитого триумфа'),
      theme('nameless-siege', 'Безымянная осада', 'безымянной осады'),
      theme('ransom-of-the-banner', 'Выкуп знамени', 'выкупа знамени'),
      theme('hollow-victory', 'Полая победа', 'полой победы'),
      theme('sapper-under-the-wall', 'Подкоп под стеной', 'подкопа под стеной'),
      theme('last-ration', 'Последний паёк', 'последнего пайка'),
      theme('generals-silence', 'Молчание полководца', 'молчания полководца'),
      theme('oath-of-the-deserter', 'Клятва дезертира', 'клятвы дезертира'),
      theme('widows-muster', 'Вдовий сбор', 'вдовьего сбора'),
      theme('smoke-over-the-trench', 'Дым над рвом', 'дыма над рвом'),
      theme('bloodied-trumpet', 'Окровавленная труба', 'окровавленной трубы'),
      theme('tattered-laurel', 'Изорванный лавр', 'изорванного лавра'),
      theme('fallen-standardbearer', 'Павший знаменосец', 'павшего знаменосца'),
      theme('veterans-copper', 'Ветеранская медь', 'ветеранской меди'),
      theme('burial-of-the-drums', 'Погребение барабанов', 'погребения барабанов'),
      theme('unpaid-company', 'Неоплаченная дружина', 'неоплаченной дружины'),
      theme('bones-on-the-border', 'Кости на границе', 'костей на границе'),
      theme('parade-of-the-missing', 'Парад пропавших', 'парада пропавших'),
      theme('siege-widowers', 'Вдовцы осады', 'вдовцов осады'),
      theme('mercy-after-battle', 'Милосердие после битвы', 'милосердия после битвы'),
    ],
  },
  {
    id: 'sun-sepulchers', name: 'Солнечные усыпальницы', family: 'holy', material: 'plate', silhouette: 'paladin', hue: 45,
    themes: [
      theme('buried-sun', 'Погребённое солнце', 'погребённого солнца'),
      theme('golden-sarcophagus', 'Золотой саркофаг', 'золотого саркофага'),
      theme('dusk-in-the-sanctum', 'Закат в святилище', 'заката в святилище'),
      theme('blind-saint', 'Слепой святой', 'слепого святого'),
      theme('sun-eaters-confession', 'Исповедь пожирателя солнца', 'исповеди пожирателя солнца'),
      theme('gilded-requiem', 'Позолоченный реквием', 'позолоченного реквиема'),
      theme('marble-halo', 'Мраморный нимб', 'мраморного нимба'),
      theme('sealed-noon', 'Запечатанный полдень', 'запечатанного полдня'),
      theme('flame-behind-the-altar', 'Пламя за алтарём', 'пламени за алтарём'),
      theme('solar-mourning', 'Солнечный траур', 'солнечного траура'),
      theme('dust-of-martyrs', 'Пыль мучеников', 'пыли мучеников'),
      theme('silent-benediction', 'Безмолвное благословение', 'безмолвного благословения'),
      theme('ivory-sundoor', 'Костяные врата солнца', 'костяных врат солнца'),
      theme('funeral-daybreak', 'Погребальный рассвет', 'погребального рассвета'),
      theme('copper-seraph', 'Медный серафим', 'медного серафима'),
      theme('unlit-sanctuary', 'Незажжённое святилище', 'незажжённого святилища'),
      theme('tear-of-the-icon', 'Слеза иконы', 'слезы иконы'),
      theme('saffron-shroud', 'Шафрановый саван', 'шафранового савана'),
      theme('crown-of-dry-rays', 'Венец иссохших лучей', 'венца иссохших лучей'),
      theme('last-solar-tithe', 'Последняя солнечная десятина', 'последней солнечной десятины'),
      theme('broken-aureole', 'Расколотая ауреола', 'расколотой ауреолы'),
      theme('tomb-of-the-morning-star', 'Гробница утренней звезды', 'гробницы утренней звезды'),
      theme('goldleaf-penance', 'Сусальное покаяние', 'сусального покаяния'),
      theme('choir-under-stone', 'Хор под камнем', 'хора под камнем'),
      theme('dawn-without-witnesses', 'Рассвет без свидетелей', 'рассвета без свидетелей'),
    ],
  },
  {
    id: 'storm-outriders', name: 'Всадники ненастья', family: 'storm', material: 'mail', silhouette: 'ranger', hue: 211,
    themes: [
      theme('thunder-saddle', 'Грозовое седло', 'грозового седла'),
      theme('bridle-of-wind', 'Узда ветра', 'узды ветра'),
      theme('rain-soaked-pennant', 'Промокший вымпел', 'промокшего вымпела'),
      theme('last-weather-vane', 'Последний флюгер', 'последнего флюгера'),
      theme('lightning-spur', 'Молниевая шпора', 'молниевой шпоры'),
      theme('stormcloud-herd', 'Табун грозовых туч', 'табуна грозовых туч'),
      theme('broken-winged-courier', 'Гонец сломанных крыльев', 'гонца сломанных крыльев'),
      theme('hurricane-toll', 'Пошлина урагана', 'пошлины урагана'),
      theme('copper-weather', 'Медное ненастье', 'медного ненастья'),
      theme('hoofprints-in-clouds', 'Следы копыт в облаках', 'следов копыт в облаках'),
      theme('falcon-before-the-squall', 'Сокол перед шквалом', 'сокола перед шквалом'),
      theme('rainkeepers-truce', 'Перемирие хранителей дождя', 'перемирия хранителей дождя'),
      theme('distant-thunder-oath', 'Зарок далёкого грома', 'зарока далёкого грома'),
      theme('lightning-rods-vigil', 'Дозор громоотвода', 'дозора громоотвода'),
      theme('feather-of-the-tempest', 'Перо ненастья', 'пера ненастья'),
      theme('storm-torn-bridal', 'Разорванная бурей свадьба', 'разорванной бурей свадьбы'),
      theme('silver-downpour', 'Серебряный ливень', 'серебряного ливня'),
      theme('skybridge-warden', 'Смотритель небесного моста', 'смотрителя небесного моста'),
      theme('charred-horseshoe', 'Обугленная подкова', 'обугленной подковы'),
      theme('eye-of-the-rain', 'Око дождя', 'ока дождя'),
      theme('blue-thunderstone', 'Синий громовой камень', 'синего громового камня'),
      theme('squall-at-the-pass', 'Шквал на перевале', 'шквала на перевале'),
      theme('untamed-cloud', 'Непокорённая туча', 'непокорённой тучи'),
      theme('storm-bells-of-the-steppe', 'Грозовые колокольцы степи', 'грозовых колокольцев степи'),
      theme('oath-to-the-open-sky', 'Клятва открытому небу', 'клятвы открытому небу'),
    ],
  },
  {
    id: 'beast-borderlands', name: 'Звериное пограничье', family: 'nature', material: 'leather', silhouette: 'ranger', hue: 112,
    themes: [
      theme('wolf-at-the-threshold', 'Волк у порога', 'волка у порога'),
      theme('antlered-exile', 'Рогатый изгнанник', 'рогатого изгнанника'),
      theme('bears-last-den', 'Последняя берлога', 'последней берлоги'),
      theme('fox-under-the-gallows', 'Лиса под виселицей', 'лисы под виселицей'),
      theme('boars-broken-tusk', 'Сломанный клык вепря', 'сломанного клыка вепря'),
      theme('owls-verdict', 'Совиный приговор', 'совиного приговора'),
      theme('lynx-on-the-border', 'Рысь на границе', 'рыси на границе'),
      theme('ravens-winter-feast', 'Зимний пир ворона', 'зимнего пира ворона'),
      theme('badgers-burrow', 'Барсучий схрон', 'барсучьего схрона'),
      theme('stag-without-forest', 'Олень без леса', 'оленя без леса'),
      theme('hounds-unkept-promise', 'Нарушенный обет гончей', 'нарушенного обета гончей'),
      theme('serpent-at-the-stump', 'Змея у пня', 'змеи у пня'),
      theme('hare-in-the-snare', 'Заяц в силке', 'зайца в силке'),
      theme('marten-in-the-belfry', 'Куница на звоннице', 'куницы на звоннице'),
      theme('old-bisons-path', 'Тропа старого зубра', 'тропы старого зубра'),
      theme('wolverines-pledge', 'Зарок росомахи', 'зарока росомахи'),
      theme('heron-of-the-dead-river', 'Цапля мёртвой реки', 'цапли мёртвой реки'),
      theme('moth-in-the-lantern', 'Мотылёк в фонаре', 'мотылька в фонаре'),
      theme('eagles-empty-nest', 'Пустое гнездо орла', 'пустого гнезда орла'),
      theme('hedgehog-of-the-thorns', 'Ёж терновника', 'ежа терновника'),
      theme('ram-at-the-ruined-gate', 'Баран у разрушенных врат', 'барана у разрушенных врат'),
      theme('vultures-inheritance', 'Наследство стервятника', 'наследства стервятника'),
      theme('otters-drowned-stone', 'Затонувший камень выдры', 'затонувшего камня выдры'),
      theme('wildcats-silent-song', 'Тихая песня лесного кота', 'тихой песни лесного кота'),
      theme('pack-without-a-leader', 'Стая без вожака', 'стаи без вожака'),
    ],
  },
  {
    id: 'forbidden-inks', name: 'Запретные чернила', family: 'arcane', material: 'cloth', silhouette: 'necromancer', hue: 271,
    themes: [
      theme('blasphemers-margin', 'Поля богохульника', 'полей богохульника'),
      theme('unwritten-gospel', 'Ненаписанное евангелие', 'ненаписанного евангелия'),
      theme('living-palimpsest', 'Живой палимпсест', 'живого палимпсеста'),
      theme('inkwell-of-regret', 'Чернильница сожалений', 'чернильницы сожалений'),
      theme('censored-name', 'Вымаранное имя', 'вымаранного имени'),
      theme('paper-coffin', 'Бумажный гроб', 'бумажного гроба'),
      theme('script-that-watches', 'Следящая письменность', 'следящей письменности'),
      theme('quill-of-the-condemned', 'Перо осуждённого', 'пера осуждённого'),
      theme('book-of-locked-mouths', 'Книга запертых ртов', 'книги запертых ртов'),
      theme('last-editors-debt', 'Долг последнего редактора', 'долга последнего редактора'),
      theme('black-wax-colophon', 'Чёрный восковой колофон', 'чёрного воскового колофона'),
      theme('manuscript-of-fever', 'Рукопись лихорадки', 'рукописи лихорадки'),
      theme('unburnt-page', 'Несгоревшая страница', 'несгоревшей страницы'),
      theme('rune-on-the-tongue', 'Руна на языке', 'руны на языке'),
      theme('torn-prologue', 'Вырванный пролог', 'вырванного пролога'),
      theme('library-under-the-skin', 'Библиотека под кожей', 'библиотеки под кожей'),
      theme('mute-alphabet', 'Немой алфавит', 'немого алфавита'),
      theme('gallows-calligraphy', 'Висельная каллиграфия', 'висельной каллиграфии'),
      theme('scribe-of-the-unborn', 'Писец нерождённых', 'писца нерождённых'),
      theme('vermilion-correction', 'Киноварная правка', 'киноварной правки'),
      theme('watermarked-curse', 'Проклятие водяного знака', 'проклятия водяного знака'),
      theme('spine-of-the-chronicle', 'Корешок летописи', 'корешка летописи'),
      theme('treatise-on-absence', 'Трактат об отсутствии', 'трактата об отсутствии'),
      theme('unsent-last-letter', 'Неотправленное последнее письмо', 'неотправленного последнего письма'),
      theme('ink-eaters-supper', 'Ужин пожирателя чернил', 'ужина пожирателя чернил'),
    ],
  },
  {
    id: 'wandering-lanterns', name: 'Блуждающие светочи', family: 'spirit', material: 'cloth', silhouette: 'priest', hue: 180,
    themes: [
      theme('lantern-at-the-crossroads', 'Фонарь на распутье', 'фонаря на распутье'),
      theme('ferrymans-last-coin', 'Последний обол перевозчика', 'последнего обола перевозчика'),
      theme('light-without-flame', 'Свет без пламени', 'света без пламени'),
      theme('lost-childs-candle', 'Свеча потерянного ребёнка', 'свечи потерянного ребёнка'),
      theme('roadside-ghost', 'Придорожный призрак', 'придорожного призрака'),
      theme('blue-wisp-procession', 'Шествие синих огоньков', 'шествия синих огоньков'),
      theme('bell-over-the-ferry', 'Колокол над переправой', 'колокола над переправой'),
      theme('names-in-the-smoke', 'Имена в дыму', 'имён в дыму'),
      theme('hospitality-of-the-dead', 'Гостеприимство мёртвых', 'гостеприимства мёртвых'),
      theme('unclosed-door', 'Незакрытая дверь', 'незакрытой двери'),
      theme('candle-in-the-window', 'Свеча в окне', 'свечи в окне'),
      theme('whispering-milestone', 'Шепчущий верстовой столб', 'шепчущего верстового столба'),
      theme('sparks-of-reunion', 'Искры воссоединения', 'искр воссоединения'),
      theme('forgotten-inn', 'Забытый постоялый двор', 'забытого постоялого двора'),
      theme('travelers-empty-chair', 'Пустое кресло путника', 'пустого кресла путника'),
      theme('lanternmakers-mourning', 'Траур фонарщика', 'траура фонарщика'),
      theme('embers-on-the-water', 'Угли на воде', 'углей на воде'),
      theme('unseen-homecoming', 'Незримое возвращение', 'незримого возвращения'),
      theme('mourning-moths', 'Траурные мотыльки', 'траурных мотыльков'),
      theme('doorstep-of-the-between', 'Порог между мирами', 'порога между мирами'),
      theme('watchfire-for-the-lost', 'Костёр для заблудших', 'костра для заблудших'),
      theme('hollow-voice-at-dawn', 'Полый голос на рассвете', 'полого голоса на рассвете'),
      theme('last-light-of-the-village', 'Последний огонь деревни', 'последнего огня деревни'),
      theme('soul-at-the-waystation', 'Душа на заставе', 'души на заставе'),
      theme('quiet-road-home', 'Тихая дорога домой', 'тихой дороги домой'),
    ],
  },
];
