import { skillSchool } from './skill-catalog-builders';

/** Each school adds seven common, five rare and four epic learnable arts. */
export const lifeProportionalSkills = [
  ...skillSchool('blood', 300, [
    {
      id: 'sanguine_mote', name: 'Кровяная искра', rarity: 'common', cooldown: 2, target: 'enemy', projectile: 'blood',
      description: 'Создаёт себе щит на 1d4 на 1 ход, затем атакует врага на 1d6 + Силу. Щит не зависит от попадания; Сила к его ёмкости не добавляется.',
      actions: [{ type: 'shield', dice: '1d4', duration: 1, target: 'self' }, { type: 'damage', dice: '1d6', scaling: 'power' }],
      tags: ['DAMAGE', 'SHIELD'], icon: { frame: 'burst', motif: 'drop', accent: 'bolt' },
    },
    {
      id: 'scent_of_failing_pulse', name: 'Запах слабого пульса', rarity: 'common', cooldown: 2, target: 'lowestHealthEnemy', projectile: 'blood',
      description: 'Атакует выбранного врага на 2d4 + Силу. Добивание не гарантируется. При автовыборе приоритет у врага с наименьшей долей здоровья.',
      actions: [{ type: 'damage', dice: '2d4', scaling: 'power' }],
      tags: ['DAMAGE', 'AUTOTARGET'], icon: { frame: 'orbit', motif: 'fang', accent: 'eye' },
    },
    {
      id: 'clotted_cuirass', name: 'Запёкшийся панцирь', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'blood',
      description: 'Даёт союзнику щит на 2d4 на 2 хода и Покров алой росы на 1 ход: в начале следующего хода появляется ещё слой щита на 1d6 со сроком 1 ход. Оба щита без прибавки Силы.',
      actions: [{ type: 'shield', dice: '2d4', duration: 2 }, { type: 'status', statusId: 'sanguine_veil', duration: 1 }],
      tags: ['SHIELD'], icon: { frame: 'ward', motif: 'shield', accent: 'drop' },
    },
    {
      id: 'shared_vein', name: 'Общая жила', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'blood',
      description: 'Алый завет на 2 хода: когда союзник действительно получает лечение, он лечит весь свой отряд на 1d4. Переданное лечение не создаёт цепочку новых передач.',
      actions: [{ type: 'status', statusId: 'scarlet_covenant', duration: 2 }],
      tags: ['BUFF', 'HEAL'], icon: { frame: 'weave', motif: 'drop', accent: 'leaf' },
    },
    {
      id: 'iron_heartbeat', name: 'Железный пульс', rarity: 'common', cooldown: 3, target: 'self', projectile: 'blood',
      description: 'Лечится на 1d8 + Силу и получает Боевой дух на 2 хода: +2 к броскам урона. Бонус не усиливает исцеление.',
      actions: [{ type: 'heal', dice: '1d8', scaling: 'power' }, { type: 'status', statusId: 'battle_fervor', duration: 2 }],
      tags: ['HEAL', 'BUFF'], icon: { frame: 'seal', motif: 'drop', accent: 'rock' },
    },
    {
      id: 'crimson_omen', name: 'Алое предвестие', rarity: 'common', cooldown: 3, target: 'randomEnemy', projectile: 'blood',
      description: 'Случайный враг получает Рваную рану на 2 хода без броска попадания: Сила −2, в конце хода — 1d6 урона без Защиты. В ход наложения урона нет.',
      actions: [{ type: 'status', statusId: 'open_wound', duration: 2 }],
      tags: ['RANDOM', 'BLEED', 'DEBUFF'], icon: { frame: 'rays', motif: 'eye', accent: 'fang' },
    },
    {
      id: 'vessel_of_first_blood', name: 'Сосуд первой крови', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'blood',
      description: 'Лечит союзника на 1d6 + Силу и накладывает Жажду хищника на 1 ход: Точность +1; после прямого урона здоровью врага носитель лечится на 1d4, не больше нанесённого урона.',
      actions: [{ type: 'heal', dice: '1d6', scaling: 'power' }, { type: 'status', statusId: 'predators_thirst', duration: 1 }],
      tags: ['HEAL', 'VAMPIRISM'], icon: { frame: 'seal', motif: 'fang', accent: 'cross' },
    },
    {
      id: 'physicians_red_suture', name: 'Алый шов лекаря', rarity: 'rare', cooldown: 4, target: 'ally', projectile: 'blood',
      description: 'Заклинатель получает Печать заживления на 3 хода: Сила +2; после тика наложенного им периодического лечения — 1d6, на 5+ срок заряда продлевается на ход. Союзник получает Багровое восстановление на 3 хода: в начале хода лечится на 1d4 + Силу источника.',
      actions: [{ type: 'status', statusId: 'clotting_seal', duration: 3, target: 'self' }, { type: 'status', statusId: 'crimson_mending', duration: 3 }],
      tags: ['HOT', 'BUFF'], icon: { frame: 'weave', motif: 'rune', accent: 'drop' },
    },
    {
      id: 'bargain_of_two_hearts', name: 'Сделка двух сердец', rarity: 'rare', cooldown: 4, target: 'any', projectile: 'blood',
      description: 'Союзника лечит на 2d4 + Силу и даёт Покров алой росы на 2 хода: щит 1d6 на 1 ход в начале хода. Врагу сначала даёт Цену крови на 2 хода (Защита −4, но урон +4), затем атакует на 2d6 + Силу. Цена остаётся при промахе.',
      actions: [{ type: 'heal', dice: '2d4', scaling: 'power', targetRelation: 'ally' }, { type: 'status', statusId: 'sanguine_veil', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'blood_price', duration: 2, targetRelation: 'enemy' }, { type: 'damage', dice: '2d6', scaling: 'power', targetRelation: 'enemy' }],
      tags: ['HYBRID', 'HEAL', 'SHIELD', 'TRADEOFF'], icon: { frame: 'orbit', motif: 'drop', accent: 'shield' },
    },
    {
      id: 'three_crimson_barbs', name: 'Три багровых зубца', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'blood',
      description: 'Три независимых удара по выбранному врагу, каждый на 1d4 без Силы. Каждое попадание оставляет отдельное Кровотечение на 2 хода: 1d4 урона без Защиты в конце хода. После гибели цели серия прекращается.',
      actions: [{ type: 'damage', dice: '1d4', hits: 3, onHitStatusId: 'bleeding', onHitDuration: 2 }],
      tags: ['MULTIHIT', 'BLEED'], icon: { frame: 'arrows', motif: 'drop', accent: 'claw' },
    },
    {
      id: 'pulse_across_the_veil', name: 'Пульс сквозь завесу', rarity: 'rare', cooldown: 4, target: 'enemy', projectile: 'blood',
      description: 'Лечит союзника с наименьшей долей здоровья на 1d6 + Силу, затем атакует выбранного врага на 2d6 + Силу. Лечение не зависит от попадания и нанесённого урона.',
      actions: [{ type: 'heal', dice: '1d6', scaling: 'power', target: 'lowestHealthAlly' }, { type: 'damage', dice: '2d6', scaling: 'power' }],
      tags: ['HEAL', 'DAMAGE', 'AUTOTARGET'], icon: { frame: 'rays', motif: 'cross', accent: 'fang' },
    },
    {
      id: 'chalice_of_kinship', name: 'Чаша родства', rarity: 'rare', cooldown: 5, target: 'self', projectile: 'blood',
      description: 'Получает Алый завет на 3 хода, затем лечится на 2d6 + Силу. Если восстановлено здоровье, завет сразу передаёт отряду лечение на 1d4; будущие полученные исцеления тоже вызывают передачу без цепочки повторов.',
      actions: [{ type: 'status', statusId: 'scarlet_covenant', duration: 3 }, { type: 'heal', dice: '2d6', scaling: 'power' }],
      tags: ['HEAL', 'BUFF'], icon: { frame: 'ward', motif: 'cross', accent: 'drop' },
    },
    {
      id: 'sanguine_tribunal', name: 'Кровавый трибунал', rarity: 'epic', cooldown: 6, target: 'allEnemies', projectile: 'blood',
      description: 'Всем врагам сначала даёт Цену крови на 2 хода: Защита каждой части тела −4, но броски урона +4. Затем атакует каждого на 2d8 + половину Силы. Ослабление Защиты и опасный бонус урона остаются при промахе.',
      actions: [{ type: 'status', statusId: 'blood_price', duration: 2 }, { type: 'damage', dice: '2d8', scaling: 'power', factor: .5 }],
      tags: ['MASS', 'DAMAGE', 'TRADEOFF'], icon: { frame: 'burst', motif: 'skull', accent: 'drop' },
    },
    {
      id: 'coronet_of_open_veins', name: 'Венец открытых вен', rarity: 'epic', cooldown: 6, target: 'allEnemies', projectile: 'blood',
      description: 'Все враги получают Кровотечение на 3 хода: 1d4 урона без Защиты в конце хода. Заклинатель на 3 хода получает Жажду хищника: Точность +1 и лечение на 1d4 после прямого урона врагу, не больше нанесённого. При применении прямых ударов нет.',
      actions: [{ type: 'status', statusId: 'bleeding', duration: 3 }, { type: 'status', statusId: 'predators_thirst', duration: 3, target: 'self' }],
      tags: ['MASS', 'BLEED', 'VAMPIRISM'], icon: { frame: 'orbit', motif: 'skull', accent: 'fang' },
    },
    {
      id: 'banner_of_blood_kin', name: 'Знамя кровного братства', rarity: 'epic', cooldown: 7, target: 'allAllies', projectile: 'blood',
      description: 'Каждый союзник получает щит на 1d6 + Силу на 2 хода и Алый завет на 2 хода. Получив реальное исцеление, носитель лечит весь отряд на 1d4; переданное лечение не порождает цепочку новых передач.',
      actions: [{ type: 'shield', dice: '1d6', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'scarlet_covenant', duration: 2 }],
      tags: ['MASS', 'SHIELD', 'HEAL'], icon: { frame: 'weave', motif: 'shield', accent: 'cross' },
    },
    {
      id: 'pursuit_of_the_last_heartbeat', name: 'Погоня за последним пульсом', rarity: 'epic', cooldown: 6, target: 'lowestHealthEnemy', projectile: 'blood',
      description: 'Получает Охотника за сердцами на 2 хода: Критический удар +3 и дополнительный 1d4 к прямым ударам. Затем атакует выбранного врага на 3d8 + Силу и 1d4 от охотника; попадание оставляет Рваную рану на 2 хода (Сила −2, 1d6 без Защиты в конце хода). При автовыборе приоритет у врага с наименьшей долей здоровья.',
      actions: [{ type: 'status', statusId: 'heart_hunter', duration: 2, target: 'self' }, { type: 'damage', dice: '3d8', scaling: 'power', onHitStatusId: 'open_wound', onHitDuration: 2 }],
      tags: ['AUTOTARGET', 'CRITICAL', 'BLEED'], icon: { frame: 'slash', motif: 'eye', accent: 'drop' },
    },
  ]),
  ...skillSchool('holy', 316, [
    {
      id: 'ember_of_matins', name: 'Уголёк утрени', rarity: 'common', cooldown: 3, target: 'self', projectile: 'holy',
      description: 'Исцеление рассвета на 2 хода: в начале собственного хода восстанавливает 1d6 + Силу источника. В ход наложения лечение ещё не срабатывает.',
      actions: [{ type: 'status', statusId: 'dawn_mending', duration: 2 }],
      tags: ['HOT'], icon: { frame: 'orbit', motif: 'flame', accent: 'star' },
    },
    {
      id: 'wandering_sanctuary_spark', name: 'Блуждающая искра приюта', rarity: 'common', cooldown: 3, target: 'randomAlly', projectile: 'holy',
      description: 'Случайный союзник получает щит на 1d8 + Силу на 2 хода и Благодать паломника на 1 ход: Проворность +3, Уклонение +2.',
      actions: [{ type: 'shield', dice: '1d8', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'pilgrims_grace', duration: 1 }],
      tags: ['RANDOM', 'SHIELD', 'EVASION'], icon: { frame: 'weave', motif: 'feather', accent: 'flame' },
    },
    {
      id: 'needle_of_noon', name: 'Игла полудня', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'holy',
      description: 'Удар на 2d4 без прибавки Силы, игнорирующий Защиту. Щиты и полное блокирование продолжают работать; попадание и крит проверяются отдельно.',
      actions: [{ type: 'damage', dice: '2d4', bypassArmor: true }],
      tags: ['DAMAGE', 'PIERCE'], icon: { frame: 'slash', motif: 'star', accent: 'cross' },
    },
    {
      id: 'pilgrims_reproof', name: 'Укор паломника', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'holy',
      description: 'Светлый приговор на 2 хода: Точность врага −3, Критический удар −2. Накладывается без прямого удара и без проверки попадания.',
      actions: [{ type: 'status', statusId: 'radiant_censure', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'seal', motif: 'cross', accent: 'eye' },
    },
    {
      id: 'bread_of_the_road', name: 'Хлеб дальней дороги', rarity: 'common', cooldown: 2, target: 'lowestHealthAlly', projectile: 'holy',
      description: 'Лечит выбранного союзника на 2d6 без прибавки Силы. Критическое лечение проверяется отдельным d20. При автовыборе приоритет у наиболее раненого союзника.',
      actions: [{ type: 'heal', dice: '2d6' }],
      tags: ['AUTOTARGET', 'HEAL'], icon: { frame: 'rays', motif: 'leaf', accent: 'cross' },
    },
    {
      id: 'pledge_at_the_gate', name: 'Обещание у ворот', rarity: 'common', cooldown: 4, target: 'ally', projectile: 'holy',
      description: 'Дозор мученика на 2 хода: Защита союзника +2. Перед прямым уроном участнику его отряда носитель уменьшает оставшийся после защиты урон на 1d4, вплоть до нуля.',
      actions: [{ type: 'status', statusId: 'martyrs_vigil', duration: 2 }],
      tags: ['GUARD', 'ARMOR'], icon: { frame: 'ward', motif: 'feather', accent: 'rune' },
    },
    {
      id: 'consecrated_lot', name: 'Освящённый жребий', rarity: 'common', cooldown: 2, target: 'randomUnit', projectile: 'holy',
      description: 'Кубик выбирает одного живого участника. Союзник получает Благословение на 1 ход: дополнительный 1d4 к прямым ударам. Враг получает атаку на 2d4 + Силу.',
      actions: [{ type: 'status', statusId: 'inspired', duration: 1, targetRelation: 'ally' }, { type: 'damage', dice: '2d4', scaling: 'power', targetRelation: 'enemy' }],
      tags: ['RANDOM', 'HYBRID', 'BUFF'], icon: { frame: 'burst', motif: 'rune', accent: 'cross' },
    },
    {
      id: 'ward_of_the_oathkeeper', name: 'Покров хранителя обетов', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'holy',
      description: 'Заклинатель получает Клятву убежища на 3 хода и создаёт союзнику щит на 2d6 + Силу на 3 хода. При расходе созданных им щитов заклинатель бросает 1d6: на 5+ остаток урона поглощается без расхода ёмкости.',
      actions: [{ type: 'status', statusId: 'oath_of_sanctuary', duration: 3, target: 'self' }, { type: 'shield', dice: '2d6', scaling: 'power', duration: 3 }],
      tags: ['SHIELD', 'BUFF'], icon: { frame: 'weave', motif: 'rune', accent: 'feather' },
    },
    {
      id: 'sunlit_wayfarers', name: 'Странники под солнцем', rarity: 'rare', cooldown: 5, target: 'allAllies', projectile: 'holy',
      description: 'Весь отряд получает Благодать паломника на 2 хода: Проворность +3, Уклонение +2. Только заклинатель немедленно лечится на 2d4 + Силу.',
      actions: [{ type: 'status', statusId: 'pilgrims_grace', duration: 2 }, { type: 'heal', dice: '2d4', scaling: 'power', target: 'self' }],
      tags: ['MASS', 'EVASION', 'HEAL'], icon: { frame: 'arrows', motif: 'star', accent: 'feather' },
    },
    {
      id: 'prayer_of_two_answers', name: 'Молитва двух ответов', rarity: 'rare', cooldown: 4, target: 'any', projectile: 'holy',
      description: 'Союзник получает Исцеление рассвета на 2 хода: 1d6 + Сила источника в начале хода. Враг получает Светлый приговор на 3 хода (Точность −3, Критический удар −2), затем удар на 1d8 + Силу. Приговор остаётся при промахе.',
      actions: [{ type: 'status', statusId: 'dawn_mending', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'radiant_censure', duration: 3, targetRelation: 'enemy' }, { type: 'damage', dice: '1d8', scaling: 'power', targetRelation: 'enemy' }],
      tags: ['HYBRID', 'HOT', 'DEBUFF'], icon: { frame: 'seal', motif: 'star', accent: 'eye' },
    },
    {
      id: 'twin_suns_rebuke', name: 'Укор двух солнц', rarity: 'rare', cooldown: 4, target: 'enemy', projectile: 'holy',
      description: 'Два независимых удара по выбранному врагу, каждый на 1d6 + половину Силы. Каждое попадание накладывает Светлый приговор на 2 хода: Точность −3, Критический удар −2. Повторное наложение этой ауры обновляет срок.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'radiant_censure', onHitDuration: 2 }],
      tags: ['MULTIHIT', 'DEBUFF'], icon: { frame: 'arrows', motif: 'cross', accent: 'flame' },
    },
    {
      id: 'light_upon_the_edge', name: 'Свет на острие', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'holy',
      description: 'На 2 хода даёт союзнику Освящённое лезвие (Точность +2, дополнительный 1d4 к прямым ударам) и Исцеление рассвета: в начале хода лечится на 1d6 + Силу источника.',
      actions: [{ type: 'status', statusId: 'consecrated_edge', duration: 2 }, { type: 'status', statusId: 'dawn_mending', duration: 2 }],
      tags: ['BUFF', 'DAMAGE', 'HOT'], icon: { frame: 'slash', motif: 'flame', accent: 'blade' },
    },
    {
      id: 'crown_of_intercession', name: 'Венец заступничества', rarity: 'epic', cooldown: 6, target: 'ally', projectile: 'holy',
      description: 'На 3 хода даёт Божественную защиту и Дозор мученика: суммарно Защита союзника +10, входящий урон после брони −3. Носитель также уменьшает остаток прямого урона по участникам своего отряда броском 1d4.',
      actions: [{ type: 'status', statusId: 'divine_protection', duration: 3 }, { type: 'status', statusId: 'martyrs_vigil', duration: 3 }],
      tags: ['GUARD', 'ARMOR'], icon: { frame: 'orbit', motif: 'shield', accent: 'star' },
    },
    {
      id: 'fleeting_miracle', name: 'Мимолётное чудо', rarity: 'epic', cooldown: 7, target: 'lowestHealthAlly', projectile: 'holy',
      description: 'Выбранный живой союзник лечится на 3d8 + Силу и получает Бастион: полностью блокирует входящий урон до начала своего следующего хода. При автовыборе приоритет у наиболее раненого союзника.',
      actions: [{ type: 'heal', dice: '3d8', scaling: 'power' }, { type: 'status', statusId: 'bastion', duration: 1 }],
      tags: ['AUTOTARGET', 'HEAL', 'IMMUNITY'], icon: { frame: 'rays', motif: 'feather', accent: 'shield' },
    },
    {
      id: 'bells_of_reckoning', name: 'Колокола воздаяния', rarity: 'epic', cooldown: 6, target: 'allEnemies', projectile: 'holy',
      description: 'Каждому врагу — удар на 2d6 + половину Силы; попадание накладывает Светлый приговор на 2 хода (Точность −3, Критический удар −2). Заклинатель затем получает Хор милосердия на 2 хода: Сила +2, полученное реальное лечение передаёт отряду 1d6 здоровья.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', factor: .5, onHitStatusId: 'radiant_censure', onHitDuration: 2 }, { type: 'status', statusId: 'merciful_chorus', duration: 2, target: 'self' }],
      tags: ['MASS', 'DEBUFF', 'BUFF'], icon: { frame: 'burst', motif: 'flame', accent: 'eye' },
    },
    {
      id: 'shelter_of_shared_faith', name: 'Укрытие общей веры', rarity: 'epic', cooldown: 7, target: 'allAllies', projectile: 'holy',
      description: 'Заклинатель получает Клятву убежища на 3 хода, затем создаёт каждому союзнику щит на 2d4 + Силу на 3 хода. При расходе его щита бросает 1d6: на 5+ весь остаток урона поглощается без расхода ёмкости.',
      actions: [{ type: 'status', statusId: 'oath_of_sanctuary', duration: 3, target: 'self' }, { type: 'shield', dice: '2d4', scaling: 'power', duration: 3 }],
      tags: ['MASS', 'SHIELD'], icon: { frame: 'ward', motif: 'star', accent: 'rune' },
    },
  ]),
  ...skillSchool('nature', 332, [
    {
      id: 'sapwood_skin', name: 'Кожа молодой древесины', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'nature',
      description: 'Даёт союзнику Панцирь на 2 хода: каждый заряд уменьшает входящий урон после Защиты на 4. Урон, игнорирующий Защиту, обходит это уменьшение.',
      actions: [{ type: 'status', statusId: 'fortified', duration: 2 }],
      tags: ['ARMOR', 'BUFF'], icon: { frame: 'ward', motif: 'leaf', accent: 'bone' },
    },
    {
      id: 'elderberry_draught', name: 'Бузинный настой', rarity: 'common', cooldown: 3, target: 'lowestHealthAlly', projectile: 'nature',
      description: 'Выбранный союзник лечится на 1d6 + Силу и на 1 ход получает Звериное чутьё: Точность, Уклонение и следующий бросок инициативы +2. Текущая очередь не меняется. При автовыборе приоритет у наиболее раненого союзника.',
      actions: [{ type: 'heal', dice: '1d6', scaling: 'power' }, { type: 'status', statusId: 'wild_instinct', duration: 1 }],
      tags: ['AUTOTARGET', 'HEAL', 'EVASION'], icon: { frame: 'rays', motif: 'drop', accent: 'leaf' },
    },
    {
      id: 'autumn_snare', name: 'Осенний силок', rarity: 'common', cooldown: 4, target: 'randomEnemy', projectile: 'nature',
      description: 'Случайный враг получает Корневую хватку на 2 хода (Уклонение и Проворность −3) и Терновую рану на 1 ход: 1d6 урона с учётом Защиты в конце его следующего хода. Бросков попадания нет.',
      actions: [{ type: 'status', statusId: 'rootbound', duration: 2 }, { type: 'status', statusId: 'briar_wound', duration: 1 }],
      tags: ['RANDOM', 'DEBUFF', 'DOT'], icon: { frame: 'weave', motif: 'claw', accent: 'leaf' },
    },
    {
      id: 'tender_bud', name: 'Нежная почка', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'nature',
      description: 'Сначала лечит союзника на 1d4 + Силу заклинателя, затем даёт Дыхание весны на 1 ход: Сила получателя +4. Уже выполненное лечение этот бонус не усиливает.',
      actions: [{ type: 'heal', dice: '1d4', scaling: 'power' }, { type: 'status', statusId: 'spring_breath', duration: 1 }],
      tags: ['HEAL', 'BUFF'], icon: { frame: 'seal', motif: 'leaf', accent: 'drop' },
    },
    {
      id: 'reed_splinter', name: 'Тростниковая заноза', rarity: 'common', cooldown: 4, target: 'enemy', projectile: 'nature',
      description: 'Атакует выбранного врага на 2d4 + Силу, игнорируя Защиту. Щиты и полное блокирование действуют; попадание и крит требуют отдельных d20.',
      actions: [{ type: 'damage', dice: '2d4', scaling: 'power', bypassArmor: true }],
      tags: ['DAMAGE', 'PIERCE'], icon: { frame: 'slash', motif: 'leaf', accent: 'blade' },
    },
    {
      id: 'bed_of_young_ferns', name: 'Ложе молодых папоротников', rarity: 'common', cooldown: 3, target: 'self', projectile: 'nature',
      description: 'Лечится на 1d4 без прибавки Силы и получает Семя возвращения на 2 хода. В начале хода семя создаёт отдельный щит на 1d4 + Силу источника со сроком 2 хода; в ход наложения тика нет.',
      actions: [{ type: 'heal', dice: '1d4' }, { type: 'status', statusId: 'seed_of_return', duration: 2 }],
      tags: ['HEAL', 'SHIELD'], icon: { frame: 'orbit', motif: 'leaf', accent: 'feather' },
    },
    {
      id: 'nettle_footpath', name: 'Крапивная тропа', rarity: 'common', cooldown: 4, target: 'allEnemies', projectile: 'nature',
      description: 'По каждому врагу — удар на 1d4 без Силы. Попадание накладывает Корневую хватку на 1 ход: Уклонение и Проворность −3. Ходы и действия противника сохраняются.',
      actions: [{ type: 'damage', dice: '1d4', onHitStatusId: 'rootbound', onHitDuration: 1 }],
      tags: ['MASS', 'DEBUFF'], icon: { frame: 'arrows', motif: 'leaf', accent: 'fang' },
    },
    {
      id: 'summer_oak_blessing', name: 'Благословение летнего дуба', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'nature',
      description: 'Даёт союзнику Сердце дуба на 3 хода (Защита +6, следующий бросок инициативы −2) и Дикое обновление на 2 хода: в начале хода лечится на 2d4 + Силу источника. Текущая очередь остаётся прежней.',
      actions: [{ type: 'status', statusId: 'oak_heart', duration: 3 }, { type: 'status', statusId: 'wild_renewal', duration: 2 }],
      tags: ['ARMOR', 'HOT'], icon: { frame: 'ward', motif: 'rock', accent: 'cross' },
    },
    {
      id: 'sheltering_stag', name: 'Заступничество оленя', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'nature',
      description: 'Получает Терновый дозор на 2 хода: +1d4 к прямым ударам и уменьшение остатка прямого урона по отряду броском 1d4. Затем атакует врага на 2d6 + Силу и уже с дополнительным 1d4 от дозора.',
      actions: [{ type: 'status', statusId: 'thorn_guard', duration: 2, target: 'self' }, { type: 'damage', dice: '2d6', scaling: 'power' }],
      tags: ['DAMAGE', 'GUARD'], icon: { frame: 'slash', motif: 'claw', accent: 'shield' },
    },
    {
      id: 'roaming_garden', name: 'Странствующий сад', rarity: 'rare', cooldown: 5, target: 'randomAlly', projectile: 'nature',
      description: 'Случайный союзник лечится на 3d4 + Силу и получает Дикое обновление на 2 хода: в начале хода восстанавливает ещё 2d4 + Силу источника. Периодическое лечение не срабатывает в ход наложения.',
      actions: [{ type: 'heal', dice: '3d4', scaling: 'power' }, { type: 'status', statusId: 'wild_renewal', duration: 2 }],
      tags: ['RANDOM', 'HEAL', 'HOT'], icon: { frame: 'rays', motif: 'leaf', accent: 'feather' },
    },
    {
      id: 'green_arbitration', name: 'Зелёный рассуд', rarity: 'rare', cooldown: 4, target: 'any', projectile: 'nature',
      description: 'Союзник получает Семя возвращения на 3 хода: в начале хода щит 1d4 + Сила источника со сроком 2 хода. Враг получает Терновую рану на 3 хода (1d6 урона с учётом Защиты в конце хода) и Корневую хватку на 2 хода (Уклонение и Проворность −3). Прямых ударов нет.',
      actions: [{ type: 'status', statusId: 'seed_of_return', duration: 3, targetRelation: 'ally' }, { type: 'status', statusId: 'briar_wound', duration: 3, targetRelation: 'enemy' }, { type: 'status', statusId: 'rootbound', duration: 2, targetRelation: 'enemy' }],
      tags: ['HYBRID', 'SHIELD', 'DOT'], icon: { frame: 'seal', motif: 'eye', accent: 'claw' },
    },
    {
      id: 'orchards_last_fruit', name: 'Последний плод сада', rarity: 'rare', cooldown: 5, target: 'lowestHealthAlly', projectile: 'nature',
      description: 'Выбранный союзник лечится на 3d6 + Силу и получает Семя возвращения на 2 хода. В начале его хода — щит на 1d4 + Силу источника со сроком 2 хода. При автовыборе приоритет у наиболее раненого союзника.',
      actions: [{ type: 'heal', dice: '3d6', scaling: 'power' }, { type: 'status', statusId: 'seed_of_return', duration: 2 }],
      tags: ['AUTOTARGET', 'HEAL', 'SHIELD'], icon: { frame: 'orbit', motif: 'drop', accent: 'shield' },
    },
    {
      id: 'fruiting_thornfield', name: 'Плодоносящий терновник', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'nature',
      description: 'Сначала лечит весь отряд на 1d4 + Силу. Затем атакует каждого врага на 2d4 + Силу; попадание оставляет Терновую рану на 2 хода: 1d6 урона с учётом Защиты в конце хода. Лечение не зависит от попаданий.',
      actions: [{ type: 'heal', dice: '1d4', scaling: 'power', target: 'allAllies' }, { type: 'damage', dice: '2d4', scaling: 'power', onHitStatusId: 'briar_wound', onHitDuration: 2 }],
      tags: ['MASS', 'HEAL', 'DOT'], icon: { frame: 'burst', motif: 'leaf', accent: 'cross' },
    },
    {
      id: 'wardens_coppice', name: 'Перелесок хранителя', rarity: 'epic', cooldown: 6, target: 'ally', projectile: 'nature',
      description: 'Союзник получает щит на 3d6 + Силу и Терновый дозор на 3 хода. Дозор даёт дополнительный 1d4 к прямым ударам; когда по участнику отряда остаётся прямой урон после защиты, носитель уменьшает его броском 1d4.',
      actions: [{ type: 'shield', dice: '3d6', scaling: 'power', duration: 3 }, { type: 'status', statusId: 'thorn_guard', duration: 3 }],
      tags: ['SHIELD', 'GUARD', 'BUFF'], icon: { frame: 'weave', motif: 'shield', accent: 'claw' },
    },
    {
      id: 'flood_of_spring_roots', name: 'Половодье весенних корней', rarity: 'epic', cooldown: 7, target: 'allAllies', projectile: 'nature',
      description: 'Весь отряд получает Дикое обновление на 2 хода: 2d4 + Сила источника лечения в начале собственного хода. Все враги получают Корневую хватку на 2 хода: Уклонение и Проворность −3. Прямых ударов нет.',
      actions: [{ type: 'status', statusId: 'wild_renewal', duration: 2 }, { type: 'status', statusId: 'rootbound', duration: 2, target: 'allEnemies' }],
      tags: ['MASS', 'HOT', 'DEBUFF'], icon: { frame: 'arrows', motif: 'rune', accent: 'leaf' },
    },
    {
      id: 'verdict_of_the_elder_grove', name: 'Приговор старой рощи', rarity: 'epic', cooldown: 6, target: 'any', projectile: 'nature',
      description: 'Союзника лечит на 3d8 + Силу и даёт Панцирь на 3 хода (входящий урон после Защиты −4). Врагу сначала даёт Корневую хватку на 3 хода (Уклонение и Проворность −3), затем удар на 3d8 + Силу; попадание оставляет Терновую рану на 2 хода: 1d6 в конце хода с учётом Защиты.',
      actions: [{ type: 'heal', dice: '3d8', scaling: 'power', targetRelation: 'ally' }, { type: 'status', statusId: 'fortified', duration: 3, targetRelation: 'ally' }, { type: 'status', statusId: 'rootbound', duration: 3, targetRelation: 'enemy' }, { type: 'damage', dice: '3d8', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'briar_wound', onHitDuration: 2 }],
      tags: ['HYBRID', 'HEAL', 'DEBUFF', 'DOT'], icon: { frame: 'seal', motif: 'rock', accent: 'eye' },
    },
  ]),
  ...skillSchool('shadow', 348, [
    {
      id: 'dagger_behind_the_curtain', name: 'Кинжал за занавесом', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'shadow',
      description: 'Создаёт себе щит на 1d6 без Силы на 1 ход, затем атакует выбранного врага на 1d4 + Силу. Щит остаётся и при промахе.',
      actions: [{ type: 'shield', dice: '1d6', duration: 1, target: 'self' }, { type: 'damage', dice: '1d4', scaling: 'power' }],
      tags: ['SHIELD', 'DAMAGE'], icon: { frame: 'slash', motif: 'blade', accent: 'shield' },
    },
    {
      id: 'moonwax_dressing', name: 'Повязка лунного воска', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'shadow',
      description: 'Лечит союзника на 1d4 без Силы и даёт Доспех сумрака на 1 ход: Защита каждой части тела +4, Уклонение +2.',
      actions: [{ type: 'heal', dice: '1d4' }, { type: 'status', statusId: 'gloom_armor', duration: 1 }],
      tags: ['HEAL', 'ARMOR'], icon: { frame: 'ward', motif: 'moon', accent: 'cross' },
    },
    {
      id: 'blind_mans_coin', name: 'Монета слепца', rarity: 'common', cooldown: 4, target: 'randomEnemy', projectile: 'shadow',
      description: 'Случайный враг получает Тьму в глазах на 2 хода: Точность −4. Заклинатель получает Изворотливость на 1 ход: Уклонение +4. Прямого удара нет.',
      actions: [{ type: 'status', statusId: 'blackout', duration: 2 }, { type: 'status', statusId: 'evasiveness', duration: 1, target: 'self' }],
      tags: ['RANDOM', 'DEBUFF', 'EVASION'], icon: { frame: 'orbit', motif: 'eye', accent: 'rune' },
    },
    {
      id: 'stillness_of_the_novice', name: 'Неподвижность послушника', rarity: 'common', cooldown: 3, target: 'self', projectile: 'shadow',
      description: 'Терпение убийцы на 2 хода: Критический удар +6, следующий бросок инициативы −2. Уже определённая очередь не меняется; крит по-прежнему проверяется отдельным d20.',
      actions: [{ type: 'status', statusId: 'assassins_patience', duration: 2 }],
      tags: ['CRITICAL', 'TRADEOFF'], icon: { frame: 'seal', motif: 'eye', accent: 'hourglass' },
    },
    {
      id: 'black_feather_barb', name: 'Зубец чёрного пера', rarity: 'common', cooldown: 2, target: 'enemy', projectile: 'shadow',
      description: 'Удар на 2d4 без Силы. Попадание накладывает Тьму в глазах на 1 ход: Точность врага −4.',
      actions: [{ type: 'damage', dice: '2d4', onHitStatusId: 'blackout', onHitDuration: 1 }],
      tags: ['DEBUFF', 'DAMAGE'], icon: { frame: 'arrows', motif: 'feather', accent: 'eye' },
    },
    {
      id: 'balm_of_the_hidden_path', name: 'Бальзам тайной тропы', rarity: 'common', cooldown: 3, target: 'lowestHealthAlly', projectile: 'shadow',
      description: 'Выбранный живой союзник лечится на 1d8 + Силу и получает Изворотливость на 1 ход: Уклонение +4. При автовыборе приоритет у наиболее раненого союзника.',
      actions: [{ type: 'heal', dice: '1d8', scaling: 'power' }, { type: 'status', statusId: 'evasiveness', duration: 1 }],
      tags: ['AUTOTARGET', 'HEAL', 'EVASION'], icon: { frame: 'rays', motif: 'drop', accent: 'moon' },
    },
    {
      id: 'ticket_to_midnight', name: 'Пропуск в полночь', rarity: 'common', cooldown: 2, target: 'randomAlly', projectile: 'shadow',
      description: 'Случайный союзник получает Сокрытое лезвие на 1 ход: Точность +3 и дополнительный 1d4 к каждому прямому удару.',
      actions: [{ type: 'status', statusId: 'veiled_blade', duration: 1 }],
      tags: ['RANDOM', 'BUFF', 'DAMAGE'], icon: { frame: 'weave', motif: 'rune', accent: 'blade' },
    },
    {
      id: 'oath_of_two_shadows', name: 'Клятва двух теней', rarity: 'rare', cooldown: 5, target: 'any', projectile: 'shadow',
      description: 'Союзник получает Эхо тени на 2 хода: Критический удар +1; после действия с уроном бросает 1d6 и на 5+ повторяет одну базовую атаку без цепочки. Враг получает Тьму в глазах и Ночную рану на 2 хода: Точность −4, в конце хода — 1d8 урона с учётом Защиты.',
      actions: [{ type: 'status', statusId: 'shadow_echo', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'blackout', duration: 2, targetRelation: 'enemy' }, { type: 'status', statusId: 'night_wound', duration: 2, targetRelation: 'enemy' }],
      tags: ['HYBRID', 'REPEAT', 'DOT'], icon: { frame: 'seal', motif: 'moon', accent: 'wisp' },
    },
    {
      id: 'moonthread_mantle', name: 'Мантия лунных нитей', rarity: 'rare', cooldown: 4, target: 'ally', projectile: 'shadow',
      description: 'Даёт союзнику щит на 2d6 + Силу и Изворотливость на 2 хода: Уклонение +4. Естественная 20 противника продолжает гарантировать попадание.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'evasiveness', duration: 2 }],
      tags: ['SHIELD', 'EVASION'], icon: { frame: 'weave', motif: 'shield', accent: 'feather' },
    },
    {
      id: 'needle_of_the_unseen', name: 'Игла незримого', rarity: 'rare', cooldown: 5, target: 'lowestHealthEnemy', projectile: 'shadow',
      description: 'Атакует выбранного врага на 3d4 + Силу, игнорируя Защиту, но не щиты. Попадание накладывает Тьму в глазах на 2 хода: Точность −4. При автовыборе приоритет у врага с наименьшей долей здоровья.',
      actions: [{ type: 'damage', dice: '3d4', scaling: 'power', bypassArmor: true, onHitStatusId: 'blackout', onHitDuration: 2 }],
      tags: ['AUTOTARGET', 'PIERCE', 'DEBUFF'], icon: { frame: 'slash', motif: 'eye', accent: 'fang' },
    },
    {
      id: 'witness_in_the_dark', name: 'Свидетель во тьме', rarity: 'rare', cooldown: 3, target: 'randomUnit', projectile: 'shadow',
      description: 'Атакует случайного живого участника, включая союзников и себя, на 2d6 + Силу. Попадание оставляет Ночную рану на 2 хода: 1d8 урона с учётом Защиты в конце хода. Может навредить своему отряду.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', onHitStatusId: 'night_wound', onHitDuration: 2 }],
      tags: ['RANDOM', 'FRIENDLY_FIRE', 'DOT'], icon: { frame: 'burst', motif: 'eye', accent: 'skull' },
    },
    {
      id: 'muffled_procession', name: 'Безмолвная процессия', rarity: 'rare', cooldown: 5, target: 'allAllies', projectile: 'shadow',
      description: 'Отряд получает Беззвучный шаг на 2 хода: Проворность +4, следующий бросок инициативы +3; текущая очередь не меняется. Только заклинатель получает Смертоносность на 2 хода: Критический удар +5.',
      actions: [{ type: 'status', statusId: 'silent_step', duration: 2 }, { type: 'status', statusId: 'lethality', duration: 2, target: 'self' }],
      tags: ['MASS', 'ESCAPE', 'CRITICAL'], icon: { frame: 'arrows', motif: 'moon', accent: 'feather' },
    },
    {
      id: 'dance_of_the_hidden_edge', name: 'Танец скрытого острия', rarity: 'epic', cooldown: 7, target: 'enemy', projectile: 'shadow',
      description: 'Получает Сокрытое лезвие на 2 хода: Точность +3, дополнительный 1d4 к прямым ударам. Затем три независимых удара по одному врагу: каждый на 1d6 + половину Силы и уже с 1d4 от лезвия. Каждое попадание оставляет отдельную Ночную рану на 1 ход: 1d8 урона с учётом Защиты в конце следующего хода.',
      actions: [{ type: 'status', statusId: 'veiled_blade', duration: 2, target: 'self' }, { type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 3, onHitStatusId: 'night_wound', onHitDuration: 1 }],
      tags: ['MULTIHIT', 'DOT', 'BUFF'], icon: { frame: 'arrows', motif: 'fang', accent: 'rune' },
    },
    {
      id: 'dusk_shared_by_all', name: 'Сумерки на всех', rarity: 'epic', cooldown: 6, target: 'allAllies', projectile: 'shadow',
      description: 'Весь отряд получает Доспех сумрака на 2 хода: Защита +4, Уклонение +2. Все враги получают Тьму в глазах на 1 ход: Точность −4. Прямых ударов и проверок попадания нет.',
      actions: [{ type: 'status', statusId: 'gloom_armor', duration: 2 }, { type: 'status', statusId: 'blackout', duration: 1, target: 'allEnemies' }],
      tags: ['MASS', 'ARMOR', 'DEBUFF'], icon: { frame: 'ward', motif: 'eye', accent: 'moon' },
    },
    {
      id: 'black_mirror_companion', name: 'Спутник чёрного зеркала', rarity: 'epic', cooldown: 6, target: 'ally', projectile: 'shadow',
      description: 'На 3 хода даёт союзнику Изворотливость и Эхо тени: Уклонение +4, Критический удар +1. После действия с уроном — 1d6, на 5+ одна дополнительная базовая атака по той же живой цели; повтор не повторяет навык и не запускает цепочку.',
      actions: [{ type: 'status', statusId: 'evasiveness', duration: 3 }, { type: 'status', statusId: 'shadow_echo', duration: 3 }],
      tags: ['BUFF', 'EVASION', 'REPEAT'], icon: { frame: 'orbit', motif: 'crystal', accent: 'moon' },
    },
    {
      id: 'eclipse_beneath_the_ribs', name: 'Затмение под рёбрами', rarity: 'epic', cooldown: 7, target: 'enemy', projectile: 'shadow',
      description: 'Сначала получает Доспех сумрака на 2 хода (Защита +4, Уклонение +2), а врагу накладывает Ночную рану на 3 хода (1d8 урона с учётом Защиты в конце хода). Затем атакует на 2d10 + Силу без Защиты, но с учётом щитов. Обе ауры сохраняются при промахе.',
      actions: [{ type: 'status', statusId: 'gloom_armor', duration: 2, target: 'self' }, { type: 'status', statusId: 'night_wound', duration: 3 }, { type: 'damage', dice: '2d10', scaling: 'power', bypassArmor: true }],
      tags: ['ARMOR', 'DOT', 'PIERCE'], icon: { frame: 'slash', motif: 'bone', accent: 'moon' },
    },
  ]),
  ...skillSchool('arcane', 364, [
    {
      id: 'scribes_cancelled_mark', name: 'Зачёркнутый знак писца', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'arcane',
      description: 'Накладывает Разлад чар на 1 ход: Сила врага −5, Точность −2. Затем атакует на 1d4 + Силу; разлад остаётся при промахе.',
      actions: [{ type: 'status', statusId: 'arcane_disruption', duration: 1 }, { type: 'damage', dice: '1d4', scaling: 'power' }],
      tags: ['DEBUFF', 'DAMAGE'], icon: { frame: 'slash', motif: 'rune', accent: 'eye' },
    },
    {
      id: 'formula_of_the_small_buckler', name: 'Формула малого щита', rarity: 'common', cooldown: 3, target: 'self', projectile: 'arcane',
      description: 'Создаёт себе щит на 1d8 + Силу на 2 хода и получает Чародейское зрение на 1 ход: Точность +4.',
      actions: [{ type: 'shield', dice: '1d8', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'arcane_sight', duration: 1 }],
      tags: ['SHIELD', 'ACCURACY'], icon: { frame: 'ward', motif: 'eye', accent: 'rune' },
    },
    {
      id: 'surplus_spark', name: 'Избыточная искра', rarity: 'common', cooldown: 3, target: 'self', projectile: 'arcane',
      description: 'Перенасыщение на 1 ход: дополнительный 1d10 к каждому прямому удару, но Защита каждой части тела −5 и Уклонение −2. Само применение урона не наносит.',
      actions: [{ type: 'status', statusId: 'overcharge', duration: 1 }],
      tags: ['BUFF', 'TRADEOFF', 'DAMAGE'], icon: { frame: 'burst', motif: 'bolt', accent: 'crystal' },
    },
    {
      id: 'apprentices_force_rune', name: 'Силовая руна подмастерья', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'arcane',
      description: 'Руна силы на 2 хода: каждый прямой удар союзника получает дополнительный 1d8, но его Точность уменьшается на 1.',
      actions: [{ type: 'status', statusId: 'rune_of_force', duration: 2 }],
      tags: ['BUFF', 'DAMAGE', 'TRADEOFF'], icon: { frame: 'seal', motif: 'rune', accent: 'fang' },
    },
    {
      id: 'wavering_conduit', name: 'Колеблющийся проводник', rarity: 'common', cooldown: 2, target: 'randomUnit', projectile: 'arcane',
      description: 'Кубик выбирает одного живого участника. Союзнику создаёт щит на 2d4 + Силу на 2 хода. Врага атакует на 2d4 + Силу; для атаки бросаются отдельные d20 попадания и крита.',
      actions: [{ type: 'shield', dice: '2d4', scaling: 'power', duration: 2, targetRelation: 'ally' }, { type: 'damage', dice: '2d4', scaling: 'power', targetRelation: 'enemy' }],
      tags: ['RANDOM', 'HYBRID', 'SHIELD'], icon: { frame: 'orbit', motif: 'crystal', accent: 'shield' },
    },
    {
      id: 'aether_stitching', name: 'Эфирная штопка', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'arcane',
      description: 'Лечит союзника на 2d4 без Силы и даёт Эфирный барьер на 1 ход. В начале следующего хода появляется слой щита на 2d4 без Силы со сроком 1 ход; немедленного щита нет.',
      actions: [{ type: 'heal', dice: '2d4' }, { type: 'status', statusId: 'aether_barrier', duration: 1 }],
      tags: ['HEAL', 'SHIELD'], icon: { frame: 'weave', motif: 'cross', accent: 'rune' },
    },
    {
      id: 'volley_of_fractions', name: 'Залп дробей', rarity: 'common', cooldown: 2, target: 'enemy', projectile: 'arcane',
      description: 'Три независимых удара по одному врагу, каждый на 1d2 без Силы. Попадание, крит и Защита проверяются для каждого удара отдельно; серия прекращается при гибели цели.',
      actions: [{ type: 'damage', dice: '1d2', hits: 3 }],
      tags: ['MULTIHIT'], icon: { frame: 'arrows', motif: 'crystal', accent: 'rune' },
    },
    {
      id: 'mirror_aperture', name: 'Зеркальная диафрагма', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'arcane',
      description: 'Заклинатель получает Зеркальный покров на 2 хода: Уклонение +1; при расходе его щита — 1d4, на 4 ёмкость не тратится, а остаток урона поглощается. Союзнику создаёт щит на 2d6 + Силу на 2 хода и даёт Чародейское зрение на 2 хода: Точность +4.',
      actions: [{ type: 'status', statusId: 'mirror_ward', duration: 2, target: 'self' }, { type: 'shield', dice: '2d6', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'arcane_sight', duration: 2 }],
      tags: ['SHIELD', 'ACCURACY', 'BUFF'], icon: { frame: 'ward', motif: 'crystal', accent: 'feather' },
    },
    {
      id: 'living_proof', name: 'Живое доказательство', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'arcane',
      description: 'Получает Безупречную формулу на 2 хода: Точность, Критический удар и Сила +2. Затем атакует врага на 2d6 + уже усиленную Силу. Формула остаётся при промахе.',
      actions: [{ type: 'status', statusId: 'perfect_formula', duration: 2, target: 'self' }, { type: 'damage', dice: '2d6', scaling: 'power' }],
      tags: ['DAMAGE', 'BUFF', 'CRITICAL'], icon: { frame: 'rays', motif: 'star', accent: 'eye' },
    },
    {
      id: 'errant_aether_reservoir', name: 'Бродячий резервуар эфира', rarity: 'rare', cooldown: 5, target: 'randomAlly', projectile: 'arcane',
      description: 'Случайный союзник получает щит на 3d8 на 2 хода и Эфирный барьер на 2 хода: в начале хода создаётся отдельный слой щита на 2d4 со сроком 1 ход. Сила к этим щитам не добавляется.',
      actions: [{ type: 'shield', dice: '3d8', duration: 2 }, { type: 'status', statusId: 'aether_barrier', duration: 2 }],
      tags: ['RANDOM', 'SHIELD'], icon: { frame: 'orbit', motif: 'rune', accent: 'drop' },
    },
    {
      id: 'fork_of_ley_lines', name: 'Развилка силовых линий', rarity: 'rare', cooldown: 4, target: 'any', projectile: 'arcane',
      description: 'Союзник получает Средоточие чар на 2 хода: Сила +5, Критический удар +2. Враг получает Разлад чар на 3 хода: Сила −5, Точность −2. Прямого удара и проверки попадания нет.',
      actions: [{ type: 'status', statusId: 'spell_focus', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'arcane_disruption', duration: 3, targetRelation: 'enemy' }],
      tags: ['HYBRID', 'BUFF', 'DEBUFF'], icon: { frame: 'weave', motif: 'rune', accent: 'eye' },
    },
    {
      id: 'aether_boring_shard', name: 'Эфирный бурав', rarity: 'rare', cooldown: 5, target: 'lowestHealthEnemy', projectile: 'arcane',
      description: 'Выбранному врагу — удар на 3d6 без Силы, игнорирующий Защиту, но не щиты. Попадание оставляет Ожог эфира на 2 хода: в начале хода цели — 1d6 урона без Защиты. При автовыборе приоритет у врага с наименьшей долей здоровья.',
      actions: [{ type: 'damage', dice: '3d6', bypassArmor: true, onHitStatusId: 'mana_scorch', onHitDuration: 2 }],
      tags: ['AUTOTARGET', 'PIERCE', 'DOT'], icon: { frame: 'slash', motif: 'crystal', accent: 'bolt' },
    },
    {
      id: 'double_helix_of_ruin', name: 'Двойная спираль распада', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'arcane',
      description: 'По каждому врагу — два независимых удара, каждый на 1d6 + половину Силы. Каждое попадание оставляет отдельный Ожог эфира на 2 хода: 1d6 урона без Защиты в начале хода цели. Серия по погибшей цели прекращается.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'mana_scorch', onHitDuration: 2 }],
      tags: ['MASS', 'MULTIHIT', 'DOT'], icon: { frame: 'arrows', motif: 'rune', accent: 'flame' },
    },
    {
      id: 'mantle_of_higher_mathematics', name: 'Мантия высшего исчисления', rarity: 'epic', cooldown: 7, target: 'allAllies', projectile: 'arcane',
      description: 'Весь отряд получает Чародейское зрение на 3 хода (Точность +4) и Эфирный барьер на 2 хода: в начале хода — щит 2d4 без Силы со сроком 1 ход. Только заклинатель получает Руну силы на 2 хода: дополнительный 1d8 к прямым ударам, Точность −1.',
      actions: [{ type: 'status', statusId: 'arcane_sight', duration: 3 }, { type: 'status', statusId: 'aether_barrier', duration: 2 }, { type: 'status', statusId: 'rune_of_force', duration: 2, target: 'self' }],
      tags: ['MASS', 'SHIELD', 'ACCURACY', 'BUFF'], icon: { frame: 'seal', motif: 'star', accent: 'shield' },
    },
    {
      id: 'theorem_of_grace', name: 'Теорема благодати', rarity: 'epic', cooldown: 6, target: 'ally', projectile: 'arcane',
      description: 'Восстанавливает союзнику 2d6 + Силу здоровья и создаёт щит на 4d6 + Силу на 3 хода. Лечение и ёмкость щита используют отдельные броски; крит возможен только у лечения.',
      actions: [{ type: 'heal', dice: '2d6', scaling: 'power' }, { type: 'shield', dice: '4d6', scaling: 'power', duration: 3 }],
      tags: ['HEAL', 'SHIELD'], icon: { frame: 'rays', motif: 'cross', accent: 'crystal' },
    },
    {
      id: 'impossible_equation', name: 'Невозможное уравнение', rarity: 'epic', cooldown: 6, target: 'randomUnit', projectile: 'arcane',
      description: 'Кубик выбирает одного участника. Союзника лечит на 3d4 + Силу и даёт щит на 3d8 + Силу на 2 хода. Врагу сначала накладывает Сковывающий глиф на 3 хода (Проворность −2, следующий бросок инициативы −4), затем трижды атакует: по 1d8 + половине Силы. Текущая очередь не меняется.',
      actions: [{ type: 'heal', dice: '3d4', scaling: 'power', targetRelation: 'ally' }, { type: 'shield', dice: '3d8', scaling: 'power', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'binding_glyph', duration: 3, targetRelation: 'enemy' }, { type: 'damage', dice: '1d8', scaling: 'power', factor: .5, hits: 3, targetRelation: 'enemy' }],
      tags: ['RANDOM', 'HYBRID', 'HEAL', 'SHIELD', 'MULTIHIT'], icon: { frame: 'burst', motif: 'hourglass', accent: 'rune' },
    },
  ]),
];
