import { skillSchool } from './skill-catalog-builders';

/** Seventy-one authored common, rare and epic arts for five mystic schools. */
export const mysticProportionalSkills = [
  ...skillSchool('venom', 500, [
    {
      id: 'asp_oil', name: 'Масло аспида', rarity: 'common', cooldown: 3, target: 'self', projectile: 'poison',
      description: 'На 2 хода получает Ядовитое покрытие: отдельный дополнительный 1d6 к каждому прямому удару. Периодический яд от покрытия не накладывается.',
      actions: [{ type: 'status', statusId: 'venom_coating', duration: 2 }],
      tags: ['BUFF', 'DAMAGE'], icon: { frame: 'slash', motif: 'drop', accent: 'fang' },
    },
    {
      id: 'mushroom_cowl', name: 'Клобук грибника', rarity: 'common', cooldown: 4, target: 'self', projectile: 'poison',
      description: 'Споровая мантия на 3 хода: в начале собственного хода создаёт слой щита на 1d4 + Силу со сроком 1 ход. В ход наложения слой не создаётся.',
      actions: [{ type: 'status', statusId: 'spore_mantle', duration: 3 }],
      tags: ['SHIELD'], icon: { frame: 'ward', motif: 'leaf', accent: 'drop' },
    },
    {
      id: 'wormwood_poultice', name: 'Полынная припарка', rarity: 'common', cooldown: 4, target: 'ally', projectile: 'poison',
      description: 'Даёт союзнику Горький бальзам на 3 хода: в начале его хода восстанавливает 1d6 + Силу источника. Немедленного лечения и тика в ход наложения нет.',
      actions: [{ type: 'status', statusId: 'bitter_balm', duration: 3 }],
      tags: ['HOT'], icon: { frame: 'weave', motif: 'leaf', accent: 'cross' },
    },
    {
      id: 'fevered_needle', name: 'Игла лихорадки', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'poison',
      description: 'Без броска попадания накладывает Ядовитую лихорадку на 2 хода: Сила −4, следующий бросок инициативы −2. Уже определённая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'venom_fever', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'rays', motif: 'fang', accent: 'hourglass' },
    },
    {
      id: 'bile_vapor', name: 'Желчный пар', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'poison',
      description: 'Тошнотворная дымка на 2 хода: Критический удар и Проворность врага −3. Попадание не проверяется; навык не отнимает действие.',
      actions: [{ type: 'status', statusId: 'nauseating_haze', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'burst', motif: 'skull', accent: 'drop' },
    },
    {
      id: 'viper_eye_salve', name: 'Мазь змеиного взора', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'poison',
      description: 'На 2 хода даёт союзнику Взгляд змея: Точность +2, Критический удар +3.',
      actions: [{ type: 'status', statusId: 'serpent_focus', duration: 2 }],
      tags: ['BUFF', 'CRITICAL'], icon: { frame: 'seal', motif: 'eye', accent: 'fang' },
    },
    {
      id: 'stray_plague_spine', name: 'Блуждающая чумная игла', rarity: 'common', cooldown: 4, target: 'randomEnemy', projectile: 'poison',
      description: 'Кубик выбирает врага для удара на 1d6 + Силу без Защиты. Попадание оставляет Гибельное дыхание на 2 хода: в начале хода — 1d8 + плоский бонус урона источника без Защиты. В ход наложения тика нет.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', bypassArmor: true, onHitStatusId: 'virulent_breath', onHitDuration: 2 }],
      tags: ['RANDOM', 'PIERCE', 'DOT'], icon: { frame: 'arrows', motif: 'fang', accent: 'bone' },
    },
    {
      id: 'venomers_choice', name: 'Выбор отравителя', rarity: 'rare', cooldown: 5, target: 'any', projectile: 'poison',
      description: 'Союзнику создаёт щит на 2d6 + Силу на 3 хода. Врага атакует на 2d6 + Силу; попадание накладывает Ядовитую коррозию на 2 хода: Защита −3, в конце хода — 1d4 + плоский бонус урона источника с учётом Защиты. В ход наложения тика нет.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 3, targetRelation: 'ally' }, { type: 'damage', dice: '2d6', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'toxic_corrosion', onHitDuration: 2 }],
      tags: ['HYBRID', 'SHIELD', 'DOT'], icon: { frame: 'weave', motif: 'fang', accent: 'shield' },
    },
    {
      id: 'bitter_camp_kettle', name: 'Горький походный котёл', rarity: 'rare', cooldown: 6, target: 'allAllies', projectile: 'poison',
      description: 'Весь отряд получает Горький бальзам на 2 хода: в начале собственного хода каждый носитель лечится на 1d6 + Силу источника. В ход наложения тика нет.',
      actions: [{ type: 'status', statusId: 'bitter_balm', duration: 2 }],
      tags: ['MASS', 'HOT'], icon: { frame: 'orbit', motif: 'leaf', accent: 'flame' },
    },
    {
      id: 'serpents_molt', name: 'Змеиная линька', rarity: 'rare', cooldown: 5, target: 'self', projectile: 'poison',
      description: 'На 3 хода получает Змеиный голод и Споровую мантию: Защита −2; после прямого урона здоровью врага лечится на 1d6, не больше нанесённого урона. В начале хода создаёт слой щита на 1d4 + Силу со сроком 1 ход; в ход наложения тика нет.',
      actions: [{ type: 'status', statusId: 'venom_hunger', duration: 3 }, { type: 'status', statusId: 'spore_mantle', duration: 3 }],
      tags: ['VAMPIRISM', 'SHIELD', 'TRADEOFF'], icon: { frame: 'ward', motif: 'fang', accent: 'leaf' },
    },
    {
      id: 'acid_notch', name: 'Кислотная зарубка', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'poison',
      description: 'Сначала накладывает Ядовитую коррозию на 3 хода: Защита −3, в конце хода — 1d4 + плоский бонус урона источника с учётом Защиты. Затем дважды атакует на 1d4 + половину Силы; у каждого удара отдельные попадание и крит. Коррозия остаётся при промахах, в ход наложения не тикает.',
      actions: [{ type: 'status', statusId: 'toxic_corrosion', duration: 3 }, { type: 'damage', dice: '1d4', scaling: 'power', factor: .5, hits: 2 }],
      tags: ['MULTIHIT', 'DEBUFF', 'DOT'], icon: { frame: 'slash', motif: 'blade', accent: 'drop' },
    },
    {
      id: 'lot_of_green_fangs', name: 'Жребий зелёных клыков', rarity: 'rare', cooldown: 5, target: 'randomAlly', projectile: 'poison',
      description: 'Один случайный союзник на 3 хода получает Взгляд змея и Ядовитое покрытие: Точность +2, Критический удар +3 и отдельный 1d6 к каждому прямому удару. Все усиления достаются одной цели.',
      actions: [{ type: 'status', statusId: 'serpent_focus', duration: 3 }, { type: 'status', statusId: 'venom_coating', duration: 3 }],
      tags: ['RANDOM', 'BUFF', 'CRITICAL'], icon: { frame: 'rays', motif: 'fang', accent: 'star' },
    },
    {
      id: 'plaguekeepers_feast', name: 'Пир хранителя чумы', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'poison',
      description: 'Себе даёт Змеиный голод на 3 хода: Защита −2; после прямого урона здоровью врага лечится на 1d6, не больше нанесённого урона. Каждого врага атакует на 1d6 + половину Силы. Попадание даёт Гибельное дыхание на 2 хода: в начале хода — 1d8 + плоский бонус урона источника без Защиты; в ход наложения тика нет.',
      actions: [{ type: 'status', statusId: 'venom_hunger', duration: 3, target: 'self' }, { type: 'damage', dice: '1d6', scaling: 'power', factor: .5, onHitStatusId: 'virulent_breath', onHitDuration: 2 }],
      tags: ['MASS', 'VAMPIRISM', 'DOT'], icon: { frame: 'burst', motif: 'skull', accent: 'fang' },
    },
    {
      id: 'scales_of_the_brood', name: 'Чешуя выводка', rarity: 'epic', cooldown: 7, target: 'allAllies', projectile: 'poison',
      description: 'Каждому союзнику создаёт щит на 2d6 + Силу на 3 хода и даёт Взгляд змея на 3 хода: Точность +2, Критический удар +3. Кубики ёмкости бросаются отдельно для каждого щита.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 3 }, { type: 'status', statusId: 'serpent_focus', duration: 3 }],
      tags: ['MASS', 'SHIELD', 'CRITICAL'], icon: { frame: 'ward', motif: 'fang', accent: 'eye' },
    },
    {
      id: 'apothecarys_final_recipe', name: 'Последний рецепт аптекаря', rarity: 'epic', cooldown: 7, target: 'any', projectile: 'poison',
      description: 'Союзнику на 4 хода даёт Горький бальзам и Споровую мантию: в начале хода лечит на 1d6 + Силу источника и создаёт слой щита на 1d4 + Силу источника со сроком 1 ход. Врагу на 3 хода — Ядовитую лихорадку (Сила −4, следующий бросок инициативы −2) и Гибельное дыхание (в начале хода 1d8 + плоский бонус урона источника без Защиты). Текущая очередь не меняется; в ход наложения тиков нет.',
      actions: [{ type: 'status', statusId: 'bitter_balm', duration: 4, targetRelation: 'ally' }, { type: 'status', statusId: 'spore_mantle', duration: 4, targetRelation: 'ally' }, { type: 'status', statusId: 'venom_fever', duration: 3, targetRelation: 'enemy' }, { type: 'status', statusId: 'virulent_breath', duration: 3, targetRelation: 'enemy' }],
      tags: ['HYBRID', 'HOT', 'SHIELD', 'DOT'], icon: { frame: 'seal', motif: 'drop', accent: 'skull' },
    },
  ]),
  ...skillSchool('spirit', 515, [
    {
      id: 'ancestor_at_the_shoulder', name: 'Предок за плечом', rarity: 'common', cooldown: 4, target: 'ally', projectile: 'bone',
      description: 'Даёт союзнику Дозор предков на 2 хода. Пока он жив и в бою, перед оставшимся после защиты и блокирования прямым уроном участнику его отряда бросает 1d6 и уменьшает этот урон, вплоть до нуля.',
      actions: [{ type: 'status', statusId: 'ancestral_guard', duration: 2 }],
      tags: ['PARTY_GUARD'], icon: { frame: 'ward', motif: 'wisp', accent: 'shield' },
    },
    {
      id: 'slip_through_the_shroud', name: 'Шаг сквозь саван', rarity: 'common', cooldown: 3, target: 'self', projectile: 'bone',
      description: 'Призрачный шаг на 3 хода: Уклонение +4, Защита каждой части тела −3. Не даёт неуязвимости или дополнительного перемещения.',
      actions: [{ type: 'status', statusId: 'ghost_step', duration: 3 }],
      tags: ['EVASION', 'TRADEOFF'], icon: { frame: 'arrows', motif: 'wisp', accent: 'feather' },
    },
    {
      id: 'name_on_the_gravestone', name: 'Имя на надгробии', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'bone',
      description: 'Без броска попадания накладывает Погребальный плач на 3 хода: Точность и Критический удар врага −2.',
      actions: [{ type: 'status', statusId: 'funeral_lament', duration: 3 }],
      tags: ['DEBUFF'], icon: { frame: 'seal', motif: 'skull', accent: 'rune' },
    },
    {
      id: 'quiet_requiem', name: 'Тихий реквием', rarity: 'common', cooldown: 4, target: 'ally', projectile: 'bone',
      description: 'Заживление души на 2 хода: в конце собственного хода союзник лечится на 2d4 + Силу источника. В ход наложения тика нет; погибших не возвращает.',
      actions: [{ type: 'status', statusId: 'soul_mending', duration: 2 }],
      tags: ['HOT'], icon: { frame: 'weave', motif: 'wisp', accent: 'cross' },
    },
    {
      id: 'debt_to_the_departed', name: 'Долг перед ушедшими', rarity: 'common', cooldown: 4, target: 'enemy', projectile: 'bone',
      description: 'Без броска попадания даёт врагу Бледное возмездие на 2 хода: в конце хода — 1d6 + плоский бонус урона источника без Защиты. В ход наложения тика нет.',
      actions: [{ type: 'status', statusId: 'pale_rebuke', duration: 2 }],
      tags: ['DOT'], icon: { frame: 'rays', motif: 'skull', accent: 'bone' },
    },
    {
      id: 'wick_of_memory', name: 'Фитиль памяти', rarity: 'common', cooldown: 3, target: 'self', projectile: 'bone',
      description: 'Получает Фонарь души на 3 хода: Сила +5, следующий бросок инициативы +1. Уже определённая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'soul_lantern', duration: 3 }],
      tags: ['BUFF'], icon: { frame: 'orbit', motif: 'wisp', accent: 'flame' },
    },
    {
      id: 'wayward_bone_charm', name: 'Сбившийся костяной оберег', rarity: 'common', cooldown: 3, target: 'randomAlly', projectile: 'bone',
      description: 'Кубик выбирает одного живого союзника, включая заклинателя. Создаёт на нём щит на 2d6 + Силу на 2 его хода.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 2 }],
      tags: ['RANDOM', 'SHIELD'], icon: { frame: 'burst', motif: 'bone', accent: 'shield' },
    },
    {
      id: 'relic_for_the_living', name: 'Реликвия для живого', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'bone',
      description: 'Лечит союзника на 2d6 + Силу и даёт ему Завет оссуария на 3 хода: Защита +2. Когда щит, созданный этим союзником, должен тратить ёмкость, он бросает 1d8: на 6+ поглощает весь остаток удара без расхода ёмкости, пока в строю. На чужие щиты у союзника это правило не действует.',
      actions: [{ type: 'heal', dice: '2d6', scaling: 'power' }, { type: 'status', statusId: 'ossuary_pact', duration: 3 }],
      tags: ['HEAL', 'PRESERVE', 'ARMOR'], icon: { frame: 'seal', motif: 'bone', accent: 'cross' },
    },
    {
      id: 'knocking_from_the_crypt', name: 'Стук из склепа', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'bone',
      description: 'Два независимых удара по выбранному врагу, каждый на 1d6 + половину Силы. Попадание накладывает Погребальный плач на 2 хода: Точность и Критический удар −2. Второе попадание обновляет срок, не удваивая штраф.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'funeral_lament', onHitDuration: 2 }],
      tags: ['MULTIHIT', 'DEBUFF'], icon: { frame: 'arrows', motif: 'bone', accent: 'skull' },
    },
    {
      id: 'answer_of_the_echo', name: 'Ответ эха', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'bone',
      description: 'Сначала получает Эхо духа на 2 хода: Сила +1; после действия с уроном бросает 1d6, на 5+ повторяет базовую атаку по той же живой цели без цепочки повторов. Затем атакует выбранного врага на 2d4 + Силу. Эхо может сработать уже после этого действия.',
      actions: [{ type: 'status', statusId: 'spirit_echo', duration: 2, target: 'self' }, { type: 'damage', dice: '2d4', scaling: 'power' }],
      tags: ['REPEAT', 'DAMAGE'], icon: { frame: 'slash', motif: 'wisp', accent: 'blade' },
    },
    {
      id: 'chosen_of_the_ossuary', name: 'Избранник костехранилища', rarity: 'rare', cooldown: 6, target: 'randomAlly', projectile: 'bone',
      description: 'Случайный союзник получает Костяной смерч на 3 хода: в начале хода — слой щита на 1d8 со сроком 2 хода; в ход наложения тика нет. Также получает Дозор предков на 2 хода: перед оставшимся прямым уроном по отряду уменьшает его броском 1d6, пока жив и в бою.',
      actions: [{ type: 'status', statusId: 'bone_cyclone', duration: 3 }, { type: 'status', statusId: 'ancestral_guard', duration: 2 }],
      tags: ['RANDOM', 'SHIELD', 'PARTY_GUARD'], icon: { frame: 'orbit', motif: 'skull', accent: 'shield' },
    },
    {
      id: 'lament_and_lantern', name: 'Плач и светоч', rarity: 'rare', cooldown: 6, target: 'allEnemies', projectile: 'bone',
      description: 'Накладывает на всех врагов Погребальный плач на 2 хода: Точность и Критический удар −2. Затем один раз лечит себя на 2d6 + Силу.',
      actions: [{ type: 'status', statusId: 'funeral_lament', duration: 2 }, { type: 'heal', dice: '2d6', scaling: 'power', target: 'self' }],
      tags: ['MASS', 'DEBUFF', 'HEAL'], icon: { frame: 'rays', motif: 'wisp', accent: 'skull' },
    },
    {
      id: 'procession_under_white_veils', name: 'Шествие под белыми вуалями', rarity: 'epic', cooldown: 7, target: 'allAllies', projectile: 'bone',
      description: 'Весь отряд получает Последнее тепло на 3 хода: в начале собственного хода лечится на 1d12 без Силы; в ход наложения тика нет. На 2 хода каждый союзник получает Призрачный шаг: Уклонение +4, Защита каждой части тела −3.',
      actions: [{ type: 'status', statusId: 'last_warmth', duration: 3 }, { type: 'status', statusId: 'ghost_step', duration: 2 }],
      tags: ['MASS', 'HOT', 'EVASION', 'TRADEOFF'], icon: { frame: 'weave', motif: 'wisp', accent: 'feather' },
    },
    {
      id: 'ossuary_spear', name: 'Копьё костяного престола', rarity: 'epic', cooldown: 7, target: 'enemy', projectile: 'bone',
      description: 'Атакует выбранного врага на 4d6 + Силу без Защиты. Попадание оставляет Бледное возмездие на 3 хода: в конце хода 1d6 + плоский бонус урона источника без Защиты, кроме хода наложения. Затем создаёт себе щит на 2d6 + Силу на 2 хода, даже если удар промахнулся.',
      actions: [{ type: 'damage', dice: '4d6', scaling: 'power', bypassArmor: true, onHitStatusId: 'pale_rebuke', onHitDuration: 3 }, { type: 'shield', dice: '2d6', scaling: 'power', duration: 2, target: 'self' }],
      tags: ['PIERCE', 'DOT', 'SHIELD'], icon: { frame: 'slash', motif: 'bone', accent: 'rune' },
    },
    {
      id: 'vow_at_the_silent_gate', name: 'Обет у безмолвных врат', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'bone',
      description: 'Всем врагам даёт Бледное возмездие на 2 хода: в конце хода 1d6 + плоский бонус урона источника без Защиты. Себе на 3 хода даёт Заживление души (2d4 + Сила в конце хода) и Дозор предков: бросок 1d6 уменьшает оставшийся прямой урон по отряду, пока носитель в строю. В ход наложения периодические эффекты не срабатывают.',
      actions: [{ type: 'status', statusId: 'pale_rebuke', duration: 2 }, { type: 'status', statusId: 'soul_mending', duration: 3, target: 'self' }, { type: 'status', statusId: 'ancestral_guard', duration: 3, target: 'self' }],
      tags: ['MASS', 'DOT', 'HOT', 'PARTY_GUARD'], icon: { frame: 'ward', motif: 'skull', accent: 'cross' },
    },
  ]),
  ...skillSchool('time', 530, [
    {
      id: 'exit_between_heartbeats', name: 'Выход между ударами сердца', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'arcane',
      description: 'Даёт союзнику Последнее мгновение на 2 хода: Проворность для побега +6, Уклонение +1. Само действие побега не выполняется.',
      actions: [{ type: 'status', statusId: 'last_instant', duration: 2 }],
      tags: ['ESCAPE', 'EVASION'], icon: { frame: 'arrows', motif: 'hourglass', accent: 'feather' },
    },
    {
      id: 'leaden_pendulum', name: 'Свинцовый маятник', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'arcane',
      description: 'Накладывает Вязкое время на 3 хода: Точность −1, следующий бросок инициативы −5. Текущая очередь остаётся прежней, действия не пропускаются.',
      actions: [{ type: 'status', statusId: 'temporal_drag', duration: 3 }],
      tags: ['DEBUFF'], icon: { frame: 'seal', motif: 'hourglass', accent: 'rock' },
    },
    {
      id: 'glass_second', name: 'Стеклянная секунда', rarity: 'common', cooldown: 4, target: 'ally', projectile: 'arcane',
      description: 'Застывший барьер на 2 хода: в конце собственного хода союзник получает слой щита на 1d6 со сроком 2 хода. В ход наложения слой не создаётся; Сила к ёмкости не прибавляется.',
      actions: [{ type: 'status', statusId: 'suspended_barrier', duration: 2 }],
      tags: ['SHIELD'], icon: { frame: 'ward', motif: 'hourglass', accent: 'crystal' },
    },
    {
      id: 'tie_the_hour', name: 'Завязать час узлом', rarity: 'common', cooldown: 4, target: 'self', projectile: 'arcane',
      description: 'Обновлённая нить на 3 хода: Сила +1. После тика наложенного носителем периодического лечения с конечным сроком бросает 1d4: на 4 продлевает этот заряд на 1 ход, пока носитель в строю. Обычное уменьшение срока в конце хода сохраняется.',
      actions: [{ type: 'status', statusId: 'renewed_thread', duration: 3 }],
      tags: ['PRESERVE', 'BUFF'], icon: { frame: 'weave', motif: 'hourglass', accent: 'rune' },
    },
    {
      id: 'dust_of_tomorrow', name: 'Пыль завтрашнего дня', rarity: 'common', cooldown: 4, target: 'enemy', projectile: 'arcane',
      description: 'Без броска попадания накладывает Эрозию мгновений на 2 хода: в начале хода врага — 1d6 + плоский бонус урона источника без Защиты. В ход наложения тика нет.',
      actions: [{ type: 'status', statusId: 'chronal_erosion', duration: 2 }],
      tags: ['DOT'], icon: { frame: 'burst', motif: 'hourglass', accent: 'drop' },
    },
    {
      id: 'count_the_breath', name: 'Отсчитать вдох', rarity: 'common', cooldown: 3, target: 'self', projectile: 'arcane',
      description: 'Выверенный удар на 2 хода: Точность +5, следующий бросок инициативы −3. Уже определённая очередь не перестраивается.',
      actions: [{ type: 'status', statusId: 'measured_strike', duration: 2 }],
      tags: ['BUFF', 'TRADEOFF'], icon: { frame: 'rays', motif: 'hourglass', accent: 'eye' },
    },
    {
      id: 'tick_and_tock', name: 'Тик и так', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'arcane',
      description: 'Два удара по одному врагу, каждый на 1d4 + половину Силы, с отдельными d20 попадания и крита. Попадание даёт Вязкое время на 1 ход: Точность −1, следующий бросок инициативы −5. Текущая очередь не меняется; повторное попадание обновляет срок, после гибели цели серия прекращается.',
      actions: [{ type: 'damage', dice: '1d4', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'temporal_drag', onHitDuration: 1 }],
      tags: ['MULTIHIT', 'DEBUFF'], icon: { frame: 'arrows', motif: 'hourglass', accent: 'blade' },
    },
    {
      id: 'borrowed_threshold', name: 'Заимствованный порог', rarity: 'rare', cooldown: 5, target: 'any', projectile: 'arcane',
      description: 'Союзнику создаёт щит на 2d6 + Силу на 2 хода и даёт Последнее мгновение на 2 хода: Проворность +6, Уклонение +1. Врага атакует на 2d6 + Силу без Защиты; попадание даёт Вязкое время на 2 хода: Точность −1, следующий бросок инициативы −5. Текущая очередь не меняется.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'last_instant', duration: 2, targetRelation: 'ally' }, { type: 'damage', dice: '2d6', scaling: 'power', bypassArmor: true, targetRelation: 'enemy', onHitStatusId: 'temporal_drag', onHitDuration: 2 }],
      tags: ['HYBRID', 'SHIELD', 'ESCAPE', 'PIERCE'], icon: { frame: 'weave', motif: 'hourglass', accent: 'shield' },
    },
    {
      id: 'sands_under_the_cloak', name: 'Пески под плащом', rarity: 'rare', cooldown: 6, target: 'allAllies', projectile: 'arcane',
      description: 'Всем союзникам даёт Пески восстановления на 2 хода: в конце собственного хода — лечение на 1d6 + Силу источника, кроме хода наложения. Заклинатель получает Ускользающую секунду на 2 хода: Уклонение +5, Критический удар −2.',
      actions: [{ type: 'status', statusId: 'hourglass_mending', duration: 2 }, { type: 'status', statusId: 'fading_second', duration: 2, target: 'self' }],
      tags: ['MASS', 'HOT', 'EVASION'], icon: { frame: 'orbit', motif: 'hourglass', accent: 'cross' },
    },
    {
      id: 'weight_of_a_minute', name: 'Вес одной минуты', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'arcane',
      description: 'Сначала даёт врагу Вязкое время на 2 хода: Точность −1, следующий бросок инициативы −5; текущая очередь не меняется. Затем атакует на 3d4 + Силу. Вязкое время остаётся при промахе.',
      actions: [{ type: 'status', statusId: 'temporal_drag', duration: 2 }, { type: 'damage', dice: '3d4', scaling: 'power' }],
      tags: ['DAMAGE', 'DEBUFF'], icon: { frame: 'slash', motif: 'hourglass', accent: 'rock' },
    },
    {
      id: 'breath_returned_in_time', name: 'Вовремя возвращённый вздох', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'arcane',
      description: 'Лечит союзника на 2d8 + Силу. На 2 хода даёт Заимствованный миг: Проворность +2; после действия с уроном носитель бросает 1d4, на 4 повторяет базовую атаку по той же живой цели без цепочки повторов.',
      actions: [{ type: 'heal', dice: '2d8', scaling: 'power' }, { type: 'status', statusId: 'borrowed_moment', duration: 2 }],
      tags: ['HEAL', 'REPEAT'], icon: { frame: 'rays', motif: 'hourglass', accent: 'wisp' },
    },
    {
      id: 'private_hour', name: 'Час для себя', rarity: 'rare', cooldown: 6, target: 'self', projectile: 'arcane',
      description: 'На 3 хода получает Обновлённую нить (Сила +1; после своего тика лечения 1d4, на 4 продление заряда на ход), Застывший барьер и Пески восстановления. В конце хода создаёт слой щита на 1d6 со сроком 2 хода и лечится на 1d6 + Силу. В ход наложения тиков нет; обычное уменьшение срока сохраняется.',
      actions: [{ type: 'status', statusId: 'renewed_thread', duration: 3 }, { type: 'status', statusId: 'suspended_barrier', duration: 3 }, { type: 'status', statusId: 'hourglass_mending', duration: 3 }],
      tags: ['HOT', 'SHIELD', 'PRESERVE'], icon: { frame: 'seal', motif: 'hourglass', accent: 'moon' },
    },
    {
      id: 'the_watchmakers_siege', name: 'Осада часовщика', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'arcane',
      description: 'Всем врагам даёт Эрозию мгновений на 3 хода: в начале хода — 1d6 + плоский бонус урона источника без Защиты. Себе даёт Застывший барьер на 3 хода: в конце хода создаёт слой щита на 1d6 со сроком 2 хода. В ход наложения периодические действия не срабатывают.',
      actions: [{ type: 'status', statusId: 'chronal_erosion', duration: 3 }, { type: 'status', statusId: 'suspended_barrier', duration: 3, target: 'self' }],
      tags: ['MASS', 'DOT', 'SHIELD'], icon: { frame: 'ward', motif: 'hourglass', accent: 'skull' },
    },
    {
      id: 'heir_to_the_extra_second', name: 'Наследник лишней секунды', rarity: 'epic', cooldown: 7, target: 'randomAlly', projectile: 'arcane',
      description: 'Один случайный союзник получает щит на 3d6 + Силу на 3 хода, Выверенный удар и Заимствованный миг на 3 хода: Точность +5, Проворность +2, следующий бросок инициативы −3. После действия с уроном бросает 1d4, на 4 повторяет базовую атаку по той же живой цели без цепочки повторов. Текущая очередь не меняется.',
      actions: [{ type: 'shield', dice: '3d6', scaling: 'power', duration: 3 }, { type: 'status', statusId: 'measured_strike', duration: 3 }, { type: 'status', statusId: 'borrowed_moment', duration: 3 }],
      tags: ['RANDOM', 'SHIELD', 'REPEAT'], icon: { frame: 'orbit', motif: 'hourglass', accent: 'star' },
    },
    {
      id: 'coin_of_unlived_hours', name: 'Монета непрожитых часов', rarity: 'epic', cooldown: 6, target: 'randomUnit', projectile: 'arcane',
      description: 'Кубик выбирает одного живого участника. Союзника лечит на 3d8 + Силу и даёт Последнее мгновение на 3 хода: Проворность +6, Уклонение +1. Врага атакует на 3d8 + Силу; попадание оставляет Эрозию мгновений на 3 хода: в начале хода 1d6 + плоский бонус урона источника без Защиты, кроме хода наложения.',
      actions: [{ type: 'heal', dice: '3d8', scaling: 'power', targetRelation: 'ally' }, { type: 'status', statusId: 'last_instant', duration: 3, targetRelation: 'ally' }, { type: 'damage', dice: '3d8', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'chronal_erosion', onHitDuration: 3 }],
      tags: ['RANDOM', 'HYBRID', 'HEAL', 'DOT'], icon: { frame: 'burst', motif: 'hourglass', accent: 'rune' },
    },
  ]),
  ...skillSchool('war', 545, [
    {
      id: 'red_mist_breath', name: 'Вдох багровой мглы', rarity: 'common', cooldown: 3, target: 'self', projectile: 'arrow',
      description: 'На 2 хода получает Ярость: Критический удар +5, Точность −3. Естественная 1 на попадание по-прежнему означает промах.',
      actions: [{ type: 'status', statusId: 'rage', duration: 2 }],
      tags: ['CRITICAL', 'TRADEOFF'], icon: { frame: 'burst', motif: 'claw', accent: 'flame' },
    },
    {
      id: 'drummers_cadence', name: 'Ритм барабанщика', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'arrow',
      description: 'Боевой транс на 2 хода: Точность союзника +2, броски урона +3, Уклонение −2.',
      actions: [{ type: 'status', statusId: 'battle_trance', duration: 2 }],
      tags: ['BUFF', 'TRADEOFF'], icon: { frame: 'rays', motif: 'shield', accent: 'claw' },
    },
    {
      id: 'break_the_stance', name: 'Сбить стойку', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'arrow',
      description: 'Без броска попадания накладывает Боевое истощение на 2 хода: броски урона −3, Уклонение −2, следующий бросок инициативы −2. Уже определённая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'battle_fatigue', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'slash', motif: 'claw', accent: 'shield' },
    },
    {
      id: 'duelists_salute', name: 'Салют дуэлянта', rarity: 'common', cooldown: 3, target: 'self', projectile: 'arrow',
      description: 'На 2 хода получает Метку дуэлянта: Точность и Критический удар +3.',
      actions: [{ type: 'status', statusId: 'duelists_mark', duration: 2 }],
      tags: ['BUFF', 'CRITICAL'], icon: { frame: 'seal', motif: 'blade', accent: 'eye' },
    },
    {
      id: 'blindside_volley', name: 'Залп с фланга', rarity: 'common', cooldown: 3, target: 'randomEnemy', projectile: 'arrow',
      description: 'Кубик выбирает одного врага для двух ударов по 1d4 + половине Силы. У каждого удара отдельные попадание и крит. Цель одна на весь залп, после её гибели удары не перенаправляются.',
      actions: [{ type: 'damage', dice: '1d4', scaling: 'power', factor: .5, hits: 2 }],
      tags: ['RANDOM', 'MULTIHIT'], icon: { frame: 'arrows', motif: 'blade', accent: 'feather' },
    },
    {
      id: 'catch_the_fallen_banner', name: 'Подхватить павшее знамя', rarity: 'common', cooldown: 4, target: 'randomAlly', projectile: 'arrow',
      description: 'Случайный живой союзник получает Знамя сплочения на 2 хода: Сила +2; перед оставшимся после защиты и блокирования прямым уроном по отряду бросает 1d4 и уменьшает этот урон, пока носитель в строю. Погибших не возвращает.',
      actions: [{ type: 'status', statusId: 'rallying_standard', duration: 2 }],
      tags: ['RANDOM', 'PARTY_GUARD'], icon: { frame: 'ward', motif: 'shield', accent: 'rune' },
    },
    {
      id: 'covered_lunge', name: 'Выпад под прикрытием', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'arrow',
      description: 'Сначала создаёт себе щит на 2d6 + Силу на 2 хода. Затем атакует выбранного врага на 2d6 + Силу; промах не отменяет уже созданный щит.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 2, target: 'self' }, { type: 'damage', dice: '2d6', scaling: 'power' }],
      tags: ['SHIELD', 'DAMAGE'], icon: { frame: 'slash', motif: 'shield', accent: 'blade' },
    },
    {
      id: 'field_captains_order', name: 'Приказ полевого капитана', rarity: 'rare', cooldown: 5, target: 'any', projectile: 'arrow',
      description: 'Союзника лечит на 2d6 + Силу и даёт Авангард на 3 хода: Защита +3, следующий бросок инициативы +3. Врагу сначала даёт Боевое истощение на 3 хода (броски урона −3, Уклонение −2, следующая инициатива −2), затем атакует на 2d6 + Силу. Истощение остаётся при промахе; текущая очередь не меняется.',
      actions: [{ type: 'heal', dice: '2d6', scaling: 'power', targetRelation: 'ally' }, { type: 'status', statusId: 'vanguard', duration: 3, targetRelation: 'ally' }, { type: 'status', statusId: 'battle_fatigue', duration: 3, targetRelation: 'enemy' }, { type: 'damage', dice: '2d6', scaling: 'power', targetRelation: 'enemy' }],
      tags: ['HYBRID', 'HEAL', 'DEBUFF'], icon: { frame: 'weave', motif: 'shield', accent: 'cross' },
    },
    {
      id: 'executioners_red_vow', name: 'Красный обет палача', rarity: 'rare', cooldown: 5, target: 'self', projectile: 'arrow',
      description: 'Получает Рвение палача на 3 хода: Критический удар +4, дополнительный 1d6 к прямым ударам, Сила −3. На 2 хода получает Ярость: ещё +5 к Критическому удару и Точность −3. Числовые бонусы складываются.',
      actions: [{ type: 'status', statusId: 'executioners_zeal', duration: 3 }, { type: 'status', statusId: 'rage', duration: 2 }],
      tags: ['CRITICAL', 'DAMAGE', 'TRADEOFF'], icon: { frame: 'seal', motif: 'blade', accent: 'claw' },
    },
    {
      id: 'school_of_the_first_blade', name: 'Школа первого клинка', rarity: 'rare', cooldown: 6, target: 'allAllies', projectile: 'arrow',
      description: 'На 2 хода весь отряд получает Метку дуэлянта: Точность и Критический удар +3. Попадание и критический удар продолжают проверяться отдельными d20.',
      actions: [{ type: 'status', statusId: 'duelists_mark', duration: 2 }],
      tags: ['MASS', 'BUFF', 'CRITICAL'], icon: { frame: 'rays', motif: 'blade', accent: 'star' },
    },
    {
      id: 'rampart_sweep', name: 'Взмах над бруствером', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'arrow',
      description: 'Каждому врагу — удар на 2d4 + половину Силы. Попадание даёт Боевое истощение на 3 хода: броски урона −3, Уклонение −2, следующий бросок инициативы −2; текущая очередь не меняется. Затем один раз создаёт себе щит на 3d6 + Силу на 2 хода, независимо от попаданий.',
      actions: [{ type: 'damage', dice: '2d4', scaling: 'power', factor: .5, onHitStatusId: 'battle_fatigue', onHitDuration: 3 }, { type: 'shield', dice: '3d6', scaling: 'power', duration: 2, target: 'self' }],
      tags: ['MASS', 'DEBUFF', 'SHIELD'], icon: { frame: 'burst', motif: 'blade', accent: 'shield' },
    },
    {
      id: 'heart_of_the_company', name: 'Сердце дружины', rarity: 'epic', cooldown: 7, target: 'ally', projectile: 'arrow',
      description: 'Союзник получает щит на 3d6 + Силу заклинателя на 3 хода, Знамя сплочения и Авангард на 3 хода: Сила +2, Защита +3, следующий бросок инициативы +3. Перед оставшимся прямым уроном по отряду носитель бросает 1d4 и уменьшает его, пока в строю. Текущая очередь не меняется.',
      actions: [{ type: 'shield', dice: '3d6', scaling: 'power', duration: 3 }, { type: 'status', statusId: 'rallying_standard', duration: 3 }, { type: 'status', statusId: 'vanguard', duration: 3 }],
      tags: ['SHIELD', 'PARTY_GUARD', 'ARMOR'], icon: { frame: 'ward', motif: 'shield', accent: 'star' },
    },
    {
      id: 'three_veteran_cuts', name: 'Три зарубки ветерана', rarity: 'epic', cooldown: 7, target: 'enemy', projectile: 'arrow',
      description: 'Сначала получает Метку дуэлянта на 3 хода: Точность и Критический удар +3. Затем наносит три удара по выбранному врагу, каждый на 1d6 + половину Силы, с отдельными бросками попадания и крита. Попадание даёт Боевое истощение на 2 хода: урон −3, Уклонение −2, следующая инициатива −2; очередь не меняется, повторное попадание обновляет срок.',
      actions: [{ type: 'status', statusId: 'duelists_mark', duration: 3, target: 'self' }, { type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 3, onHitStatusId: 'battle_fatigue', onHitDuration: 2 }],
      tags: ['MULTIHIT', 'CRITICAL', 'DEBUFF'], icon: { frame: 'arrows', motif: 'blade', accent: 'claw' },
    },
  ]),
  ...skillSchool('astral', 558, [
    {
      id: 'chalk_constellation', name: 'Меловое созвездие', rarity: 'common', cooldown: 4, target: 'ally', projectile: 'arcane',
      description: 'Страж созвездий на 2 хода: в начале собственного хода союзник получает слой щита на 2d4 + Силу источника со сроком 1 ход. В ход наложения слой не создаётся.',
      actions: [{ type: 'status', statusId: 'constellation_guard', duration: 2 }],
      tags: ['SHIELD'], icon: { frame: 'ward', motif: 'star', accent: 'rune' },
    },
    {
      id: 'cover_the_moon', name: 'Прикрыть луну', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'arcane',
      description: 'Без броска попадания накладывает Затмение на 2 хода: Точность врага −3, Сила −4.',
      actions: [{ type: 'status', statusId: 'eclipse', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'seal', motif: 'moon', accent: 'eye' },
    },
    {
      id: 'starlight_whetstone', name: 'Точило звёздного света', rarity: 'common', cooldown: 4, target: 'ally', projectile: 'arcane',
      description: 'Даёт союзнику Клинок звёздного огня на 2 хода: отдельный дополнительный 1d8 к каждому прямому удару и Критический удар +1.',
      actions: [{ type: 'status', statusId: 'starfire_blade', duration: 2 }],
      tags: ['BUFF', 'DAMAGE'], icon: { frame: 'weave', motif: 'star', accent: 'blade' },
    },
    {
      id: 'wandering_meteor_shard', name: 'Осколок заблудшего метеора', rarity: 'common', cooldown: 4, target: 'randomEnemy', projectile: 'arcane',
      description: 'Один случайный враг получает удар на 2d6 + Силу, игнорирующий Защиту. Попадание и критический удар проверяются отдельными d20; случайная цель выбирается один раз.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', bypassArmor: true }],
      tags: ['RANDOM', 'PIERCE'], icon: { frame: 'arrows', motif: 'star', accent: 'rock' },
    },
    {
      id: 'tuning_the_spheres', name: 'Настройка небесных сфер', rarity: 'common', cooldown: 4, target: 'ally', projectile: 'arcane',
      description: 'Небесный резонанс на 3 хода: получив реальное исцеление, союзник лечит весь отряд на 1d4 без цепочки передач. После тика периодического лечения, наложенного самим этим союзником, он бросает 1d6: на 6 продлевает заряд на ход, пока в строю; обычное уменьшение срока сохраняется.',
      actions: [{ type: 'status', statusId: 'celestial_resonance', duration: 3 }],
      tags: ['BUFF', 'HEAL', 'PRESERVE'], icon: { frame: 'orbit', motif: 'star', accent: 'wisp' },
    },
    {
      id: 'airless_touch', name: 'Прикосновение безвоздушья', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'arcane',
      description: 'Холод пустоты на 2 хода: Защита каждой части тела −4, Критический удар −3, Проворность −2. Попадание не проверяется.',
      actions: [{ type: 'status', statusId: 'void_chill', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'burst', motif: 'moon', accent: 'crystal' },
    },
    {
      id: 'chart_of_the_hunt', name: 'Карта небесной охоты', rarity: 'rare', cooldown: 6, target: 'allAllies', projectile: 'arcane',
      description: 'Весь отряд на 2 хода получает Звёздную точность: Точность +4, Критический удар +1. Естественная 1 на попадание остаётся промахом.',
      actions: [{ type: 'status', statusId: 'stellar_precision', duration: 2 }],
      tags: ['MASS', 'BUFF', 'CRITICAL'], icon: { frame: 'rays', motif: 'star', accent: 'eye' },
    },
    {
      id: 'falling_star_omen', name: 'Знамение падающей звезды', rarity: 'rare', cooldown: 5, target: 'randomUnit', projectile: 'arcane',
      description: 'Кубик выбирает одного участника: союзнику создаёт щит на 3d6 + Силу на 3 хода; врага атакует на 3d6 + Силу. Попадание по врагу оставляет След кометы на 2 хода: в конце хода — 2d4 + плоский бонус урона источника без Защиты, кроме хода наложения.',
      actions: [{ type: 'shield', dice: '3d6', scaling: 'power', duration: 3, targetRelation: 'ally' }, { type: 'damage', dice: '3d6', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'comet_wake', onHitDuration: 2 }],
      tags: ['RANDOM', 'HYBRID', 'SHIELD', 'DOT'], icon: { frame: 'weave', motif: 'star', accent: 'shield' },
    },
    {
      id: 'bathing_in_moonlight', name: 'Купание в лунном свете', rarity: 'rare', cooldown: 5, target: 'self', projectile: 'arcane',
      description: 'На 3 хода получает Лунную благодать и Лунный источник: Уклонение +3, Сила +3; в конце собственного хода лечится на 1d8 + Силу с учётом усиления. В ход наложения тика нет.',
      actions: [{ type: 'status', statusId: 'lunar_grace', duration: 3 }, { type: 'status', statusId: 'moonwell', duration: 3 }],
      tags: ['HOT', 'EVASION', 'BUFF'], icon: { frame: 'orbit', motif: 'moon', accent: 'drop' },
    },
    {
      id: 'twin_marks_of_the_void', name: 'Две метки пустоты', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'arcane',
      description: 'Сначала даёт Холод пустоты на 3 хода: Защита −4, Критический удар −3, Проворность −2. Затем дважды атакует на 1d6 + половину Силы, с отдельными попаданием и критом для каждого удара. Холод пустоты остаётся при промахах.',
      actions: [{ type: 'status', statusId: 'void_chill', duration: 3 }, { type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 2 }],
      tags: ['MULTIHIT', 'DEBUFF'], icon: { frame: 'slash', motif: 'moon', accent: 'claw' },
    },
    {
      id: 'night_of_falling_crowns', name: 'Ночь падающих венцов', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'arcane',
      description: 'Всем врагам даёт След кометы на 2 хода: в конце собственного хода — 2d4 + плоский бонус урона источника без Защиты. Всем союзникам даёт Стража созвездий на 2 хода: в начале хода — слой щита на 2d4 + Силу источника со сроком 1 ход. В ход наложения тиков нет.',
      actions: [{ type: 'status', statusId: 'comet_wake', duration: 2 }, { type: 'status', statusId: 'constellation_guard', duration: 2, target: 'allAllies' }],
      tags: ['MASS', 'DOT', 'SHIELD'], icon: { frame: 'burst', motif: 'star', accent: 'moon' },
    },
    {
      id: 'vessel_of_the_northern_light', name: 'Сосуд северного света', rarity: 'epic', cooldown: 7, target: 'ally', projectile: 'arcane',
      description: 'Союзник получает Небесный резонанс на 3 хода: после реального лечения передаёт отряду 1d4 здоровья без цепочки; после тиков лечения, наложенного им самим, бросает 1d6, на 6 продлевает заряд на ход, пока в строю. Затем восстанавливает 3d8 + Силу заклинателя и получает Лунный источник на 3 хода: 1d8 + Сила заклинателя в конце хода, кроме хода наложения. Резонанс союзника не продлевает чужие ауры.',
      actions: [{ type: 'status', statusId: 'celestial_resonance', duration: 3 }, { type: 'heal', dice: '3d8', scaling: 'power' }, { type: 'status', statusId: 'moonwell', duration: 3 }],
      tags: ['HEAL', 'HOT', 'PRESERVE'], icon: { frame: 'seal', motif: 'star', accent: 'cross' },
    },
    {
      id: 'meteor_weave', name: 'Метеоритный узор', rarity: 'epic', cooldown: 7, target: 'enemy', projectile: 'arcane',
      description: 'Получает Клинок звёздного огня на 2 хода: Критический удар +1 и отдельный 1d8 к каждому прямому удару. Затем трижды атакует одного врага, каждый удар на 1d6 + половину Силы с этим дополнительным 1d8. Попадание и крит бросаются отдельно для каждого удара, после гибели цели серия прекращается.',
      actions: [{ type: 'status', statusId: 'starfire_blade', duration: 2, target: 'self' }, { type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 3 }],
      tags: ['MULTIHIT', 'CRITICAL', 'BUFF'], icon: { frame: 'arrows', motif: 'star', accent: 'flame' },
    },
  ]),
];
