import { skillSchool } from './skill-catalog-builders';

/** Learnable arts: every school has four common, three rare, two epic and one legendary skill. */
export const lifeExpansionSkills = [
  ...skillSchool('blood', 100, [
    {
      id: 'red_thread_cut', name: 'Разрез алой нити', rarity: 'common', cooldown: 2, target: 'enemy', projectile: 'blood',
      description: 'Удар на 1d6 + Силу. Попадание оставляет Кровотечение на 2 хода: в конце хода цели — 1d4 урона без защиты.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', onHitStatusId: 'bleeding', onHitDuration: 2 }],
      tags: ['BLEED', 'PHYSICAL'], icon: { frame: 'slash', motif: 'drop', accent: 'blade' },
    },
    {
      id: 'pulse_stitch', name: 'Пульсирующий шов', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'blood',
      description: 'Накладывает Багровое восстановление на 3 хода. В начале хода союзник восстанавливает 1d4 + Силу источника; в ход наложения тика нет.',
      actions: [{ type: 'status', statusId: 'crimson_mending', duration: 3 }],
      tags: ['HEAL', 'HOT'], icon: { frame: 'weave', motif: 'drop', accent: 'cross' },
    },
    {
      id: 'scarlet_raincoat', name: 'Плащ алого дождя', rarity: 'common', cooldown: 3, target: 'self', projectile: 'blood',
      description: 'Получает щит на 1d4 + Силу на 2 хода и Покров алой росы на 2 хода. С начала следующего хода покров создаёт слой щита на 1d6 со сроком 1 ход.',
      actions: [{ type: 'shield', dice: '1d4', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'sanguine_veil', duration: 2 }],
      tags: ['SHIELD'], icon: { frame: 'ward', motif: 'drop', accent: 'shield' },
    },
    {
      id: 'red_bargain', name: 'Багровый торг', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'blood',
      description: 'На 2 хода даёт союзнику Цену крови: +4 к броскам урона, но −4 к Защите каждой части тела. Здоровье при применении не тратится.',
      actions: [{ type: 'status', statusId: 'blood_price', duration: 2 }],
      tags: ['BUFF', 'DAMAGE', 'TRADEOFF'], icon: { frame: 'seal', motif: 'fang', accent: 'shield' },
    },
    {
      id: 'predator_banquet', name: 'Пир хищника', rarity: 'rare', cooldown: 4, target: 'enemy', projectile: 'blood',
      description: 'Сначала получает Жажду хищника на 2 хода: Точность +1, после прямого урона врагу лечится на 1d4, не больше нанесённого урона. Затем дважды атакует выбранного врага, каждый удар — 1d4 + половина Силы.',
      actions: [{ type: 'status', statusId: 'predators_thirst', duration: 2, target: 'self' }, { type: 'damage', dice: '1d4', scaling: 'power', factor: .5, hits: 2 }],
      tags: ['VAMPIRISM', 'MULTIHIT'], icon: { frame: 'arrows', motif: 'fang', accent: 'drop' },
    },
    {
      id: 'crimson_balance', name: 'Алое равновесие', rarity: 'rare', cooldown: 4, target: 'any', projectile: 'blood',
      description: 'Союзника лечит на 2d6 + Силу и даёт Багровое восстановление на 2 хода: 1d4 + Сила источника в начале хода. Врага атакует на 2d6 + Силу; попадание оставляет Кровотечение на 3 хода: 1d4 в конце хода без защиты.',
      actions: [{ type: 'heal', dice: '2d6', scaling: 'power', targetRelation: 'ally' }, { type: 'status', statusId: 'crimson_mending', duration: 2, targetRelation: 'ally' }, { type: 'damage', dice: '2d6', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'bleeding', onHitDuration: 3 }],
      tags: ['HYBRID', 'HEAL', 'BLEED'], icon: { frame: 'orbit', motif: 'drop', accent: 'cross' },
    },
    {
      id: 'hearts_compass', name: 'Компас сердец', rarity: 'rare', cooldown: 5, target: 'randomEnemy', projectile: 'blood',
      description: 'Кубик выбирает врага для удара на 3d6 + Силу. До удара заклинатель получает Охотника за сердцами на 2 хода: Критический удар +3 и дополнительный 1d4 к каждому прямому удару, включая этот.',
      actions: [{ type: 'status', statusId: 'heart_hunter', duration: 2, target: 'self' }, { type: 'damage', dice: '3d6', scaling: 'power' }],
      tags: ['RANDOM', 'CRITICAL', 'BUFF'], icon: { frame: 'rays', motif: 'eye', accent: 'drop' },
    },
    {
      id: 'scarlet_lifeline', name: 'Багровая нить жизни', rarity: 'epic', cooldown: 6, target: 'allAllies', projectile: 'blood',
      description: 'Каждый союзник получает щит на 2d6 + Силу на 2 хода и Багровое восстановление на 3 хода: в начале хода — лечение на 1d4 + Силу источника.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'crimson_mending', duration: 3 }],
      tags: ['MASS', 'SHIELD', 'HOT'], icon: { frame: 'weave', motif: 'cross', accent: 'drop' },
    },
    {
      id: 'arterial_severance', name: 'Разрыв артерии', rarity: 'epic', cooldown: 6, target: 'enemy', projectile: 'blood',
      description: 'Удар на 4d8 + Силу, игнорирующий Защиту. Попадание оставляет Рваную рану на 4 хода: Сила цели −2 и 1d6 урона в конце хода без защиты.',
      actions: [{ type: 'damage', dice: '4d8', scaling: 'power', bypassArmor: true, onHitStatusId: 'open_wound', onHitDuration: 4 }],
      tags: ['BLEED', 'PIERCE'], icon: { frame: 'burst', motif: 'blade', accent: 'claw' },
    },
    {
      id: 'covenant_of_the_red_moon', name: 'Завет багровой луны', rarity: 'legendary', cooldown: 9, target: 'allEnemies', projectile: 'blood',
      description: 'Получает Алый завет и Багровое восстановление на 4 хода: в начале хода лечится на 1d4 + Силу, а после реального лечения передаёт всему отряду 1d4 здоровья. Затем атакует каждого врага на 3d6 + Силу; попадание оставляет Рваную рану на 3 хода: Сила −2 и 1d6 урона в конце хода без защиты.',
      actions: [{ type: 'status', statusId: 'scarlet_covenant', duration: 4, target: 'self' }, { type: 'status', statusId: 'crimson_mending', duration: 4, target: 'self' }, { type: 'damage', dice: '3d6', scaling: 'power', onHitStatusId: 'open_wound', onHitDuration: 3 }],
      tags: ['MASS', 'BLEED', 'HOT', 'HEAL'], icon: { frame: 'seal', motif: 'moon', accent: 'drop' },
    },
  ]),
  ...skillSchool('holy', 110, [
    {
      id: 'candle_guard', name: 'Стража свечи', rarity: 'common', cooldown: 2, target: 'ally', projectile: 'holy',
      description: 'Создаёт на выбранном союзнике щит ёмкостью 2d4 + Сила на 2 его хода.',
      actions: [{ type: 'shield', dice: '2d4', scaling: 'power', duration: 2 }],
      tags: ['SHIELD'], icon: { frame: 'ward', motif: 'flame', accent: 'cross' },
    },
    {
      id: 'pilgrims_passage', name: 'Дорога паломника', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'holy',
      description: 'Благодать паломника на 3 хода: союзник получает +3 к Проворности для побега и +2 к Уклонению.',
      actions: [{ type: 'status', statusId: 'pilgrims_grace', duration: 3 }],
      tags: ['EVASION', 'ESCAPE'], icon: { frame: 'arrows', motif: 'feather', accent: 'star' },
    },
    {
      id: 'rebuking_ray', name: 'Укоряющий луч', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'holy',
      description: 'Удар на 1d8 + Силу. Попадание накладывает Светлый приговор на 2 хода: Точность −3, Критический удар −2.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', onHitStatusId: 'radiant_censure', onHitDuration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'rays', motif: 'cross', accent: 'eye' },
    },
    {
      id: 'warm_hands', name: 'Тепло ладоней', rarity: 'common', cooldown: 2, target: 'ally', projectile: 'holy',
      description: 'Восстанавливает выбранному живому союзнику 1d8 + Силу здоровья. Отдельный d20 проверяет критическое исцеление.',
      actions: [{ type: 'heal', dice: '1d8', scaling: 'power' }],
      tags: ['HEAL'], icon: { frame: 'orbit', motif: 'cross', accent: 'flame' },
    },
    {
      id: 'vigil_of_the_lantern', name: 'Дозор светоча', rarity: 'rare', cooldown: 4, target: 'self', projectile: 'holy',
      description: 'Получает Дозор мученика на 3 хода: Защита +2; перед прямым уроном любому союзнику, включая себя, бросает 1d4 и уменьшает оставшийся после защиты урон. Сразу создаёт на себе щит на 1d8 + Силу на 2 хода.',
      actions: [{ type: 'status', statusId: 'martyrs_vigil', duration: 3 }, { type: 'shield', dice: '1d8', scaling: 'power', duration: 2 }],
      tags: ['GUARD', 'SHIELD'], icon: { frame: 'seal', motif: 'feather', accent: 'shield' },
    },
    {
      id: 'scales_of_sanctuary', name: 'Весы святилища', rarity: 'rare', cooldown: 4, target: 'any', projectile: 'holy',
      description: 'Союзнику даёт щит на 3d6 + Силу на 3 хода. Врага атакует на 3d6 + Силу. Выбранная цель определяет действие.',
      actions: [{ type: 'shield', dice: '3d6', scaling: 'power', duration: 3, targetRelation: 'ally' }, { type: 'damage', dice: '3d6', scaling: 'power', targetRelation: 'enemy' }],
      tags: ['HYBRID', 'SHIELD'], icon: { frame: 'weave', motif: 'shield', accent: 'blade' },
    },
    {
      id: 'choir_of_candles', name: 'Хор свечей', rarity: 'rare', cooldown: 5, target: 'allAllies', projectile: 'holy',
      description: 'Каждому живому участнику отряда восстанавливает 2d4 + Силу здоровья. Кубики лечения и критического исцеления бросаются отдельно для каждого.',
      actions: [{ type: 'heal', dice: '2d4', scaling: 'power' }],
      tags: ['MASS', 'HEAL'], icon: { frame: 'rays', motif: 'flame', accent: 'feather' },
    },
    {
      id: 'mercy_resonance', name: 'Отзвук милосердия', rarity: 'epic', cooldown: 6, target: 'ally', projectile: 'holy',
      description: 'Сначала даёт Хор милосердия на 3 хода: Сила союзника +2, а после его реального исцеления всему отряду передаётся 1d6 здоровья. Затем лечит цель на 4d8 + Силу заклинателя; это лечение тоже может запустить передачу.',
      actions: [{ type: 'status', statusId: 'merciful_chorus', duration: 3 }, { type: 'heal', dice: '4d8', scaling: 'power' }],
      tags: ['HEAL', 'BUFF'], icon: { frame: 'burst', motif: 'cross', accent: 'feather' },
    },
    {
      id: 'unbroken_covenant', name: 'Нерушимый обет', rarity: 'epic', cooldown: 6, target: 'self', projectile: 'holy',
      description: 'На 3 хода получает Клятву убежища и щит на 4d6 + Силу. Когда созданный им щит должен терять ёмкость, бросает 1d6: на 5+ щит поглощает весь остаток удара без расхода ёмкости.',
      actions: [{ type: 'status', statusId: 'oath_of_sanctuary', duration: 3 }, { type: 'shield', dice: '4d6', scaling: 'power', duration: 3 }],
      tags: ['SHIELD', 'DEFENSE'], icon: { frame: 'ward', motif: 'rune', accent: 'cross' },
    },
    {
      id: 'cathedral_of_dawn', name: 'Собор первого света', rarity: 'legendary', cooldown: 9, target: 'allAllies', projectile: 'holy',
      description: 'Весь отряд получает щит на 3d8 + Силу и Божественную защиту на 3 хода: +8 к Защите каждой части тела, ещё −3 к входящему урону после защиты. Урон, игнорирующий защиту, обходит это уменьшение.',
      actions: [{ type: 'shield', dice: '3d8', scaling: 'power', duration: 3 }, { type: 'status', statusId: 'divine_protection', duration: 3 }],
      tags: ['MASS', 'SHIELD', 'ARMOR'], icon: { frame: 'seal', motif: 'cross', accent: 'star' },
    },
  ]),
  ...skillSchool('nature', 120, [
    {
      id: 'bramble_hook', name: 'Крюк ежевики', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'nature',
      description: 'Удар на 1d8 + Силу. Попадание накладывает Корневую хватку на 2 хода: Уклонение и Проворность −3. Действие цели не отнимается.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', onHitStatusId: 'rootbound', onHitDuration: 2 }],
      tags: ['DEBUFF', 'PHYSICAL'], icon: { frame: 'slash', motif: 'leaf', accent: 'claw' },
    },
    {
      id: 'fox_senses', name: 'Лисье чутьё', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'nature',
      description: 'Звериное чутьё на 3 хода: Точность +2, Уклонение +2, бонус к следующему броску инициативы +2. Уже определённая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'wild_instinct', duration: 3 }],
      tags: ['BUFF', 'EVASION'], icon: { frame: 'seal', motif: 'eye', accent: 'leaf' },
    },
    {
      id: 'meadow_balm', name: 'Луговой бальзам', rarity: 'common', cooldown: 2, target: 'ally', projectile: 'nature',
      description: 'Лечит выбранного союзника на 2d4 + Силу. Отдельный d20 определяет критическое исцеление.',
      actions: [{ type: 'heal', dice: '2d4', scaling: 'power' }],
      tags: ['HEAL'], icon: { frame: 'rays', motif: 'leaf', accent: 'drop' },
    },
    {
      id: 'woven_boughs', name: 'Плетение ветвей', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'nature',
      description: 'Создаёт союзнику щит на 2d4 + Силу на 3 его хода.',
      actions: [{ type: 'shield', dice: '2d4', scaling: 'power', duration: 3 }],
      tags: ['SHIELD'], icon: { frame: 'weave', motif: 'leaf', accent: 'shield' },
    },
    {
      id: 'thornbound_keeper', name: 'Терновый хранитель', rarity: 'rare', cooldown: 5, target: 'self', projectile: 'nature',
      description: 'На 3 хода получает Терновый дозор и Сердце дуба: +1d4 к прямым ударам, защита отряда кубиком 1d4 перед входящим прямым уроном, Защита +6 и −2 к следующему броску инициативы. Текущая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'thorn_guard', duration: 3 }, { type: 'status', statusId: 'oak_heart', duration: 3 }],
      tags: ['GUARD', 'ARMOR', 'DAMAGE'], icon: { frame: 'ward', motif: 'rock', accent: 'claw' },
    },
    {
      id: 'seed_of_a_hundred_paths', name: 'Семя сотни троп', rarity: 'rare', cooldown: 4, target: 'randomAlly', projectile: 'nature',
      description: 'Случайный союзник получает на 2 хода Дикое обновление и Семя возвращения. В начале хода лечится на 2d4 + Силу источника и получает слой щита на 1d4 + Силу источника со сроком 2 хода. В ход наложения тиков нет.',
      actions: [{ type: 'status', statusId: 'wild_renewal', duration: 2 }, { type: 'status', statusId: 'seed_of_return', duration: 2 }],
      tags: ['RANDOM', 'HOT', 'SHIELD'], icon: { frame: 'orbit', motif: 'leaf', accent: 'rune' },
    },
    {
      id: 'bloom_or_briar', name: 'Цветок или терн', rarity: 'rare', cooldown: 4, target: 'any', projectile: 'nature',
      description: 'Союзника лечит на 2d6 + Силу, затем даёт Дыхание весны на 2 хода: Сила +4. Врага атакует на 2d6 + Силу; попадание оставляет Терновую рану на 3 хода: 1d6 урона с учётом защиты в конце хода.',
      actions: [{ type: 'heal', dice: '2d6', scaling: 'power', targetRelation: 'ally' }, { type: 'status', statusId: 'spring_breath', duration: 2, targetRelation: 'ally' }, { type: 'damage', dice: '2d6', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'briar_wound', onHitDuration: 3 }],
      tags: ['HYBRID', 'HEAL', 'DOT'], icon: { frame: 'burst', motif: 'leaf', accent: 'fang' },
    },
    {
      id: 'green_canopy', name: 'Зелёный полог', rarity: 'epic', cooldown: 6, target: 'allAllies', projectile: 'nature',
      description: 'Каждый союзник получает щит на 2d6 + Силу на 3 хода. Затем весь отряд получает Дыхание весны на 3 хода: Сила +4. Бонус не усиливает уже созданные щиты.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 3 }, { type: 'status', statusId: 'spring_breath', duration: 3 }],
      tags: ['MASS', 'SHIELD', 'BUFF'], icon: { frame: 'weave', motif: 'shield', accent: 'leaf' },
    },
    {
      id: 'forest_closes_in', name: 'Лес смыкается', rarity: 'epic', cooldown: 6, target: 'allEnemies', projectile: 'nature',
      description: 'Сначала накладывает на всех врагов Корневую хватку на 3 хода: Уклонение и Проворность −3. Затем атакует каждого на 2d8 + половину Силы. Хватка остаётся даже при промахе удара.',
      actions: [{ type: 'status', statusId: 'rootbound', duration: 3 }, { type: 'damage', dice: '2d8', scaling: 'power', factor: .5 }],
      tags: ['MASS', 'DEBUFF'], icon: { frame: 'arrows', motif: 'claw', accent: 'leaf' },
    },
    {
      id: 'worldtrees_awakening', name: 'Пробуждение Мирового древа', rarity: 'legendary', cooldown: 10, target: 'allAllies', projectile: 'nature',
      description: 'Весь отряд на 4 хода получает Дыхание весны (Сила +4), Дикое обновление и Семя возвращения. С начала следующего хода каждого союзника — лечение на 2d4 + Силу источника и отдельный щит на 1d4 + Силу источника со сроком 2 хода.',
      actions: [{ type: 'status', statusId: 'spring_breath', duration: 4 }, { type: 'status', statusId: 'wild_renewal', duration: 4 }, { type: 'status', statusId: 'seed_of_return', duration: 4 }],
      tags: ['MASS', 'HOT', 'SHIELD', 'BUFF'], icon: { frame: 'seal', motif: 'leaf', accent: 'star' },
    },
  ]),
  ...skillSchool('shadow', 130, [
    {
      id: 'soot_in_the_eyes', name: 'Сажа в глазах', rarity: 'common', cooldown: 2, target: 'enemy', projectile: 'shadow',
      description: 'Накладывает Тьму в глазах на 2 хода: Точность врага −4. Урона не наносит, броска попадания нет.',
      actions: [{ type: 'status', statusId: 'blackout', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'burst', motif: 'eye', accent: 'moon' },
    },
    {
      id: 'sidestep_into_dusk', name: 'Шаг в сумерки', rarity: 'common', cooldown: 3, target: 'self', projectile: 'shadow',
      description: 'На 2 хода получает Изворотливость: Уклонение +4. Естественная 20 врага по-прежнему гарантирует попадание.',
      actions: [{ type: 'status', statusId: 'evasiveness', duration: 2 }],
      tags: ['EVASION'], icon: { frame: 'orbit', motif: 'feather', accent: 'moon' },
    },
    {
      id: 'needles_of_dusk', name: 'Иглы сумерек', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'shadow',
      description: 'Два независимых удара по выбранному врагу, каждый на 1d4 + половину Силы. Для каждого отдельно бросаются попадание и крит; после гибели цели серия прекращается.',
      actions: [{ type: 'damage', dice: '1d4', scaling: 'power', factor: .5, hits: 2 }],
      tags: ['MULTIHIT'], icon: { frame: 'arrows', motif: 'blade', accent: 'moon' },
    },
    {
      id: 'borrowed_silence', name: 'Заимствованная тишина', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'shadow',
      description: 'Беззвучный шаг на 3 хода: Проворность союзника +4, бонус к следующему броску инициативы +3. Уже определённая очередь остаётся прежней.',
      actions: [{ type: 'status', statusId: 'silent_step', duration: 3 }],
      tags: ['BUFF', 'ESCAPE'], icon: { frame: 'weave', motif: 'feather', accent: 'eye' },
    },
    {
      id: 'moonless_gash', name: 'Безлунный порез', rarity: 'rare', cooldown: 4, target: 'enemy', projectile: 'shadow',
      description: 'Удар на 2d8 + Силу. Попадание оставляет Ночную рану на 3 хода: 1d8 урона с учётом защиты в конце хода цели.',
      actions: [{ type: 'damage', dice: '2d8', scaling: 'power', onHitStatusId: 'night_wound', onHitDuration: 3 }],
      tags: ['DOT'], icon: { frame: 'slash', motif: 'moon', accent: 'claw' },
    },
    {
      id: 'second_silhouette', name: 'Второй силуэт', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'shadow',
      description: 'Эхо тени на 3 хода: Критический удар +1. После действия с уроном союзник бросает 1d6; на 5+ повторяет базовую атаку по той же живой цели. Повтор не запускает новую цепочку.',
      actions: [{ type: 'status', statusId: 'shadow_echo', duration: 3 }],
      tags: ['BUFF', 'REPEAT'], icon: { frame: 'seal', motif: 'moon', accent: 'blade' },
    },
    {
      id: 'two_faces_of_night', name: 'Два лика ночи', rarity: 'rare', cooldown: 4, target: 'any', projectile: 'shadow',
      description: 'Союзнику даёт Доспех сумрака на 3 хода: Защита +4, Уклонение +2. Врагу сначала накладывает Тьму в глазах на 2 хода (Точность −4), затем атакует его на 2d6 + Силу.',
      actions: [{ type: 'status', statusId: 'gloom_armor', duration: 3, targetRelation: 'ally' }, { type: 'status', statusId: 'blackout', duration: 2, targetRelation: 'enemy' }, { type: 'damage', dice: '2d6', scaling: 'power', targetRelation: 'enemy' }],
      tags: ['HYBRID', 'ARMOR', 'DEBUFF'], icon: { frame: 'ward', motif: 'eye', accent: 'shield' },
    },
    {
      id: 'eclipse_procession', name: 'Шествие затмения', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'shadow',
      description: 'На всех врагов накладывает Тьму в глазах на 2 хода (Точность −4) и Ночную рану на 3 хода (1d8 урона с учётом защиты в конце хода). Прямых ударов и бросков попадания нет; в ход наложения рана не тикает.',
      actions: [{ type: 'status', statusId: 'blackout', duration: 2 }, { type: 'status', statusId: 'night_wound', duration: 3 }],
      tags: ['MASS', 'DEBUFF', 'DOT'], icon: { frame: 'rays', motif: 'moon', accent: 'skull' },
    },
    {
      id: 'assassins_ascendancy', name: 'Час безмолвного клинка', rarity: 'epic', cooldown: 6, target: 'self', projectile: 'shadow',
      description: 'На 3 хода получает Сокрытое лезвие и Смертоносность: Точность +3, дополнительный 1d4 к прямым ударам и Критический удар +5. Для крита остаётся отдельный d20.',
      actions: [{ type: 'status', statusId: 'veiled_blade', duration: 3 }, { type: 'status', statusId: 'lethality', duration: 3 }],
      tags: ['BUFF', 'CRITICAL', 'DAMAGE'], icon: { frame: 'slash', motif: 'blade', accent: 'eye' },
    },
    {
      id: 'five_knives_of_midnight', name: 'Пять ножей полуночи', rarity: 'legendary', cooldown: 8, target: 'randomEnemy', projectile: 'shadow',
      description: 'Кубик выбирает одного врага. Пять независимых ударов по нему, каждый на 1d6 + половину Силы; каждое попадание оставляет отдельную Ночную рану на 2 хода: 1d8 урона в конце хода с учётом защиты. После гибели цели оставшиеся ножи не перенаправляются.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 5, onHitStatusId: 'night_wound', onHitDuration: 2 }],
      tags: ['RANDOM', 'MULTIHIT', 'DOT'], icon: { frame: 'arrows', motif: 'blade', accent: 'star' },
    },
  ]),
  ...skillSchool('arcane', 140, [
    {
      id: 'unclouded_lens', name: 'Ясная линза', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'arcane',
      description: 'Чародейское зрение на 3 хода: Точность союзника +4, уменьшающая Уклонение цели при проверке попадания.',
      actions: [{ type: 'status', statusId: 'arcane_sight', duration: 3 }],
      tags: ['BUFF', 'ACCURACY'], icon: { frame: 'orbit', motif: 'eye', accent: 'crystal' },
    },
    {
      id: 'weighted_glyph', name: 'Глиф тяжести', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'arcane',
      description: 'Удар на 1d8 + Силу. Попадание накладывает Сковывающий глиф на 3 хода: Проворность −2, бонус к следующему броску инициативы −4. Текущая очередь не меняется.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', onHitStatusId: 'binding_glyph', onHitDuration: 3 }],
      tags: ['DEBUFF'], icon: { frame: 'seal', motif: 'rune', accent: 'rock' },
    },
    {
      id: 'aether_spindle', name: 'Эфирное веретено', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'arcane',
      description: 'Эфирный барьер на 2 хода. В начале хода союзника создаёт слой щита на 2d4 со сроком 1 ход; Сила к этому кубику не добавляется. В ход наложения тика нет.',
      actions: [{ type: 'status', statusId: 'aether_barrier', duration: 2 }],
      tags: ['SHIELD'], icon: { frame: 'weave', motif: 'rune', accent: 'shield' },
    },
    {
      id: 'raw_aether_shard', name: 'Осколок чистого эфира', rarity: 'common', cooldown: 2, target: 'enemy', projectile: 'arcane',
      description: 'Атакует выбранного врага на 3d4. Сила к урону не добавляется; бонусы прямых ударов от действующих аур сохраняются. Попадание и крит проверяются отдельными d20.',
      actions: [{ type: 'damage', dice: '3d4' }],
      tags: ['DAMAGE'], icon: { frame: 'slash', motif: 'crystal', accent: 'rune' },
    },
    {
      id: 'wandering_comets', name: 'Блуждающие кометы', rarity: 'rare', cooldown: 4, target: 'randomEnemy', projectile: 'arcane',
      description: 'Кубик выбирает врага для двух независимых ударов, каждый на 1d8 + половину Силы. Каждое попадание оставляет отдельный Ожог эфира на 2 хода: 1d6 урона без защиты в начале хода цели.',
      actions: [{ type: 'damage', dice: '1d8', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'mana_scorch', onHitDuration: 2 }],
      tags: ['RANDOM', 'MULTIHIT', 'DOT'], icon: { frame: 'arrows', motif: 'star', accent: 'rune' },
    },
    {
      id: 'living_conduit', name: 'Живой проводник', rarity: 'rare', cooldown: 4, target: 'ally', projectile: 'arcane',
      description: 'Средоточие чар на 3 хода: Сила союзника +5, Критический удар +2. Сила усиливает и урон, и лечение, и щиты, если действие использует этот атрибут.',
      actions: [{ type: 'status', statusId: 'spell_focus', duration: 3 }],
      tags: ['BUFF', 'CRITICAL'], icon: { frame: 'rays', motif: 'crystal', accent: 'bolt' },
    },
    {
      id: 'axiom_of_equilibrium', name: 'Аксиома равновесия', rarity: 'rare', cooldown: 5, target: 'any', projectile: 'arcane',
      description: 'Союзнику создаёт щит на 3d6 + Силу на 3 хода. Врага атакует на 2d6 + Силу; при попадании накладывает Разлад чар на 3 хода: Сила −5 и Точность −2.',
      actions: [{ type: 'shield', dice: '3d6', scaling: 'power', duration: 3, targetRelation: 'ally' }, { type: 'damage', dice: '2d6', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'arcane_disruption', onHitDuration: 3 }],
      tags: ['HYBRID', 'SHIELD', 'DEBUFF'], icon: { frame: 'seal', motif: 'rune', accent: 'cross' },
    },
    {
      id: 'prismatic_redoubt', name: 'Призматический редут', rarity: 'epic', cooldown: 6, target: 'self', projectile: 'arcane',
      description: 'Получает Зеркальный покров и щит на 4d8 + Силу на 3 хода. Покров даёт Уклонение +1; при расходе созданного им щита бросает 1d4: на 4 весь остаток урона поглощается без расхода ёмкости.',
      actions: [{ type: 'status', statusId: 'mirror_ward', duration: 3 }, { type: 'shield', dice: '4d8', scaling: 'power', duration: 3 }],
      tags: ['SHIELD', 'EVASION'], icon: { frame: 'ward', motif: 'crystal', accent: 'eye' },
    },
    {
      id: 'unravel_the_pattern', name: 'Расплести узор', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'arcane',
      description: 'Все враги получают Разлад чар на 2 хода (Сила −5, Точность −2) и Ожог эфира на 3 хода: 1d6 урона без защиты в начале хода. Бросков попадания нет; в ход наложения ожог не тикает.',
      actions: [{ type: 'status', statusId: 'arcane_disruption', duration: 2 }, { type: 'status', statusId: 'mana_scorch', duration: 3 }],
      tags: ['MASS', 'DEBUFF', 'DOT'], icon: { frame: 'burst', motif: 'rune', accent: 'claw' },
    },
    {
      id: 'grand_theorem', name: 'Великая теорема', rarity: 'legendary', cooldown: 9, target: 'allAllies', projectile: 'arcane',
      description: 'Сначала даёт всему отряду щиты на 2d8 + Силу на 2 хода. Затем на 4 хода накладывает Безупречную формулу (Точность, Критический удар и Сила +2) и Эфирный барьер: в начале хода — слой щита на 2d4 со сроком 1 ход, без прибавки Силы.',
      actions: [{ type: 'shield', dice: '2d8', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'perfect_formula', duration: 4 }, { type: 'status', statusId: 'aether_barrier', duration: 4 }],
      tags: ['MASS', 'SHIELD', 'BUFF'], icon: { frame: 'weave', motif: 'star', accent: 'rune' },
    },
  ]),
];
