import { skillSchool } from './skill-catalog-builders';

/** Elemental techniques for the 4:3:2:1 rarity pools. Durations use the recipient's own turns. */
export const elementalProportionalSkills = [
  ...skillSchool('fire', 400, [
    {
      id: 'twin_candle_fangs', name: 'Два клыка свечи', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'fire',
      description: 'Два независимых удара по выбранному врагу, каждый на 1d4 без Силы. Каждое попадание добавляет заряд Горения: в конце хода цели урон равен числу зарядов, после чего один заряд исчезает.',
      actions: [{ type: 'damage', dice: '1d4', hits: 2, onHitStatusId: 'burning', onHitDuration: null }],
      tags: ['MULTIHIT', 'BURN'], icon: { frame: 'arrows', motif: 'flame', accent: 'fang' },
    },
    {
      id: 'hearthkeepers_palm', name: 'Ладонь хранителя очага', rarity: 'common', cooldown: 4, target: 'randomAlly', projectile: 'fire',
      description: 'Кубик выбирает одного союзника. Лечит его на 1d8 + Силу и даёт Знак огненного клинка на 2 хода: Критический удар +3, Точность +1.',
      actions: [{ type: 'heal', dice: '1d8', scaling: 'power' }, { type: 'status', statusId: 'firebrand', duration: 2 }],
      tags: ['RANDOM', 'HEAL', 'BUFF'], icon: { frame: 'rays', motif: 'cross', accent: 'flame' },
    },
    {
      id: 'ashblind_whisper', name: 'Шёпот горелой сажи', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'fire',
      description: 'Без проверки попадания накладывает Пепельное удушье на выбранного врага на 3 хода: Точность −3, Сила −2.',
      actions: [{ type: 'status', statusId: 'ash_choke', duration: 3 }],
      tags: ['DEBUFF'], icon: { frame: 'seal', motif: 'eye', accent: 'flame' },
    },
    {
      id: 'mantle_of_warm_cinders', name: 'Накидка тёплых углей', rarity: 'common', cooldown: 4, target: 'self', projectile: 'fire',
      description: 'На 2 хода получает Угольную кожу: Защита каждой части тела +3, каждый прямой удар получает дополнительный 1d4 к урону.',
      actions: [{ type: 'status', statusId: 'cinder_skin', duration: 2 }],
      tags: ['BUFF', 'ARMOR'], icon: { frame: 'ward', motif: 'rock', accent: 'flame' },
    },
    {
      id: 'coal_under_the_heart', name: 'Уголь под сердцем', rarity: 'common', cooldown: 4, target: 'self', projectile: 'fire',
      description: 'Создаёт на себе щит на 1d8 + Силу сроком 2 хода. На 2 хода получает Сердце горнила: броски урона +2, лечение на 1d4 без Силы в конце собственного хода.',
      actions: [{ type: 'shield', dice: '1d8', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'furnace_heart', duration: 2 }],
      tags: ['SHIELD', 'HOT'], icon: { frame: 'orbit', motif: 'drop', accent: 'flame' },
    },
    {
      id: 'scattered_tinder', name: 'Рассыпанный трут', rarity: 'common', cooldown: 4, target: 'allEnemies', projectile: 'fire',
      description: 'Без проверки попадания добавляет каждому врагу один заряд Горения. В конце хода каждого носителя Горение наносит урон по числу зарядов без Защиты и теряет один заряд.',
      actions: [{ type: 'status', statusId: 'burning', duration: null }],
      tags: ['MASS', 'BURN'], icon: { frame: 'burst', motif: 'flame', accent: 'leaf' },
    },
    {
      id: 'cauterists_choice', name: 'Выбор прижигателя', rarity: 'common', cooldown: 3, target: 'any', projectile: 'fire',
      description: 'Выбранного союзника, включая себя, лечит на 2d4 + Силу. Вместо этого выбранного врага атакует на 2d4 + Силу с обычными проверками попадания и крита.',
      actions: [{ type: 'heal', dice: '2d4', scaling: 'power', targetRelation: 'ally' }, { type: 'damage', dice: '2d4', scaling: 'power', targetRelation: 'enemy' }],
      tags: ['HYBRID', 'HEAL', 'DAMAGE'], icon: { frame: 'weave', motif: 'flame', accent: 'cross' },
    },
    {
      id: 'bellows_of_the_siege', name: 'Меха осадной печи', rarity: 'rare', cooldown: 5, target: 'allEnemies', projectile: 'fire',
      description: 'На 2 хода накладывает на всех врагов Обугленную броню: Защита каждой части тела −6. Заклинателю даёт Знак огненного клинка на 3 хода: Критический удар +3, Точность +1. Попадание не проверяется.',
      actions: [{ type: 'status', statusId: 'charred_armor', duration: 2 }, { type: 'status', statusId: 'firebrand', duration: 3, target: 'self' }],
      tags: ['MASS', 'DEBUFF', 'BUFF'], icon: { frame: 'rays', motif: 'shield', accent: 'flame' },
    },
    {
      id: 'feast_of_the_last_ember', name: 'Пир последнего угля', rarity: 'rare', cooldown: 4, target: 'lowestHealthEnemy', projectile: 'fire',
      description: 'Атакует выбранного врага на 2d8 + Силу; попадание добавляет заряд Горения. Затем лечит заклинателя на 1d6 без Силы, даже если удар промахнулся. При автовыборе приоритет у врага с наименьшей долей здоровья.',
      actions: [{ type: 'damage', dice: '2d8', scaling: 'power', onHitStatusId: 'burning', onHitDuration: null }, { type: 'heal', dice: '1d6', target: 'self' }],
      tags: ['DAMAGE', 'BURN', 'HEAL'], icon: { frame: 'slash', motif: 'fang', accent: 'flame' },
    },
    {
      id: 'courier_of_wild_sparks', name: 'Гонец буйных искр', rarity: 'rare', cooldown: 5, target: 'randomAlly', projectile: 'fire',
      description: 'Одному случайному союзнику на 3 хода даёт Неистовые искры: дополнительный 1d6 к каждому прямому удару; после действия с уроном бросает 1d6, на 6 повторяет базовую атаку по той же живой цели без цепочки повторов.',
      actions: [{ type: 'status', statusId: 'volatile_sparks', duration: 3 }],
      tags: ['RANDOM', 'BUFF', 'REPEAT'], icon: { frame: 'arrows', motif: 'feather', accent: 'flame' },
    },
    {
      id: 'brazier_of_comrades', name: 'Жаровня побратимов', rarity: 'rare', cooldown: 5, target: 'allAllies', projectile: 'fire',
      description: 'Всем союзникам на 2 хода даёт Сердце горнила: броски урона +2, лечение на 1d4 без Силы в конце хода. Заклинателю на 2 хода — Огненный заслон: Защита +2, в начале хода щит на 1d8 со сроком 1 ход.',
      actions: [{ type: 'status', statusId: 'furnace_heart', duration: 2 }, { type: 'status', statusId: 'flameward', duration: 2, target: 'self' }],
      tags: ['MASS', 'HOT', 'SHIELD'], icon: { frame: 'seal', motif: 'flame', accent: 'shield' },
    },
    {
      id: 'cinders_dual_verdict', name: 'Двойной приговор пепла', rarity: 'rare', cooldown: 5, target: 'any', projectile: 'fire',
      description: 'Союзнику создаёт щит на 2d4 + Силу на 2 хода и Огненный заслон на 2 хода: Защита +2, в начале хода щит на 1d8 со сроком 1 ход. Врагу без проверки попадания на 2 хода — Пепельное удушье (Точность −3, Сила −2) и Тление (1d6 урона с Защитой в конце хода).',
      actions: [{ type: 'shield', dice: '2d4', scaling: 'power', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'flameward', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'ash_choke', duration: 2, targetRelation: 'enemy' }, { type: 'status', statusId: 'smoldering', duration: 2, targetRelation: 'enemy' }],
      tags: ['HYBRID', 'SHIELD', 'DOT'], icon: { frame: 'weave', motif: 'flame', accent: 'eye' },
    },
    {
      id: 'breath_of_the_brass_wyrm', name: 'Дыхание медного змея', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'fire',
      description: 'Каждому врагу — удар на 2d6 + половину Силы; попадание оставляет Обугленную броню на 3 хода: Защита каждой части тела −6. Заклинатель получает Угольную кожу на 3 хода: Защита +3, дополнительный 1d4 к прямым ударам, независимо от попаданий.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', factor: .5, onHitStatusId: 'charred_armor', onHitDuration: 3 }, { type: 'status', statusId: 'cinder_skin', duration: 3, target: 'self' }],
      tags: ['MASS', 'DAMAGE', 'DEBUFF', 'ARMOR'], icon: { frame: 'burst', motif: 'fang', accent: 'flame' },
    },
    {
      id: 'heart_of_the_ashen_phoenix', name: 'Сердце пепельного феникса', rarity: 'epic', cooldown: 6, target: 'self', projectile: 'fire',
      description: 'На 3 хода получает Искры жизни (1d8 + Сила источника в начале хода), Огненный заслон (Защита +2, в начале хода щит на 1d8 со сроком 1 ход) и Знак огненного клинка (Критический удар +3, Точность +1).',
      actions: [{ type: 'status', statusId: 'embers_of_life', duration: 3 }, { type: 'status', statusId: 'flameward', duration: 3 }, { type: 'status', statusId: 'firebrand', duration: 3 }],
      tags: ['HOT', 'SHIELD', 'BUFF'], icon: { frame: 'ward', motif: 'feather', accent: 'flame' },
    },
    {
      id: 'duel_at_the_furnace', name: 'Поединок у горнила', rarity: 'epic', cooldown: 6, target: 'enemy', projectile: 'fire',
      description: 'Сначала получает Неистовые искры на 2 хода: 1d6 к прямым ударам; после действия с уроном 1d6, на 6 — повтор базовой атаки по той же живой цели. Затем дважды атакует врага на 1d8 + Силу за удар; каждое попадание добавляет Горение. Новые искры усиливают и эти удары.',
      actions: [{ type: 'status', statusId: 'volatile_sparks', duration: 2, target: 'self' }, { type: 'damage', dice: '1d8', scaling: 'power', hits: 2, onHitStatusId: 'burning', onHitDuration: null }],
      tags: ['MULTIHIT', 'BURN', 'REPEAT'], icon: { frame: 'orbit', motif: 'blade', accent: 'flame' },
    },
  ]),
  ...skillSchool('frost', 415, [
    {
      id: 'whisper_of_the_snowfield', name: 'Шёпот снежного поля', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'frost',
      description: 'Без проверки попадания накладывает Белое безмолвие на 2 хода: Сила врага −3, броски урона −3. Враг сохраняет возможность действовать.',
      actions: [{ type: 'status', statusId: 'white_silence', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'rays', motif: 'moon', accent: 'crystal' },
    },
    {
      id: 'rime_tailors_touch', name: 'Прикосновение портного инея', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'frost',
      description: 'Выбранный союзник на 2 хода получает Иней на доспехе: Защита каждой части тела +7, Проворность −2.',
      actions: [{ type: 'status', statusId: 'rime_armor', duration: 2 }],
      tags: ['ARMOR', 'TRADEOFF'], icon: { frame: 'weave', motif: 'shield', accent: 'crystal' },
    },
    {
      id: 'ice_drifters_gift', name: 'Дар ледохода', rarity: 'common', cooldown: 3, target: 'randomAlly', projectile: 'frost',
      description: 'Один случайный союзник получает щит на 2d8 + Силу заклинателя. Щит сохраняется 2 собственных хода получателя.',
      actions: [{ type: 'shield', dice: '2d8', scaling: 'power', duration: 2 }],
      tags: ['RANDOM', 'SHIELD'], icon: { frame: 'orbit', motif: 'crystal', accent: 'drop' },
    },
    {
      id: 'frost_on_the_wound', name: 'Иней на ране', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'frost',
      description: 'Без проверки попадания накладывает один заряд Обморожения на 2 хода: Уклонение −1, в начале собственного хода цели — 1d4 урона без Защиты и без Силы.',
      actions: [{ type: 'status', statusId: 'frostbite', duration: 2 }],
      tags: ['DOT', 'DEBUFF'], icon: { frame: 'seal', motif: 'crystal', accent: 'drop' },
    },
    {
      id: 'snow_travelers_rest', name: 'Привал снегоступа', rarity: 'common', cooldown: 4, target: 'self', projectile: 'frost',
      description: 'Лечит себя на 1d4 + Силу. На 2 хода получает Снежную пелену: Уклонение +3, Защита каждой части тела +2.',
      actions: [{ type: 'heal', dice: '1d4', scaling: 'power' }, { type: 'status', statusId: 'snowveil', duration: 2 }],
      tags: ['HEAL', 'EVASION'], icon: { frame: 'ward', motif: 'feather', accent: 'drop' },
    },
    {
      id: 'last_icicle', name: 'Последняя сосулька', rarity: 'common', cooldown: 3, target: 'lowestHealthEnemy', projectile: 'frost',
      description: 'Атакует выбранного врага на 2d4 + Силу. При попадании накладывает Леденящее онемение на 2 хода: Критический удар цели −4. При автовыборе приоритет у врага с наименьшей долей здоровья.',
      actions: [{ type: 'damage', dice: '2d4', scaling: 'power', onHitStatusId: 'numbing_cold', onHitDuration: 2 }],
      tags: ['DAMAGE', 'DEBUFF'], icon: { frame: 'slash', motif: 'crystal', accent: 'hourglass' },
    },
    {
      id: 'winter_gatekeeper', name: 'Привратник зимы', rarity: 'common', cooldown: 4, target: 'any', projectile: 'frost',
      description: 'Союзнику на 2 хода даёт Хрустальную оболочку: в начале хода щит на 1d8 без Силы со сроком 2 хода. Врага атакует на 1d6 + Силу; попадание даёт Промерзание на 2 хода: Проворность −2, следующая Инициатива −3. Текущая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'crystal_shell', duration: 2, targetRelation: 'ally' }, { type: 'damage', dice: '1d6', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'chilled', onHitDuration: 2 }],
      tags: ['HYBRID', 'SHIELD', 'DAMAGE'], icon: { frame: 'arrows', motif: 'rune', accent: 'crystal' },
    },
    {
      id: 'duet_of_white_blades', name: 'Дуэт белых клинков', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'frost',
      description: 'Два независимых удара по одному врагу, каждый на 1d6 + половину Силы. Попадание накладывает Леденящее онемение на 2 хода (Критический удар −4); повтор обновляет срок. Заклинатель получает Снежную пелену на 2 хода (Уклонение +3, Защита +2), даже при промахах.',
      actions: [{ type: 'damage', dice: '1d6', scaling: 'power', factor: .5, hits: 2, onHitStatusId: 'numbing_cold', onHitDuration: 2 }, { type: 'status', statusId: 'snowveil', duration: 2, target: 'self' }],
      tags: ['MULTIHIT', 'DEBUFF', 'EVASION'], icon: { frame: 'arrows', motif: 'blade', accent: 'crystal' },
    },
    {
      id: 'procession_of_the_thaw', name: 'Шествие оттепели', rarity: 'rare', cooldown: 5, target: 'allAllies', projectile: 'frost',
      description: 'Каждого союзника лечит на 1d4 + половину Силы. Даёт всему отряду Пульс оттепели на 1 ход: в конце собственного хода каждый восстанавливает 1d6 + Силу источника. В ход наложения аура не срабатывает.',
      actions: [{ type: 'heal', dice: '1d4', scaling: 'power', factor: .5 }, { type: 'status', statusId: 'thawing_pulse', duration: 1 }],
      tags: ['MASS', 'HEAL', 'HOT'], icon: { frame: 'rays', motif: 'drop', accent: 'feather' },
    },
    {
      id: 'cartographer_of_cracks', name: 'Картограф трещин', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'frost',
      description: 'Без проверки попадания накладывает на врага Ледяной надлом на 3 хода: Защита −3, в конце хода 2d4 урона без Силы с учётом Защиты. На себя накладывает Зимнюю сосредоточенность на 2 хода: Точность +3, Критический удар +2.',
      actions: [{ type: 'status', statusId: 'glacial_fracture', duration: 3 }, { type: 'status', statusId: 'winter_focus', duration: 2, target: 'self' }],
      tags: ['DOT', 'BUFF', 'DEBUFF'], icon: { frame: 'seal', motif: 'eye', accent: 'crystal' },
    },
    {
      id: 'turn_of_the_crystal_key', name: 'Поворот хрустального ключа', rarity: 'rare', cooldown: 5, target: 'any', projectile: 'frost',
      description: 'Союзнику — щит на 1d10 + Силу на 3 хода и Снежная пелена на 2 хода (Уклонение +3, Защита +2). Врагу — удар на 2d8 + Силу; попадание оставляет Белое безмолвие на 2 хода: Сила и броски урона −3.',
      actions: [{ type: 'shield', dice: '1d10', scaling: 'power', duration: 3, targetRelation: 'ally' }, { type: 'status', statusId: 'snowveil', duration: 2, targetRelation: 'ally' }, { type: 'damage', dice: '2d8', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'white_silence', onHitDuration: 2 }],
      tags: ['HYBRID', 'SHIELD', 'DEBUFF'], icon: { frame: 'weave', motif: 'rune', accent: 'moon' },
    },
    {
      id: 'sentinel_of_the_ice_gate', name: 'Часовой ледяных врат', rarity: 'rare', cooldown: 6, target: 'self', projectile: 'frost',
      description: 'На 2 хода получает Вызов: враги обязаны атаковать заклинателя; при нескольких провокациях действует последняя. На 3 хода получает Иней на доспехе (Защита +7, Проворность −2) и Хрустальную оболочку (в начале хода щит на 1d8 со сроком 2 хода).',
      actions: [{ type: 'status', statusId: 'taunted', duration: 2 }, { type: 'status', statusId: 'rime_armor', duration: 3 }, { type: 'status', statusId: 'crystal_shell', duration: 3 }],
      tags: ['TAUNT', 'SHIELD', 'ARMOR'], icon: { frame: 'ward', motif: 'shield', accent: 'eye' },
    },
    {
      id: 'ledger_of_the_blizzard', name: 'Летопись метели', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'frost',
      description: 'Без проверки попадания каждому врагу даёт Обморожение на 3 хода (Уклонение −1, в начале хода 1d4 урона без Защиты) и Белое безмолвие на 2 хода (Сила и броски урона −3). Периодический урон не прибавляет Силу.',
      actions: [{ type: 'status', statusId: 'frostbite', duration: 3 }, { type: 'status', statusId: 'white_silence', duration: 2 }],
      tags: ['MASS', 'DOT', 'DEBUFF'], icon: { frame: 'burst', motif: 'crystal', accent: 'rune' },
    },
    {
      id: 'needle_of_the_polar_star', name: 'Игла полярной звезды', rarity: 'epic', cooldown: 6, target: 'lowestHealthEnemy', projectile: 'frost',
      description: 'Атакует выбранного врага на 3d8 + Силу, игнорируя Защиту; щиты и полное блокирование продолжают работать. После удара получает Зимнюю сосредоточенность на 2 хода: Точность +3, Критический удар +2, даже при промахе. При автовыборе приоритет у врага с наименьшей долей здоровья.',
      actions: [{ type: 'damage', dice: '3d8', scaling: 'power', bypassArmor: true }, { type: 'status', statusId: 'winter_focus', duration: 2, target: 'self' }],
      tags: ['DAMAGE', 'PIERCE', 'BUFF'], icon: { frame: 'slash', motif: 'star', accent: 'crystal' },
    },
    {
      id: 'spring_beneath_the_glacier', name: 'Весна под ледником', rarity: 'epic', cooldown: 6, target: 'ally', projectile: 'frost',
      description: 'Лечит выбранного союзника на 3d6 + Силу и даёт Пульс оттепели на 3 хода: в конце хода лечение на 1d6 + Силу источника. Сам заклинатель получает Снежную пелену на 3 хода: Уклонение +3, Защита каждой части тела +2.',
      actions: [{ type: 'heal', dice: '3d6', scaling: 'power' }, { type: 'status', statusId: 'thawing_pulse', duration: 3 }, { type: 'status', statusId: 'snowveil', duration: 3, target: 'self' }],
      tags: ['HEAL', 'HOT', 'EVASION'], icon: { frame: 'orbit', motif: 'leaf', accent: 'crystal' },
    },
  ]),
  ...skillSchool('storm', 430, [
    {
      id: 'counsel_of_clear_skies', name: 'Совет ясного неба', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'lightning',
      description: 'На 2 хода даёт выбранному союзнику Ясность грозы: Точность +3, следующий бросок Инициативы +3. Уже определённая очередь ходов не меняется.',
      actions: [{ type: 'status', statusId: 'storm_clarity', duration: 2 }],
      tags: ['BUFF'], icon: { frame: 'seal', motif: 'eye', accent: 'bolt' },
    },
    {
      id: 'needle_of_ball_lightning', name: 'Игла шаровой молнии', rarity: 'common', cooldown: 4, target: 'randomEnemy', projectile: 'lightning',
      description: 'Одного случайного врага атакует на 1d12 без Силы, игнорируя Защиту. Попадание оставляет Статический заряд на 1 ход: Критический удар −1, в конце хода 1d4 урона с Защитой. Щиты продолжают защищать от обоих ударов.',
      actions: [{ type: 'damage', dice: '1d12', bypassArmor: true, onHitStatusId: 'static_charge', onHitDuration: 1 }],
      tags: ['RANDOM', 'PIERCE', 'DOT'], icon: { frame: 'slash', motif: 'bolt', accent: 'fang' },
    },
    {
      id: 'thunder_in_the_ribs', name: 'Гром в рёбрах', rarity: 'common', cooldown: 4, target: 'self', projectile: 'lightning',
      description: 'На 2 хода получает Грозовой панцирь: в начале собственного хода создаёт щит на 1d6 + Силу источника. Срок каждого слоя щита — 1 ход; в ход наложения аура не срабатывает.',
      actions: [{ type: 'status', statusId: 'thunder_shell', duration: 2 }],
      tags: ['SHIELD'], icon: { frame: 'ward', motif: 'bone', accent: 'bolt' },
    },
    {
      id: 'clap_above_the_helm', name: 'Раскат над шлемом', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'lightning',
      description: 'На 3 хода накладывает на выбранного врага Оглушительный раскат: Точность −2, следующий бросок Инициативы −2. Попадание не проверяется; действие врага и текущая очередь сохраняются.',
      actions: [{ type: 'status', statusId: 'deafening_roar', duration: 3 }],
      tags: ['DEBUFF'], icon: { frame: 'rays', motif: 'bolt', accent: 'shield' },
    },
    {
      id: 'two_beats_of_thunder', name: 'Два удара грома', rarity: 'common', cooldown: 2, target: 'enemy', projectile: 'lightning',
      description: 'Дважды атакует выбранного врага. Каждый удар независимо проверяет попадание и крит и наносит 1d4 + половину Силы. После гибели цели оставшийся удар не переносится.',
      actions: [{ type: 'damage', dice: '1d4', scaling: 'power', factor: .5, hits: 2 }],
      tags: ['MULTIHIT', 'DAMAGE'], icon: { frame: 'arrows', motif: 'bolt', accent: 'bone' },
    },
    {
      id: 'weather_vanes_judgement', name: 'Решение флюгера', rarity: 'common', cooldown: 4, target: 'randomUnit', projectile: 'lightning',
      description: 'Кубик выбирает одного живого участника. Союзнику даёт щит на 2d6 + Силу на 2 хода. Врагу наносит удар на 2d6 + Силу; попадание даёт Проводящую метку на 1 ход: Защита −4, Точность −1.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 2, targetRelation: 'ally' }, { type: 'damage', dice: '2d6', scaling: 'power', targetRelation: 'enemy', onHitStatusId: 'conductive_brand', onHitDuration: 1 }],
      tags: ['RANDOM', 'HYBRID', 'SHIELD'], icon: { frame: 'orbit', motif: 'feather', accent: 'eye' },
    },
    {
      id: 'breath_before_the_gale', name: 'Вдох перед шквалом', rarity: 'common', cooldown: 4, target: 'lowestHealthAlly', projectile: 'lightning',
      description: 'Лечит выбранного союзника на 1d10 + Силу. Сам заклинатель получает Поступь бури на 1 ход: Уклонение и Проворность +3. При автовыборе приоритет у наиболее раненого союзника.',
      actions: [{ type: 'heal', dice: '1d10', scaling: 'power' }, { type: 'status', statusId: 'storm_stride', duration: 1, target: 'self' }],
      tags: ['HEAL', 'EVASION'], icon: { frame: 'weave', motif: 'cross', accent: 'bolt' },
    },
    {
      id: 'march_on_the_tailwind', name: 'Марш по ветру', rarity: 'rare', cooldown: 5, target: 'allAllies', projectile: 'lightning',
      description: 'Весь отряд на 2 хода получает Поступь бури: Уклонение +3, Проворность +3. Бонус действует на каждого союзника, включая заклинателя.',
      actions: [{ type: 'status', statusId: 'storm_stride', duration: 2 }],
      tags: ['MASS', 'EVASION'], icon: { frame: 'rays', motif: 'feather', accent: 'bolt' },
    },
    {
      id: 'lightning_rods_challenge', name: 'Вызов громоотвода', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'lightning',
      description: 'Сначала накладывает на врага Проводящую метку на 3 хода (Защита −4, Точность −1), затем атакует на 2d6 + Силу. После этого получает Ясность грозы на 2 хода (Точность +3, следующая Инициатива +3). Обе ауры сохраняются при промахе; текущая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'conductive_brand', duration: 3 }, { type: 'damage', dice: '2d6', scaling: 'power' }, { type: 'status', statusId: 'storm_clarity', duration: 2, target: 'self' }],
      tags: ['DAMAGE', 'DEBUFF', 'BUFF'], icon: { frame: 'seal', motif: 'bolt', accent: 'eye' },
    },
    {
      id: 'storm_forged_armament', name: 'Вооружение грозы', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'lightning',
      description: 'Создаёт на союзнике щит на 1d8 + Силу на 2 хода. Даёт Заряженное острие на 3 хода: дополнительный 1d6 к каждому прямому удару, Точность +1.',
      actions: [{ type: 'shield', dice: '1d8', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'charged_edge', duration: 3 }],
      tags: ['SHIELD', 'BUFF'], icon: { frame: 'ward', motif: 'blade', accent: 'bolt' },
    },
    {
      id: 'keeper_of_the_calm_center', name: 'Хранитель тихого центра', rarity: 'rare', cooldown: 5, target: 'self', projectile: 'lightning',
      description: 'На 2 хода получает Око бури: уменьшает оставшийся урон прямых ударов по отряду на 1d6, своя Проворность −1. На 2 хода получает Грозовой панцирь: в начале хода создаёт щит на 1d6 + Силу источника со сроком 1 ход.',
      actions: [{ type: 'status', statusId: 'eye_of_storm', duration: 2 }, { type: 'status', statusId: 'thunder_shell', duration: 2 }],
      tags: ['PARTY_GUARD', 'SHIELD'], icon: { frame: 'orbit', motif: 'eye', accent: 'shield' },
    },
    {
      id: 'harvest_of_static', name: 'Жатва разрядов', rarity: 'rare', cooldown: 5, target: 'allEnemies', projectile: 'lightning',
      description: 'Без проверки попадания каждому врагу даёт Статический заряд на 2 хода: Критический удар −1, в конце хода 1d4 урона без Силы с учётом Защиты. Затем лечит заклинателя на 2d6 без Силы.',
      actions: [{ type: 'status', statusId: 'static_charge', duration: 2 }, { type: 'heal', dice: '2d6', target: 'self' }],
      tags: ['MASS', 'DOT', 'HEAL'], icon: { frame: 'weave', motif: 'bolt', accent: 'drop' },
    },
    {
      id: 'herald_of_the_high_tempest', name: 'Вестник высшей бури', rarity: 'epic', cooldown: 7, target: 'ally', projectile: 'lightning',
      description: 'Даёт союзнику щит на 2d8 + Силу на 2 хода. На 3 хода — Ясность грозы (Точность +3, следующая Инициатива +3) и Порыв шквала (следующая Инициатива +1; после действия с уроном 1d8, на 6+ повтор базовой атаки по той же живой цели). Текущая очередь не меняется.',
      actions: [{ type: 'shield', dice: '2d8', scaling: 'power', duration: 2 }, { type: 'status', statusId: 'storm_clarity', duration: 3 }, { type: 'status', statusId: 'tempest_surge', duration: 3 }],
      tags: ['SHIELD', 'BUFF', 'REPEAT'], icon: { frame: 'rays', motif: 'star', accent: 'bolt' },
    },
    {
      id: 'front_of_the_black_storm', name: 'Фронт чёрной грозы', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'lightning',
      description: 'Каждому врагу — удар на 2d6 + половину Силы. Попадание даёт Оглушительный раскат на 3 хода: Точность и следующая Инициатива −2, текущая очередь не меняется. Каждому союзнику создаёт щит на 1d6 + половину Силы на 1 ход, независимо от попаданий.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', factor: .5, onHitStatusId: 'deafening_roar', onHitDuration: 3 }, { type: 'shield', dice: '1d6', scaling: 'power', factor: .5, duration: 1, target: 'allAllies' }],
      tags: ['MASS', 'DAMAGE', 'SHIELD'], icon: { frame: 'burst', motif: 'bolt', accent: 'moon' },
    },
    {
      id: 'quarrel_of_four_lightnings', name: 'Спор четырёх молний', rarity: 'epic', cooldown: 8, target: 'randomEnemy', projectile: 'lightning',
      description: 'Сначала получает Заряженное острие на 2 хода: Точность +1, дополнительный 1d6 к каждому прямому удару. Затем по одному случайному врагу — четыре независимых удара на 1d6 без Силы. Попадания обновляют Проводящую метку на 2 хода (Защита −4, Точность −1). Новое острие усиливает эти удары; переноса цели нет.',
      actions: [{ type: 'status', statusId: 'charged_edge', duration: 2, target: 'self' }, { type: 'damage', dice: '1d6', hits: 4, onHitStatusId: 'conductive_brand', onHitDuration: 2 }],
      tags: ['RANDOM', 'MULTIHIT', 'DEBUFF'], icon: { frame: 'arrows', motif: 'bolt', accent: 'crystal' },
    },
  ]),
  ...skillSchool('stone', 445, [
    {
      id: 'granite_masons_blessing', name: 'Благословение каменотёса', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'stone',
      description: 'На 2 хода даёт союзнику Гранитную кожу: Защита каждой части тела +9, следующая Инициатива −3. Текущая очередь ходов не меняется.',
      actions: [{ type: 'status', statusId: 'granite_skin', duration: 2 }],
      tags: ['ARMOR', 'TRADEOFF'], icon: { frame: 'ward', motif: 'rock', accent: 'blade' },
    },
    {
      id: 'mossbound_bandage', name: 'Повязка из курганного мха', rarity: 'common', cooldown: 3, target: 'lowestHealthAlly', projectile: 'stone',
      description: 'Лечит выбранного союзника на 2d6 без Силы и даёт ему Мох веков на 1 ход: в начале собственного хода восстанавливает ещё 1d10 без Силы. В ход наложения аура не срабатывает. При автовыборе приоритет у наиболее раненого союзника.',
      actions: [{ type: 'heal', dice: '2d6' }, { type: 'status', statusId: 'moss_of_ages', duration: 1 }],
      tags: ['HEAL', 'HOT'], icon: { frame: 'weave', motif: 'leaf', accent: 'bone' },
    },
    {
      id: 'burial_of_the_boots', name: 'Погребение сапог', rarity: 'common', cooldown: 3, target: 'enemy', projectile: 'stone',
      description: 'Сначала накладывает Оковы земли на 3 хода: Уклонение −2, следующая Инициатива −5; текущая очередь не меняется. Затем атакует на 1d4 + Силу. Оковы остаются при промахе и не лишают врага действия.',
      actions: [{ type: 'status', statusId: 'earthbound', duration: 3 }, { type: 'damage', dice: '1d4', scaling: 'power' }],
      tags: ['DAMAGE', 'DEBUFF'], icon: { frame: 'seal', motif: 'rock', accent: 'bone' },
    },
    {
      id: 'pebbles_in_orbit', name: 'Круг гальки', rarity: 'common', cooldown: 4, target: 'self', projectile: 'stone',
      description: 'На 2 хода получает Гравийный заслон. В начале собственного хода аура создаёт щит на 2d6 без Силы со сроком 1 ход. В ход наложения щит ещё не появляется.',
      actions: [{ type: 'status', statusId: 'gravel_guard', duration: 2 }],
      tags: ['SHIELD'], icon: { frame: 'orbit', motif: 'rock', accent: 'shield' },
    },
    {
      id: 'shale_lottery', name: 'Сланцевый жребий', rarity: 'common', cooldown: 3, target: 'randomEnemy', projectile: 'stone',
      description: 'Один случайный враг без проверки попадания получает Каменные занозы на 3 хода: в конце собственного хода — 1d8 урона без Силы с учётом Защиты.',
      actions: [{ type: 'status', statusId: 'splintered_stone', duration: 3 }],
      tags: ['RANDOM', 'DOT'], icon: { frame: 'arrows', motif: 'rock', accent: 'fang' },
    },
    {
      id: 'two_faces_of_flint', name: 'Две грани кремня', rarity: 'common', cooldown: 3, target: 'any', projectile: 'stone',
      description: 'Союзнику, включая себя, создаёт щит на 2d4 + Силу на 2 хода. Врага вместо этого атакует на 2d4 + Силу без Защиты; щиты и полное блокирование продолжают защищать.',
      actions: [{ type: 'shield', dice: '2d4', scaling: 'power', duration: 2, targetRelation: 'ally' }, { type: 'damage', dice: '2d4', scaling: 'power', bypassArmor: true, targetRelation: 'enemy' }],
      tags: ['HYBRID', 'SHIELD', 'PIERCE'], icon: { frame: 'slash', motif: 'rock', accent: 'rune' },
    },
    {
      id: 'surveyors_fault_mark', name: 'Метка землемера', rarity: 'common', cooldown: 4, target: 'enemy', projectile: 'stone',
      description: 'Без проверки попадания накладывает Линию разлома на выбранного врага на 2 хода: Защита каждой части тела −8, Проворность −1.',
      actions: [{ type: 'status', statusId: 'fault_line', duration: 2 }],
      tags: ['DEBUFF'], icon: { frame: 'rays', motif: 'eye', accent: 'rock' },
    },
    {
      id: 'avalanche_bearers_draught', name: 'Глоток несущего лавину', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'stone',
      description: 'Лечит союзника на 1d8 + Силу. На 3 хода даёт Намерение лавины: дополнительный 1d8 к каждому прямому удару, Критический удар +2, Точность −2.',
      actions: [{ type: 'heal', dice: '1d8', scaling: 'power' }, { type: 'status', statusId: 'avalanche_intent', duration: 3 }],
      tags: ['HEAL', 'BUFF', 'TRADEOFF'], icon: { frame: 'seal', motif: 'drop', accent: 'rock' },
    },
    {
      id: 'challenge_from_the_crag', name: 'Вызов с утёса', rarity: 'rare', cooldown: 5, target: 'self', projectile: 'stone',
      description: 'На 2 хода получает Вызов и Решимость горы: враги обязаны атаковать заклинателя, оставшийся после Защиты входящий урон −5, Проворность −2. При нескольких провокациях действует последняя. Урон без Защиты обходит это уменьшение.',
      actions: [{ type: 'status', statusId: 'taunted', duration: 2 }, { type: 'status', statusId: 'mountain_resolve', duration: 2 }],
      tags: ['TAUNT', 'GUARD'], icon: { frame: 'ward', motif: 'rock', accent: 'claw' },
    },
    {
      id: 'shelter_of_the_old_quarry', name: 'Укрытие старой каменоломни', rarity: 'rare', cooldown: 5, target: 'allAllies', projectile: 'stone',
      description: 'Каждому союзнику создаёт щит на 1d6 + половину Силы на 2 хода. Даёт всему отряду Мох веков на 1 ход: в начале собственного хода каждого — лечение на 1d10 без Силы. В ход наложения аура не срабатывает.',
      actions: [{ type: 'shield', dice: '1d6', scaling: 'power', factor: .5, duration: 2 }, { type: 'status', statusId: 'moss_of_ages', duration: 1 }],
      tags: ['MASS', 'SHIELD', 'HOT'], icon: { frame: 'weave', motif: 'shield', accent: 'leaf' },
    },
    {
      id: 'cairn_breakers_swing', name: 'Размах крушителя курганов', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'stone',
      description: 'Атакует врага на 2d6 + Силу; попадание оставляет Каменные занозы на 2 хода: 1d8 урона с учётом Защиты в конце хода. После удара получает Благословение кургана на 2 хода: Защита +4, Сила +3, даже при промахе; первый удар этот бонус ещё не получает.',
      actions: [{ type: 'damage', dice: '2d6', scaling: 'power', onHitStatusId: 'splintered_stone', onHitDuration: 2 }, { type: 'status', statusId: 'cairn_blessing', duration: 2, target: 'self' }],
      tags: ['DAMAGE', 'DOT', 'BUFF'], icon: { frame: 'slash', motif: 'rock', accent: 'cross' },
    },
    {
      id: 'oath_of_the_boundary_stone', name: 'Обет межевого камня', rarity: 'rare', cooldown: 5, target: 'any', projectile: 'stone',
      description: 'Союзнику даёт щит на 2d6 + Силу на 2 хода и Гранитную кожу на 3 хода (Защита +9, следующая Инициатива −3). Врагу без проверки попадания на 3 хода — Оковы земли (Уклонение −2, следующая Инициатива −5) и Каменные занозы (1d8 урона с Защитой в конце хода). Текущая очередь не меняется.',
      actions: [{ type: 'shield', dice: '2d6', scaling: 'power', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'granite_skin', duration: 3, targetRelation: 'ally' }, { type: 'status', statusId: 'earthbound', duration: 3, targetRelation: 'enemy' }, { type: 'status', statusId: 'splintered_stone', duration: 3, targetRelation: 'enemy' }],
      tags: ['HYBRID', 'SHIELD', 'DOT'], icon: { frame: 'orbit', motif: 'rune', accent: 'rock' },
    },
    {
      id: 'liturgy_of_the_deep_earth', name: 'Литургия глубин земли', rarity: 'epic', cooldown: 7, target: 'allAllies', projectile: 'stone',
      description: 'На 3 хода весь отряд получает Благословение кургана (Защита каждой части тела +4, Сила +3) и Мох веков: в начале собственного хода каждого союзника — лечение на 1d10 без Силы. При применении лечения нет.',
      actions: [{ type: 'status', statusId: 'cairn_blessing', duration: 3 }, { type: 'status', statusId: 'moss_of_ages', duration: 3 }],
      tags: ['MASS', 'BUFF', 'HOT'], icon: { frame: 'rays', motif: 'cross', accent: 'rock' },
    },
    {
      id: 'hammer_beneath_the_mountain', name: 'Молот под горой', rarity: 'epic', cooldown: 6, target: 'enemy', projectile: 'stone',
      description: 'Удар на 4d6 + Силу. При попадании — Линия разлома на 3 хода: Защита −8, Проворность −1. Заклинатель получает Решимость горы на 2 хода независимо от попадания: урон после Защиты −5, Проворность −2; урон без Защиты обходит это уменьшение.',
      actions: [{ type: 'damage', dice: '4d6', scaling: 'power', onHitStatusId: 'fault_line', onHitDuration: 3 }, { type: 'status', statusId: 'mountain_resolve', duration: 2, target: 'self' }],
      tags: ['DAMAGE', 'DEBUFF', 'GUARD'], icon: { frame: 'burst', motif: 'rock', accent: 'blade' },
    },
    {
      id: 'circle_of_walking_boulders', name: 'Круг шагающих валунов', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'stone',
      description: 'Каждому врагу без проверки попадания даёт Каменные занозы на 2 хода: 1d8 урона с Защитой в конце хода. Сам получает на 3 хода Укрытие монолита (своя Защита +2, урон после Защиты по отряду −3) и Гравийный заслон (в начале хода щит на 2d6 со сроком 1 ход). Периодические кубики не прибавляют Силу.',
      actions: [{ type: 'status', statusId: 'splintered_stone', duration: 2 }, { type: 'status', statusId: 'sheltering_monolith', duration: 3, target: 'self' }, { type: 'status', statusId: 'gravel_guard', duration: 3, target: 'self' }],
      tags: ['MASS', 'DOT', 'PARTY_GUARD', 'SHIELD'], icon: { frame: 'arrows', motif: 'rock', accent: 'hourglass' },
    },
  ]),
  ...skillSchool('metal', 460, [
    {
      id: 'barbers_silver_oath', name: 'Серебряный обет брадобрея', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'arrow',
      description: 'Даёт выбранному союзнику Бритвенную грань на 2 хода: Критический удар +4, броски урона +1.',
      actions: [{ type: 'status', statusId: 'razor_edge', duration: 2 }],
      tags: ['BUFF', 'CRIT'], icon: { frame: 'slash', motif: 'blade', accent: 'eye' },
    },
    {
      id: 'lodestones_embrace', name: 'Объятие магнитного камня', rarity: 'common', cooldown: 3, target: 'ally', projectile: 'stone',
      description: 'На 2 хода даёт союзнику Магнитный покров: Уклонение +2, Защита каждой части тела +4.',
      actions: [{ type: 'status', statusId: 'magnetic_ward', duration: 2 }],
      tags: ['ARMOR', 'EVASION'], icon: { frame: 'orbit', motif: 'shield', accent: 'rock' },
    },
    {
      id: 'twin_barbs_of_the_trap', name: 'Два зубца капкана', rarity: 'common', cooldown: 4, target: 'enemy', projectile: 'arrow',
      description: 'Два независимых удара по одному врагу, каждый на 1d4 без Силы. Каждое попадание оставляет отдельные Зазубренные оковы на 1 ход: Проворность −3 и 1d4 урона без Защиты в конце хода за заряд.',
      actions: [{ type: 'damage', dice: '1d4', hits: 2, onHitStatusId: 'barbed_shackles', onHitDuration: 1 }],
      tags: ['MULTIHIT', 'BLEED'], icon: { frame: 'arrows', motif: 'fang', accent: 'blade' },
    },
    {
      id: 'anvils_lottery', name: 'Жребий наковальни', rarity: 'common', cooldown: 3, target: 'randomEnemy', projectile: 'stone',
      description: 'Атакует одного случайного врага на 3d6 + Силу. Попадание и критический удар проверяются отдельно; других эффектов удар не накладывает.',
      actions: [{ type: 'damage', dice: '3d6', scaling: 'power' }],
      tags: ['RANDOM', 'DAMAGE'], icon: { frame: 'burst', motif: 'rock', accent: 'blade' },
    },
    {
      id: 'smiths_second_breath', name: 'Второе дыхание кузнеца', rarity: 'common', cooldown: 4, target: 'self', projectile: 'stone',
      description: 'Восстанавливает себе 1d6 + Силу здоровья. На 2 хода получает Закалённую волю: Точность +2, Защита каждой части тела +3, Критический удар +1.',
      actions: [{ type: 'heal', dice: '1d6', scaling: 'power' }, { type: 'status', statusId: 'tempered_will', duration: 2 }],
      tags: ['HEAL', 'BUFF'], icon: { frame: 'seal', motif: 'cross', accent: 'blade' },
    },
    {
      id: 'rain_of_rust_dust', name: 'Дождь ржавой пыли', rarity: 'common', cooldown: 4, target: 'allEnemies', projectile: 'arrow',
      description: 'Без проверки попадания накладывает Ржавчину на всех врагов на 1 собственный ход каждого: Защита каждой части тела −5, броски урона −2.',
      actions: [{ type: 'status', statusId: 'rust', duration: 1 }],
      tags: ['MASS', 'DEBUFF'], icon: { frame: 'rays', motif: 'drop', accent: 'blade' },
    },
    {
      id: 'forgemasters_touch', name: 'Касание мастера горна', rarity: 'common', cooldown: 3, target: 'any', projectile: 'stone',
      description: 'Союзнику даёт Стальную кожу на 2 хода: Защита каждой части тела +5. Врагу вместо этого накладывает Ржавчину на 2 хода: Защита −5, броски урона −2. Попадание не проверяется; можно выбрать себя.',
      actions: [{ type: 'status', statusId: 'steel_skin', duration: 2, targetRelation: 'ally' }, { type: 'status', statusId: 'rust', duration: 2, targetRelation: 'enemy' }],
      tags: ['HYBRID', 'ARMOR', 'DEBUFF'], icon: { frame: 'weave', motif: 'blade', accent: 'rune' },
    },
    {
      id: 'riveters_procession', name: 'Шествие заклёпщиков', rarity: 'rare', cooldown: 5, target: 'allAllies', projectile: 'stone',
      description: 'Весь отряд получает Стальную кожу на 2 хода: Защита каждой части тела +5. Каждый союзник также получает щит на 1d4 + половину Силы заклинателя сроком 1 ход.',
      actions: [{ type: 'status', statusId: 'steel_skin', duration: 2 }, { type: 'shield', dice: '1d4', scaling: 'power', factor: .5, duration: 1 }],
      tags: ['MASS', 'SHIELD', 'ARMOR'], icon: { frame: 'ward', motif: 'shield', accent: 'blade' },
    },
    {
      id: 'mercury_cutters_stance', name: 'Стойка ртутного резчика', rarity: 'rare', cooldown: 5, target: 'self', projectile: 'arrow',
      description: 'На 2 хода получает Ртутный шаг (Проворность +5, следующая Инициатива +2, Защита −2), на 3 хода — Бритвенную грань (Критический удар +4, броски урона +1). Текущая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'mercury_step', duration: 2 }, { type: 'status', statusId: 'razor_edge', duration: 3 }],
      tags: ['BUFF', 'CRIT', 'TRADEOFF'], icon: { frame: 'orbit', motif: 'drop', accent: 'blade' },
    },
    {
      id: 'hook_of_the_iron_gaoler', name: 'Крюк железного тюремщика', rarity: 'rare', cooldown: 5, target: 'enemy', projectile: 'arrow',
      description: 'Сначала накладывает Ржавчину на 3 хода (Защита −5, броски урона −2), затем атакует на 2d6 + Силу. Попадание оставляет Зазубренные оковы на 2 хода: Проворность −3, в конце хода 1d4 урона без Защиты. Ржавчина остаётся при промахе.',
      actions: [{ type: 'status', statusId: 'rust', duration: 3 }, { type: 'damage', dice: '2d6', scaling: 'power', onHitStatusId: 'barbed_shackles', onHitDuration: 2 }],
      tags: ['DAMAGE', 'DEBUFF', 'BLEED'], icon: { frame: 'slash', motif: 'fang', accent: 'shield' },
    },
    {
      id: 'lotus_of_tempered_iron', name: 'Лотос закалённого железа', rarity: 'rare', cooldown: 5, target: 'randomAlly', projectile: 'stone',
      description: 'Одному случайному союзнику на 3 хода даёт Железный цветок (в начале хода щит на 1d10 без Силы со сроком 2 хода) и Закалённую волю: Точность +2, Защита +3, Критический удар +1.',
      actions: [{ type: 'status', statusId: 'iron_bloom', duration: 3 }, { type: 'status', statusId: 'tempered_will', duration: 3 }],
      tags: ['RANDOM', 'SHIELD', 'BUFF'], icon: { frame: 'seal', motif: 'leaf', accent: 'blade' },
    },
    {
      id: 'surgeon_of_silver_threads', name: 'Хирург серебряных нитей', rarity: 'rare', cooldown: 5, target: 'ally', projectile: 'stone',
      description: 'Лечит союзника на 2d6 + Силу и даёт Магнитный покров на 3 хода: Уклонение +2, Защита +4. Сам заклинатель получает Стальную кожу на 2 хода: Защита каждой части тела +5.',
      actions: [{ type: 'heal', dice: '2d6', scaling: 'power' }, { type: 'status', statusId: 'magnetic_ward', duration: 3 }, { type: 'status', statusId: 'steel_skin', duration: 2, target: 'self' }],
      tags: ['HEAL', 'EVASION', 'ARMOR'], icon: { frame: 'weave', motif: 'cross', accent: 'shield' },
    },
    {
      id: 'last_nail_of_the_citadel', name: 'Последний гвоздь цитадели', rarity: 'epic', cooldown: 6, target: 'enemy', projectile: 'arrow',
      description: 'Один удар на 4d6 + Силу, игнорирующий Защиту. При попадании накладывает Ржавчину на 3 хода: Защита каждой части тела −5, броски урона −2. Щиты и полное блокирование продолжают защищать от удара.',
      actions: [{ type: 'damage', dice: '4d6', scaling: 'power', bypassArmor: true, onHitStatusId: 'rust', onHitDuration: 3 }],
      tags: ['DAMAGE', 'PIERCE', 'DEBUFF'], icon: { frame: 'arrows', motif: 'blade', accent: 'rock' },
    },
    {
      id: 'garden_of_flying_shrapnel', name: 'Сад летящей шрапнели', rarity: 'epic', cooldown: 7, target: 'allEnemies', projectile: 'arrow',
      description: 'По каждому врагу — три независимых удара, каждый на 1d4 без Силы. Каждое попадание оставляет отдельные Зазубренные оковы на 1 ход: Проворность −3, в конце хода 1d4 урона без Защиты за каждый заряд. Удары не переходят с погибшей цели на другую.',
      actions: [{ type: 'damage', dice: '1d4', hits: 3, onHitStatusId: 'barbed_shackles', onHitDuration: 1 }],
      tags: ['MASS', 'MULTIHIT', 'BLEED'], icon: { frame: 'burst', motif: 'blade', accent: 'leaf' },
    },
    {
      id: 'anthem_of_the_whetstone', name: 'Гимн точильного камня', rarity: 'epic', cooldown: 7, target: 'allAllies', projectile: 'stone',
      description: 'На 3 хода заклинатель получает Железный хор: уменьшает оставшийся урон прямых ударов по отряду на 1d8, следующая Инициатива −3. Всем союзникам — щит на 2d4 + половину Силы на 2 хода и Бритвенная грань на 2 хода (Критический удар +4, броски урона +1). Текущая очередь не меняется.',
      actions: [{ type: 'status', statusId: 'iron_chorus', duration: 3, target: 'self' }, { type: 'shield', dice: '2d4', scaling: 'power', factor: .5, duration: 2 }, { type: 'status', statusId: 'razor_edge', duration: 2 }],
      tags: ['MASS', 'PARTY_GUARD', 'SHIELD', 'CRIT'], icon: { frame: 'rays', motif: 'rune', accent: 'blade' },
    },
  ]),
];
