import { auraGroup, buff, tick } from './status-catalog-builders';

export const mysticAuras = [
  ...auraGroup('venom', 1, [
    tick('toxic_corrosion', 'Ядовитая коррозия', 'damage', '1d4', 'TURN_ENDED', { modifiers: { armorBonus: -3 }, visual: { form: 'rain', motion: 'zigzag', motif: 'drop' } }),
    buff('venom_fever', 'Ядовитая лихорадка', { initiativeBonus: -2, powerBonus: -4 }, { polarity: 'negative', visual: { form: 'mist', motion: 'pulse', motif: 'fang' } }),
    buff('serpent_focus', 'Взгляд змея', { critBonus: 3, accuracyBonus: 2 }, { visual: { form: 'eyes', motion: 'breathe', motif: 'fang' } }),
    tick('bitter_balm', 'Горький бальзам', 'heal', '1d6', 'TURN_STARTED', { healingScale: true, visual: { form: 'roots', motion: 'rise', motif: 'leaf' } }),
    buff('venom_coating', 'Ядовитое покрытие', { damageBonusDice: '1d6' }, { stacking: 'independent', visual: { form: 'arcs', motion: 'pulse', motif: 'fang' } }),
    buff('nauseating_haze', 'Тошнотворная дымка', { critBonus: -3, agilityBonus: -3 }, { polarity: 'negative', visual: { form: 'vortex', motion: 'breathe', motif: 'skull' } }),
    tick('virulent_breath', 'Гибельное дыхание', 'damage', '1d8', 'TURN_STARTED', { bypassArmor: true, duration: 2, visual: { form: 'flames', motion: 'spiral', motif: 'fang' } }),
    tick('spore_mantle', 'Споровая мантия', 'shield', '1d4', 'TURN_STARTED', { healingScale: true, visual: { form: 'halo', motion: 'rise', motif: 'leaf' } }),
    buff('venom_hunger', 'Змеиный голод', { vampirismDice: '1d6', armorBonus: -2 }, { visual: { form: 'crown', motion: 'zigzag', motif: 'fang' } }),
  ]),
  ...auraGroup('spirit', 0, [
    tick('soul_mending', 'Заживление души', 'heal', '2d4', 'TURN_ENDED', { healingScale: true, visual: { form: 'waves', motion: 'spiral', motif: 'wisp' } }),
    tick('bone_cyclone', 'Костяной смерч', 'shield', '1d8', 'TURN_STARTED', { shieldDuration: 2, visual: { form: 'vortex', motion: 'spiral', motif: 'bone', count: 14, radius: 18, height: 44, speed: 1.25 } }),
    buff('ancestral_guard', 'Дозор предков', { partyGuardDice: '1d6' }, { visual: { form: 'orbit', motion: 'pulse', motif: 'skull' } }),
    tick('pale_rebuke', 'Бледное возмездие', 'damage', '1d6', 'TURN_ENDED', { bypassArmor: true, visual: { form: 'rain', motion: 'rise', motif: 'wisp' } }),
    buff('soul_lantern', 'Фонарь души', { powerBonus: 5, initiativeBonus: 1 }, { visual: { form: 'halo', motion: 'breathe', motif: 'wisp' } }),
    buff('ghost_step', 'Призрачный шаг', { evasionBonus: 4, armorBonus: -3 }, { visual: { form: 'feathers', motion: 'zigzag', motif: 'bone' } }),
    buff('funeral_lament', 'Погребальный плач', { accuracyBonus: -2, critBonus: -2 }, { polarity: 'negative', visual: { form: 'wings', motion: 'fall', motif: 'skull' } }),
    buff('spirit_echo', 'Эхо духа', { repeatAttack: { dice: '1d6', atLeast: 5 }, powerBonus: 1 }, { visual: { form: 'eyes', motion: 'rise', motif: 'wisp' } }),
    buff('ossuary_pact', 'Завет оссуария', { preserveShield: { dice: '1d8', atLeast: 6 }, armorBonus: 2 }, { visual: { form: 'chains', motion: 'breathe', motif: 'bone' } }),
    tick('last_warmth', 'Последнее тепло', 'heal', '1d12', 'TURN_STARTED', { duration: 2, visual: { form: 'embers', motion: 'breathe', motif: 'wisp' } }),
  ]),
  ...auraGroup('time', 0, [
    buff('haste', 'Ускорение', { agilityBonus: 3, evasionBonus: 2 }, { visual: { form: 'arcs', motion: 'orbit', motif: 'hourglass' } }),
    buff('temporal_drag', 'Вязкое время', { initiativeBonus: -5, accuracyBonus: -1 }, { polarity: 'negative', visual: { form: 'chains', motion: 'breathe', motif: 'hourglass' } }),
    buff('borrowed_moment', 'Заимствованный миг', { repeatAttack: { dice: '1d4', atLeast: 4 }, agilityBonus: 2 }, { duration: 2, visual: { form: 'orbit', motion: 'zigzag', motif: 'hourglass' } }),
    buff('fading_second', 'Ускользающая секунда', { evasionBonus: 5, critBonus: -2 }, { visual: { form: 'mist', motion: 'pulse', motif: 'hourglass' } }),
    tick('hourglass_mending', 'Пески восстановления', 'heal', '1d6', 'TURN_ENDED', { healingScale: true, duration: 4, visual: { form: 'rain', motion: 'fall', motif: 'hourglass' } }),
    buff('renewed_thread', 'Обновлённая нить', { preserveHot: { dice: '1d4', atLeast: 4 }, powerBonus: 1 }, { visual: { form: 'runes', motion: 'spiral', motif: 'hourglass' } }),
    tick('chronal_erosion', 'Эрозия мгновений', 'damage', '1d6', 'TURN_STARTED', { bypassArmor: true, visual: { form: 'shards', motion: 'fall', motif: 'hourglass' } }),
    tick('suspended_barrier', 'Застывший барьер', 'shield', '1d6', 'TURN_ENDED', { shieldDuration: 2, visual: { form: 'dome', motion: 'orbit', motif: 'hourglass' } }),
    buff('measured_strike', 'Выверенный удар', { accuracyBonus: 5, initiativeBonus: -3 }, { visual: { form: 'sigil', motion: 'pulse', motif: 'hourglass' } }),
    buff('last_instant', 'Последнее мгновение', { agilityBonus: 6, evasionBonus: 1 }, { duration: 2, visual: { form: 'wings', motion: 'rise', motif: 'hourglass' } }),
  ]),
  ...auraGroup('war', 2, [
    buff('rage', 'Ярость', { critBonus: 5, accuracyBonus: -3 }, { visual: { form: 'flames', motion: 'pulse', motif: 'claw', count: 12, radius: 16, height: 38, speed: 1.4 } }),
    buff('battle_trance', 'Боевой транс', { accuracyBonus: 2, damageBonus: 3, evasionBonus: -2 }, { visual: { form: 'eyes', motion: 'pulse', motif: 'claw' } }),
    buff('vanguard', 'Авангард', { initiativeBonus: 3, armorBonus: 3 }, { visual: { form: 'arcs', motion: 'rise', motif: 'shield' } }),
    buff('rallying_standard', 'Знамя сплочения', { partyGuardDice: '1d4', powerBonus: 2 }, { visual: { form: 'wings', motion: 'breathe', motif: 'shield' } }),
    buff('duelists_mark', 'Метка дуэлянта', { accuracyBonus: 3, critBonus: 3 }, { visual: { form: 'sigil', motion: 'zigzag', motif: 'blade' } }),
    buff('battle_fatigue', 'Боевое истощение', { damageBonus: -3, evasionBonus: -2, initiativeBonus: -2 }, { polarity: 'negative', visual: { form: 'embers', motion: 'fall', motif: 'claw' } }),
    buff('unyielding_oath', 'Клятва несгибаемого', { taunt: true, armorBonus: 5 }, { visual: { form: 'crown', motion: 'breathe', motif: 'shield' } }),
    buff('executioners_zeal', 'Рвение палача', { critBonus: 4, damageBonusDice: '1d6', powerBonus: -3 }, { duration: 2, visual: { form: 'spikes', motion: 'rise', motif: 'blade' } }),
  ]),
  ...auraGroup('astral', 0, [
    buff('lunar_grace', 'Лунная благодать', { evasionBonus: 3, powerBonus: 3 }, { visual: { form: 'halo', motion: 'orbit', motif: 'moon' } }),
    buff('stellar_precision', 'Звёздная точность', { accuracyBonus: 4, critBonus: 1 }, { visual: { form: 'eyes', motion: 'spiral', motif: 'star' } }),
    tick('comet_wake', 'След кометы', 'damage', '2d4', 'TURN_ENDED', { bypassArmor: true, visual: { form: 'rain', motion: 'zigzag', motif: 'star' } }),
    tick('constellation_guard', 'Страж созвездий', 'shield', '2d4', 'TURN_STARTED', { healingScale: true, visual: { form: 'runes', motion: 'orbit', motif: 'star' } }),
    tick('moonwell', 'Лунный источник', 'heal', '1d8', 'TURN_ENDED', { healingScale: true, visual: { form: 'waves', motion: 'breathe', motif: 'moon' } }),
    buff('eclipse', 'Затмение', { accuracyBonus: -3, powerBonus: -4 }, { polarity: 'negative', visual: { form: 'dome', motion: 'breathe', motif: 'moon' } }),
    buff('starfire_blade', 'Клинок звёздного огня', { damageBonusDice: '1d8', critBonus: 1 }, { visual: { form: 'flames', motion: 'spiral', motif: 'star' } }),
    buff('orbiting_fate', 'Орбиты судьбы', { repeatAttack: { dice: '1d8', atLeast: 7 }, accuracyBonus: 2 }, { visual: { form: 'orbit', motion: 'pulse', motif: 'moon' } }),
    buff('celestial_resonance', 'Небесный резонанс', { healingShareDice: '1d4', preserveHot: { dice: '1d6', atLeast: 6 } }, { visual: { form: 'crown', motion: 'rise', motif: 'star' } }),
    buff('void_chill', 'Холод пустоты', { armorBonus: -4, critBonus: -3, agilityBonus: -2 }, { polarity: 'negative', visual: { form: 'vortex', motion: 'fall', motif: 'moon' } }),
  ]),
];
