import { auraGroup, buff, tick } from './status-catalog-builders';

export const elementalAuras = [
  ...auraGroup('fire', 1, [
    tick('smoldering', 'Тление', 'damage', '1d6', 'TURN_ENDED', { visual: { form: 'embers', motion: 'rise', motif: 'flame' } }),
    buff('cinder_skin', 'Угольная кожа', { armorBonus: 3, damageBonusDice: '1d4' }, { visual: { form: 'shards', motion: 'pulse', motif: 'rock' } }),
    tick('furnace_heart', 'Сердце горнила', 'heal', '1d4', 'TURN_ENDED', { modifiers: { damageBonus: 2 }, visual: { form: 'halo', motion: 'breathe', motif: 'flame' } }),
    buff('charred_armor', 'Обугленная броня', { armorBonus: -6 }, { polarity: 'negative', visual: { form: 'embers', motion: 'fall', motif: 'shield' } }),
    buff('firebrand', 'Знак огненного клинка', { critBonus: 3, accuracyBonus: 1 }, { visual: { form: 'arcs', motion: 'rise', motif: 'blade' } }),
    buff('volatile_sparks', 'Неистовые искры', { repeatAttack: { dice: '1d6', atLeast: 6 }, damageBonusDice: '1d6' }, { visual: { form: 'orbit', motion: 'zigzag', motif: 'flame' } }),
    buff('ash_choke', 'Пепельное удушье', { accuracyBonus: -3, powerBonus: -2 }, { polarity: 'negative', visual: { form: 'mist', motion: 'fall', motif: 'rock' } }),
    tick('embers_of_life', 'Искры жизни', 'heal', '1d8', 'TURN_STARTED', { healingScale: true, visual: { form: 'flames', motion: 'breathe', motif: 'star' } }),
    tick('flameward', 'Огненный заслон', 'shield', '1d8', 'TURN_STARTED', { modifiers: { armorBonus: 2 }, visual: { form: 'dome', motion: 'rise', motif: 'flame' } }),
  ]),
  ...auraGroup('frost', 0, [
    buff('chilled', 'Промерзание', { initiativeBonus: -3, agilityBonus: -2 }, { polarity: 'negative', visual: { form: 'mist', motion: 'fall', motif: 'crystal' } }),
    tick('frostbite', 'Обморожение', 'damage', '1d4', 'TURN_STARTED', { bypassArmor: true, modifiers: { evasionBonus: -1 }, visual: { form: 'spikes', motion: 'breathe', motif: 'crystal' } }),
    buff('rime_armor', 'Иней на доспехе', { armorBonus: 7, agilityBonus: -2 }, { visual: { form: 'shards', motion: 'breathe', motif: 'shield' } }),
    tick('crystal_shell', 'Хрустальная оболочка', 'shield', '1d8', 'TURN_STARTED', { shieldDuration: 2, visual: { form: 'dome', motion: 'pulse', motif: 'crystal' } }),
    buff('winter_focus', 'Зимняя сосредоточенность', { accuracyBonus: 3, critBonus: 2 }, { visual: { form: 'crown', motion: 'orbit', motif: 'crystal' } }),
    buff('numbing_cold', 'Леденящее онемение', { critBonus: -4 }, { polarity: 'negative', visual: { form: 'chains', motion: 'fall', motif: 'crystal' } }),
    buff('snowveil', 'Снежная пелена', { evasionBonus: 3, armorBonus: 2 }, { visual: { form: 'rain', motion: 'spiral', motif: 'feather' } }),
    tick('glacial_fracture', 'Ледяной надлом', 'damage', '2d4', 'TURN_ENDED', { modifiers: { armorBonus: -3 }, visual: { form: 'shards', motion: 'zigzag', motif: 'crystal' } }),
    buff('white_silence', 'Белое безмолвие', { damageBonus: -3, powerBonus: -3 }, { polarity: 'negative', visual: { form: 'halo', motion: 'breathe', motif: 'moon' } }),
    tick('thawing_pulse', 'Пульс оттепели', 'heal', '1d6', 'TURN_ENDED', { healingScale: true, visual: { form: 'waves', motion: 'rise', motif: 'crystal' } }),
  ]),
  ...auraGroup('storm', 1, [
    buff('storm_clarity', 'Ясность грозы', { accuracyBonus: 3, initiativeBonus: 3 }, { visual: { form: 'eyes', motion: 'zigzag', motif: 'bolt' } }),
    tick('static_charge', 'Статический заряд', 'damage', '1d4', 'TURN_ENDED', { modifiers: { critBonus: -1 }, visual: { form: 'arcs', motion: 'pulse', motif: 'bolt' } }),
    buff('charged_edge', 'Заряженное острие', { damageBonusDice: '1d6', accuracyBonus: 1 }, { visual: { form: 'orbit', motion: 'rise', motif: 'blade' } }),
    buff('storm_stride', 'Поступь бури', { evasionBonus: 3, agilityBonus: 3 }, { visual: { form: 'vortex', motion: 'spiral', motif: 'feather' } }),
    tick('thunder_shell', 'Грозовой панцирь', 'shield', '1d6', 'TURN_STARTED', { healingScale: true, visual: { form: 'dome', motion: 'zigzag', motif: 'bolt', count: 13 } }),
    buff('deafening_roar', 'Оглушительный раскат', { accuracyBonus: -2, initiativeBonus: -2 }, { polarity: 'negative', visual: { form: 'waves', motion: 'pulse', motif: 'bolt' } }),
    buff('eye_of_storm', 'Око бури', { partyGuardDice: '1d6', agilityBonus: -1 }, { visual: { form: 'halo', motion: 'orbit', motif: 'eye' } }),
    buff('tempest_surge', 'Порыв шквала', { repeatAttack: { dice: '1d8', atLeast: 6 }, initiativeBonus: 1 }, { visual: { form: 'wings', motion: 'rise', motif: 'bolt' } }),
    buff('conductive_brand', 'Проводящая метка', { armorBonus: -4, accuracyBonus: -1 }, { polarity: 'negative', visual: { form: 'sigil', motion: 'zigzag', motif: 'bolt' } }),
  ]),
  ...auraGroup('stone', 0, [
    buff('granite_skin', 'Гранитная кожа', { armorBonus: 9, initiativeBonus: -3 }, { visual: { form: 'shards', motion: 'breathe', motif: 'rock' } }),
    buff('mountain_resolve', 'Решимость горы', { damageReduction: 5, agilityBonus: -2 }, { visual: { form: 'spikes', motion: 'pulse', motif: 'rock' } }),
    tick('gravel_guard', 'Гравийный заслон', 'shield', '2d6', 'TURN_STARTED', { duration: 2, visual: { form: 'orbit', motion: 'fall', motif: 'rock' } }),
    buff('earthbound', 'Оковы земли', { initiativeBonus: -5, evasionBonus: -2 }, { polarity: 'negative', visual: { form: 'roots', motion: 'pulse', motif: 'rock' } }),
    tick('splintered_stone', 'Каменные занозы', 'damage', '1d8', 'TURN_ENDED', { tags: ['PHYSICAL'], visual: { form: 'rain', motion: 'fall', motif: 'rock' } }),
    buff('cairn_blessing', 'Благословение кургана', { armorBonus: 4, powerBonus: 3 }, { visual: { form: 'runes', motion: 'breathe', motif: 'rock' } }),
    buff('fault_line', 'Линия разлома', { armorBonus: -8, agilityBonus: -1 }, { polarity: 'negative', visual: { form: 'arcs', motion: 'zigzag', motif: 'rock' } }),
    buff('sheltering_monolith', 'Укрытие монолита', { partyDamageReduction: 3, armorBonus: 2 }, { visual: { form: 'dome', motion: 'breathe', motif: 'rock' } }),
    tick('moss_of_ages', 'Мох веков', 'heal', '1d10', 'TURN_STARTED', { duration: 4, visual: { form: 'mist', motion: 'breathe', motif: 'leaf' } }),
    buff('avalanche_intent', 'Намерение лавины', { damageBonusDice: '1d8', accuracyBonus: -2, critBonus: 2 }, { visual: { form: 'waves', motion: 'fall', motif: 'rock' } }),
  ]),
  ...auraGroup('metal', 0, [
    buff('steel_skin', 'Стальная кожа', { armorBonus: 5 }, { visual: { form: 'shards', motion: 'orbit', motif: 'blade' } }),
    buff('razor_edge', 'Бритвенная грань', { critBonus: 4, damageBonus: 1 }, { visual: { form: 'arcs', motion: 'spiral', motif: 'blade' } }),
    buff('magnetic_ward', 'Магнитный покров', { evasionBonus: 2, armorBonus: 4 }, { visual: { form: 'orbit', motion: 'breathe', motif: 'shield' } }),
    tick('iron_bloom', 'Железный цветок', 'shield', '1d10', 'TURN_STARTED', { shieldDuration: 2, visual: { form: 'spikes', motion: 'rise', motif: 'shield' } }),
    buff('rust', 'Ржавчина', { armorBonus: -5, damageBonus: -2 }, { polarity: 'negative', visual: { form: 'rain', motion: 'fall', motif: 'blade' } }),
    tick('barbed_shackles', 'Зазубренные оковы', 'damage', '1d4', 'TURN_ENDED', { bypassArmor: true, modifiers: { agilityBonus: -3 }, tags: ['BLEED', 'PHYSICAL'], visual: { form: 'chains', motion: 'zigzag', motif: 'blade' } }),
    buff('tempered_will', 'Закалённая воля', { accuracyBonus: 2, armorBonus: 3, critBonus: 1 }, { visual: { form: 'crown', motion: 'pulse', motif: 'shield' } }),
    buff('sword_dance', 'Танец клинков', { repeatAttack: { dice: '1d4', atLeast: 4 }, evasionBonus: 2 }, { visual: { form: 'vortex', motion: 'spiral', motif: 'blade' } }),
    buff('iron_chorus', 'Железный хор', { partyGuardDice: '1d8', initiativeBonus: -3 }, { visual: { form: 'waves', motion: 'breathe', motif: 'shield' } }),
    buff('mercury_step', 'Ртутный шаг', { agilityBonus: 5, initiativeBonus: 2, armorBonus: -2 }, { visual: { form: 'mist', motion: 'zigzag', motif: 'drop' } }),
  ]),
];
