import { auraGroup, buff, tick } from './status-catalog-builders';

export const lifeAuras = [
  ...auraGroup('blood', 1, [
    tick('bleeding', 'Кровотечение', 'damage', '1d4', 'TURN_ENDED', { bypassArmor: true, tags: ['BLEED', 'PHYSICAL'], visual: { form: 'rain', motion: 'fall', motif: 'drop', count: 11, radius: 12, height: 34, speed: 1.15 } }),
    tick('open_wound', 'Рваная рана', 'damage', '1d6', 'TURN_ENDED', { bypassArmor: true, modifiers: { powerBonus: -2 }, tags: ['BLEED'], visual: { form: 'chains', motion: 'pulse', motif: 'claw' } }),
    tick('crimson_mending', 'Багровое восстановление', 'heal', '1d4', 'TURN_STARTED', { healingScale: true, visual: { form: 'waves', motion: 'rise', motif: 'drop' } }),
    tick('sanguine_veil', 'Покров алой росы', 'shield', '1d6', 'TURN_STARTED', { shieldDuration: 1, visual: { form: 'mist', motion: 'breathe', motif: 'drop' } }),
    buff('predators_thirst', 'Жажда хищника', { vampirismDice: '1d4', accuracyBonus: 1 }, { visual: { form: 'eyes', motion: 'orbit', motif: 'fang' } }),
    buff('heart_hunter', 'Охотник за сердцами', { critBonus: 3, damageBonusDice: '1d4' }, { visual: { form: 'crown', motion: 'spiral', motif: 'blade' } }),
    buff('blood_price', 'Цена крови', { damageBonus: 4, armorBonus: -4 }, { visual: { form: 'spikes', motion: 'pulse', motif: 'drop' } }),
    buff('scarlet_covenant', 'Алый завет', { healingShareDice: '1d4' }, { visual: { form: 'runes', motion: 'breathe', motif: 'cross' } }),
    buff('clotting_seal', 'Печать заживления', { preserveHot: { dice: '1d6', atLeast: 5 }, powerBonus: 2 }, { visual: { form: 'sigil', motion: 'pulse', motif: 'rune' } }),
  ]),
  ...auraGroup('holy', 2, [
    buff('divine_protection', 'Божественная защита', { armorBonus: 8, damageReduction: 3 }, { visual: { form: 'dome', motion: 'breathe', motif: 'cross', count: 9, radius: 20, height: 40, speed: .75 } }),
    tick('dawn_mending', 'Исцеление рассвета', 'heal', '1d6', 'TURN_STARTED', { healingScale: true, visual: { form: 'rain', motion: 'fall', motif: 'star' } }),
    buff('consecrated_edge', 'Освящённое лезвие', { accuracyBonus: 2, damageBonusDice: '1d4' }, { visual: { form: 'arcs', motion: 'orbit', motif: 'blade' } }),
    buff('martyrs_vigil', 'Дозор мученика', { partyGuardDice: '1d4', armorBonus: 2 }, { visual: { form: 'wings', motion: 'breathe', motif: 'feather' } }),
    buff('merciful_chorus', 'Хор милосердия', { healingShareDice: '1d6', powerBonus: 2 }, { visual: { form: 'waves', motion: 'rise', motif: 'cross' } }),
    buff('oath_of_sanctuary', 'Клятва убежища', { preserveShield: { dice: '1d6', atLeast: 5 } }, { visual: { form: 'halo', motion: 'pulse', motif: 'shield' } }),
    buff('pilgrims_grace', 'Благодать паломника', { agilityBonus: 3, evasionBonus: 2 }, { visual: { form: 'feathers', motion: 'spiral', motif: 'feather' } }),
    buff('radiant_censure', 'Светлый приговор', { accuracyBonus: -3, critBonus: -2 }, { polarity: 'negative', visual: { form: 'chains', motion: 'pulse', motif: 'cross' } }),
  ]),
  ...auraGroup('nature', 2, [
    buff('rootbound', 'Корневая хватка', { evasionBonus: -3, agilityBonus: -3 }, { polarity: 'negative', visual: { form: 'roots', motion: 'breathe', motif: 'leaf' } }),
    tick('wild_renewal', 'Дикое обновление', 'heal', '2d4', 'TURN_STARTED', { healingScale: true, visual: { form: 'wings', motion: 'rise', motif: 'leaf' } }),
    tick('briar_wound', 'Терновая рана', 'damage', '1d6', 'TURN_ENDED', { tags: ['PHYSICAL'], visual: { form: 'spikes', motion: 'pulse', motif: 'claw' } }),
    buff('oak_heart', 'Сердце дуба', { armorBonus: 6, initiativeBonus: -2 }, { visual: { form: 'chains', motion: 'breathe', motif: 'leaf' } }),
    buff('spring_breath', 'Дыхание весны', { powerBonus: 4 }, { visual: { form: 'mist', motion: 'rise', motif: 'leaf' } }),
    buff('thorn_guard', 'Терновый дозор', { partyGuardDice: '1d4', damageBonusDice: '1d4' }, { visual: { form: 'orbit', motion: 'zigzag', motif: 'leaf' } }),
    buff('wild_instinct', 'Звериное чутьё', { accuracyBonus: 2, evasionBonus: 2, initiativeBonus: 2 }, { visual: { form: 'eyes', motion: 'pulse', motif: 'eye' } }),
    tick('seed_of_return', 'Семя возвращения', 'shield', '1d4', 'TURN_STARTED', { healingScale: true, shieldDuration: 2, visual: { form: 'sigil', motion: 'breathe', motif: 'leaf' } }),
  ]),
  ...auraGroup('shadow', 1, [
    buff('evasiveness', 'Изворотливость', { evasionBonus: 4 }, { visual: { form: 'mist', motion: 'zigzag', motif: 'feather', count: 8, radius: 18, height: 32, speed: 1.45 } }),
    buff('lethality', 'Смертоносность', { critBonus: 5 }, { visual: { form: 'crown', motion: 'orbit', motif: 'blade', count: 6, radius: 16, height: 42, speed: .9 } }),
    buff('veiled_blade', 'Сокрытое лезвие', { accuracyBonus: 3, damageBonusDice: '1d4' }, { visual: { form: 'arcs', motion: 'spiral', motif: 'blade' } }),
    buff('blackout', 'Тьма в глазах', { accuracyBonus: -4 }, { polarity: 'negative', visual: { form: 'eyes', motion: 'breathe', motif: 'eye' } }),
    tick('night_wound', 'Ночная рана', 'damage', '1d8', 'TURN_ENDED', { visual: { form: 'flames', motion: 'fall', motif: 'moon' } }),
    buff('silent_step', 'Беззвучный шаг', { initiativeBonus: 3, agilityBonus: 4 }, { visual: { form: 'feathers', motion: 'fall', motif: 'feather' } }),
    buff('assassins_patience', 'Терпение убийцы', { critBonus: 6, initiativeBonus: -2 }, { visual: { form: 'sigil', motion: 'pulse', motif: 'eye' } }),
    buff('gloom_armor', 'Доспех сумрака', { armorBonus: 4, evasionBonus: 2 }, { visual: { form: 'shards', motion: 'orbit', motif: 'shield' } }),
    buff('shadow_echo', 'Эхо тени', { repeatAttack: { dice: '1d6', atLeast: 5 }, critBonus: 1 }, { visual: { form: 'wings', motion: 'zigzag', motif: 'moon' } }),
  ]),
  ...auraGroup('arcane', 0, [
    buff('arcane_sight', 'Чародейское зрение', { accuracyBonus: 4 }, { visual: { form: 'eyes', motion: 'orbit', motif: 'rune' } }),
    buff('rune_of_force', 'Руна силы', { damageBonusDice: '1d8', accuracyBonus: -1 }, { visual: { form: 'runes', motion: 'pulse', motif: 'rune' } }),
    tick('aether_barrier', 'Эфирный барьер', 'shield', '2d4', 'TURN_STARTED', { shieldDuration: 1, visual: { form: 'dome', motion: 'pulse', motif: 'rune' } }),
    buff('spell_focus', 'Средоточие чар', { powerBonus: 5, critBonus: 2 }, { visual: { form: 'orbit', motion: 'spiral', motif: 'crystal' } }),
    buff('arcane_disruption', 'Разлад чар', { powerBonus: -5, accuracyBonus: -2 }, { polarity: 'negative', visual: { form: 'shards', motion: 'zigzag', motif: 'rune' } }),
    tick('mana_scorch', 'Ожог эфира', 'damage', '1d6', 'TURN_STARTED', { bypassArmor: true, visual: { form: 'flames', motion: 'rise', motif: 'rune' } }),
    buff('mirror_ward', 'Зеркальный покров', { preserveShield: { dice: '1d4', atLeast: 4 }, evasionBonus: 1 }, { visual: { form: 'shards', motion: 'breathe', motif: 'crystal' } }),
    buff('binding_glyph', 'Сковывающий глиф', { initiativeBonus: -4, agilityBonus: -2 }, { polarity: 'negative', visual: { form: 'chains', motion: 'orbit', motif: 'rune' } }),
    buff('overcharge', 'Перенасыщение', { damageBonusDice: '1d10', armorBonus: -5, evasionBonus: -2 }, { duration: 2, visual: { form: 'arcs', motion: 'zigzag', motif: 'bolt' } }),
    buff('perfect_formula', 'Безупречная формула', { accuracyBonus: 2, critBonus: 2, powerBonus: 2 }, { visual: { form: 'sigil', motion: 'orbit', motif: 'star' } }),
  ]),
];
